In [1]:
pip install request

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement request (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for request

In [3]:
pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (26.1.2)
Collecting pip
  Using cached pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.2.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.1.2
    Uninstalling pip-26.1.2:
      Successfully uninstalled pip-26.1.2
Successfully installed pip-26.2.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
%pip install requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

## What is an API?

API stands for **`Application Programming Interface`**.

An API is a way for one software/application to communicate with another software/application and request or exchange data.

For Data Analytics, APIs are commonly used as external data sources.

### Why APIs Exist

APIs allow applications to communicate with external systems without requiring direct access to their internal databases.

Basic workflow: Client → API → Server → Data/Database → API → Client

APIs can control:
- What data can be accessed
- Who can access the data
- How requests should be made
- Authentication
- Rate limits
- Available functionality

### API in Data Analytics

A Data Analyst can use an API to collect data and then analyze it using Python.

Typical workflow: Python → API → JSON → Pandas → Data Cleaning → EDA → Visualization → Business Insights

### API vs Website

| Website | API |
|---|---|
| Mainly designed for humans | Mainly designed for applications |
| Usually displays information visually | Usually returns structured data |
| Browser is commonly used | Python/programs can be used |
| HTML/CSS/JavaScript may be returned | JSON/XML or other structured formats may be returned |

Example API response:

```json
{
    "city": "Delhi",
    "temperature": 32,
    "humidity": 65
}

### Real-world example

Suppose you are building a weather analytics project.

Your Python program needs today's weather:

**`Your Python Program -> API -> Weather Service -> Weather Data -> API -> Your Python Program`**

Your Python program doesn't need to know how the weather company's internal database works.

It simply asks the API: "Give me the weather data for Delhi."

The API sends the data back.

### Request and Response

This is the fundamental API workflow.

#### Request = Your program asks the server for something.

**`Example: "Give me weather data for Delhi."`**

#### Response = The server sends data back.

Example:
{
    "city": "Delhi",
    "temperature": 32,
    "humidity": 65
}

### **`So remember:`**
REQUEST  →  Ask for something

RESPONSE →  Receive something

Python
   ↓
API Request
   ↓
API Server
   ↓
API Response
   ↓
JSON
   ↓
Python
   ↓
Pandas DataFrame
   ↓
Data Cleaning
   ↓
EDA
   ↓
Visualization
   ↓
Business Insights

CLIENT
   │
   │ Request
   ↓
  API
   ↓
SERVER
   ↓
DATABASE
   ↑
   │ Data
SERVER
   ↓
  API
   ↓
CLIENT

Database = stores the ingredients/data
Server = processes the request and performs the work

In [1]:
import requests
import json
import pandas as pd

In [2]:
api_response = {
    "city": "Delhi",
    "temperature": 32,
    "humidity": 65,
    "wind_speed": 12
}
print("city :",api_response['city'])
print("temperature :",api_response['temperature'])
print("humidity :",api_response['humidity'])
print("wind_Speed :",api_response['wind_speed'])

city : Delhi
temperature : 32
humidity : 65
wind_Speed : 12

In [3]:
url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url) # api request send

print(response)

<Response [200]>

In [4]:
response.text

'[\n  {\n    "id": 1,\n    "name": "Leanne Graham",\n    "username": "Bret",\n    "email": "Sincere@april.biz",\n    "address": {\n      "street": "Kulas Light",\n      "suite": "Apt. 556",\n      "city": "Gwenborough",\n      "zipcode": "92998-3874",\n      "geo": {\n        "lat": "-37.3159",\n        "lng": "81.1496"\n      }\n    },\n    "phone": "1-770-736-8031 x56442",\n    "website": "hildegard.org",\n    "company": {\n      "name": "Romaguera-Crona",\n      "catchPhrase": "Multi-layered client-server neural-net",\n      "bs": "harness real-time e-markets"\n    }\n  },\n  {\n    "id": 2,\n    "name": "Ervin Howell",\n    "username": "Antonette",\n    "email": "Shanna@melissa.tv",\n    "address": {\n      "street": "Victor Plains",\n      "suite": "Suite 879",\n      "city": "Wisokyburgh",\n      "zipcode": "90566-7771",\n      "geo": {\n        "lat": "-43.9509",\n        "lng": "-34.4618"\n      }\n    },\n    "phone": "010-692-6593 x09125",\n    "website": "anastasia.net",\n    "company": {\n      "name": "Deckow-Crist",\n      "catchPhrase": "Proactive didactic contingency",\n      "bs": "synergize scalable supply-chains"\n    }\n  },\n  {\n    "id": 3,\n    "name": "Clementine Bauch",\n    "username": "Samantha",\n    "email": "Nathan@yesenia.net",\n    "address": {\n      "street": "Douglas Extension",\n      "suite": "Suite 847",\n      "city": "McKenziehaven",\n      "zipcode": "59590-4157",\n      "geo": {\n        "lat": "-68.6102",\n        "lng": "-47.0653"\n      }\n    },\n    "phone": "1-463-123-4447",\n    "website": "ramiro.info",\n    "company": {\n      "name": "Romaguera-Jacobson",\n      "catchPhrase": "Face to face bifurcated interface",\n      "bs": "e-enable strategic applications"\n    }\n  },\n  {\n    "id": 4,\n    "name": "Patricia Lebsack",\n    "username": "Karianne",\n    "email": "Julianne.OConner@kory.org",\n    "address": {\n      "street": "Hoeger Mall",\n      "suite": "Apt. 692",\n      "city": "South Elvis",\n      "zipcode": "53919-4257",\n      "geo": {\n        "lat": "29.4572",\n        "lng": "-164.2990"\n      }\n    },\n    "phone": "493-170-9623 x156",\n    "website": "kale.biz",\n    "company": {\n      "name": "Robel-Corkery",\n      "catchPhrase": "Multi-tiered zero tolerance productivity",\n      "bs": "transition cutting-edge web services"\n    }\n  },\n  {\n    "id": 5,\n    "name": "Chelsey Dietrich",\n    "username": "Kamren",\n    "email": "Lucio_Hettinger@annie.ca",\n    "address": {\n      "street": "Skiles Walks",\n      "suite": "Suite 351",\n      "city": "Roscoeview",\n      "zipcode": "33263",\n      "geo": {\n        "lat": "-31.8129",\n        "lng": "62.5342"\n      }\n    },\n    "phone": "(254)954-1289",\n    "website": "demarco.info",\n    "company": {\n      "name": "Keebler LLC",\n      "catchPhrase": "User-centric fault-tolerant solution",\n      "bs": "revolutionize end-to-end systems"\n    }\n  },\n  {\n    "id": 6,\n    "name": "Mrs. Dennis Schulist",\n    "username": "Leopoldo_Corkery",\n    "email": "Karley_Dach@jasper.info",\n    "address": {\n      "street": "Norberto Crossing",\n      "suite": "Apt. 950",\n      "city": "South Christy",\n      "zipcode": "23505-1337",\n      "geo": {\n        "lat": "-71.4197",\n        "lng": "71.7478"\n      }\n    },\n    "phone": "1-477-935-8478 x6430",\n    "website": "ola.org",\n    "company": {\n      "name": "Considine-Lockman",\n      "catchPhrase": "Synchronised bottom-line interface",\n      "bs": "e-enable innovative applications"\n    }\n  },\n  {\n    "id": 7,\n    "name": "Kurtis Weissnat",\n    "username": "Elwyn.Skiles",\n    "email": "Telly.Hoeger@billy.biz",\n    "address": {\n      "street": "Rex Trail",\n      "suite": "Suite 280",\n      "city": "Howemouth",\n      "zipcode": "58804-1099",\n      "geo": {\n        "lat": "24.8918",\n        "lng": "21.8984"\n      }\n    },\n    "phone": "210.067.6132",\n    "website": "elvis.io",\n    "company": {\n      "name": "Johns Group",\n      "catchPhrase": "Configurable multimedia task-force",\n      "bs": "generate enterprise e-tailers"\n    }\n  },\n  {\n    "id": 8,\n    "name": "Nicholas Runolfsdottir V",\n    "username": "Maxime_Nienow",\n    "email": "Sherwood@rosamond.me",\n    "address": {\n      "street": "Ellsworth Summit",\n      "suite": "Suite 729",\n      "city": "Aliyaview",\n      "zipcode": "45169",\n      "geo": {\n        "lat": "-14.3990",\n        "lng": "-120.7677"\n      }\n    },\n    "phone": "586.493.6943 x140",\n    "website": "jacynthe.com",\n    "company": {\n      "name": "Abernathy Group",\n      "catchPhrase": "Implemented secondary concept",\n      "bs": "e-enable extensible e-tailers"\n    }\n  },\n  {\n    "id": 9,\n    "name": "Glenna Reichert",\n    "username": "Delphine",\n    "email": "Chaim_McDermott@dana.io",\n    "address": {\n      "street": "Dayna Park",\n      "suite": "Suite 449",\n      "city": "Bartholomebury",\n      "zipcode": "76495-3109",\n      "geo": {\n        "lat": "24.6463",\n        "lng": "-168.8889"\n      }\n    },\n    "phone": "(775)976-6794 x41206",\n    "website": "conrad.com",\n    "company": {\n      "name": "Yost and Sons",\n      "catchPhrase": "Switchable contextually-based project",\n      "bs": "aggregate real-time technologies"\n    }\n  },\n  {\n    "id": 10,\n    "name": "Clementina DuBuque",\n    "username": "Moriah.Stanton",\n    "email": "Rey.Padberg@karina.biz",\n    "address": {\n      "street": "Kattie Turnpike",\n      "suite": "Suite 198",\n      "city": "Lebsackbury",\n      "zipcode": "31428-2261",\n      "geo": {\n        "lat": "-38.2386",\n        "lng": "57.2232"\n      }\n    },\n    "phone": "024-648-3804",\n    "website": "ambrose.net",\n    "company": {\n      "name": "Hoeger LLC",\n      "catchPhrase": "Centralized empowering task-force",\n      "bs": "target end-to-end models"\n    }\n  }\n]'

In [5]:
response.status_code  # checking response of api

200

In [6]:
data = response.json() # converting that response to json

print(data)

[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

In [20]:
print(data[0])

{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}

In [21]:
data[0]['name']

'Leanne Graham'

#### Converting that json data into df

In [7]:
df = pd.DataFrame(data)
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [8]:
df.shape

(10, 8)

### Another API

In [10]:
res = requests.get('https://dummyjson.com/products')  # API request send
print(res)

<Response [200]>

In [11]:
res.status_code # checking response status of the URL

200

In [12]:
res.text

'{"products":[{"id":1,"title":"Essence Mascara Lash Princess","description":"The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.","category":"beauty","price":9.99,"discountPercentage":10.48,"rating":2.56,"stock":99,"tags":["beauty","mascara"],"brand":"Essence","sku":"BEA-ESS-ESS-001","weight":4,"dimensions":{"width":15.14,"height":13.08,"depth":22.99},"warrantyInformation":"1 week warranty","shippingInformation":"Ships in 3-5 business days","availabilityStatus":"In Stock","reviews":[{"rating":3,"comment":"Would not recommend!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Eleanor Collins","reviewerEmail":"eleanor.collins@x.dummyjson.com"},{"rating":4,"comment":"Very satisfied!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Lucas Gordon","reviewerEmail":"lucas.gordon@x.dummyjson.com"},{"rating":5,"comment":"Highly impressed!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Eleanor Collins","reviewerEmail":"eleanor.collins@x.dummyjson.com"}],"returnPolicy":"No return policy","minimumOrderQuantity":48,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"5784719087687","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp"},{"id":2,"title":"Eyeshadow Palette with Mirror","description":"The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it\'s convenient for on-the-go makeup application.","category":"beauty","price":19.99,"discountPercentage":18.19,"rating":2.86,"stock":34,"tags":["beauty","eyeshadow"],"brand":"Glamour Beauty","sku":"BEA-GLA-EYE-002","weight":9,"dimensions":{"width":9.26,"height":22.47,"depth":27.67},"warrantyInformation":"1 year warranty","shippingInformation":"Ships in 2 weeks","availabilityStatus":"In Stock","reviews":[{"rating":5,"comment":"Great product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Savannah Gomez","reviewerEmail":"savannah.gomez@x.dummyjson.com"},{"rating":4,"comment":"Awesome product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Christian Perez","reviewerEmail":"christian.perez@x.dummyjson.com"},{"rating":1,"comment":"Poor quality!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Nicholas Bailey","reviewerEmail":"nicholas.bailey@x.dummyjson.com"}],"returnPolicy":"7 days return policy","minimumOrderQuantity":20,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"9170275171413","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp"},{"id":3,"title":"Powder Canister","description":"The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.","category":"beauty","price":14.99,"discountPercentage":9.84,"rating":4.64,"stock":89,"tags":["beauty","face powder"],"brand":"Velvet Touch","sku":"BEA-VEL-POW-003","weight":8,"dimensions":{"width":29.27,"height":27.93,"depth":20.59},"warrantyInformation":"3 months warranty","shippingInformation":"Ships in 1-2 business days","availabilityStatus":"In Stock","reviews":[{"rating":4,"comment":"Would buy again!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Alexander Jones","reviewerEmail":"alexander.jones@x.dummyjson.com"},{"rating":5,"comment":"Highly impressed!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Elijah Cruz","reviewerEmail":"elijah.cruz@x.dummyjson.com"},{"rating":1,"comment":"Very dissatisfied!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Avery Perez","reviewerEmail":"avery.perez@x.dummyjson.com"}],"returnPolicy":"No return policy","minimumOrderQuantity":22,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"8418883906837","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp"},{"id":4,"title":"Red Lipstick","description":"The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.","category":"beauty","price":12.99,"discountPercentage":12.16,"rating":4.36,"stock":91,"tags":["beauty","lipstick"],"brand":"Chic Cosmetics","sku":"BEA-CHI-LIP-004","weight":1,"dimensions":{"width":18.11,"height":28.38,"depth":22.17},"warrantyInformation":"3 year warranty","shippingInformation":"Ships in 1 week","availabilityStatus":"In Stock","reviews":[{"rating":4,"comment":"Great product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Liam Garcia","reviewerEmail":"liam.garcia@x.dummyjson.com"},{"rating":5,"comment":"Great product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Ruby Andrews","reviewerEmail":"ruby.andrews@x.dummyjson.com"},{"rating":5,"comment":"Would buy again!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Clara Berry","reviewerEmail":"clara.berry@x.dummyjson.com"}],"returnPolicy":"7 days return policy","minimumOrderQuantity":40,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"9467746727219","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp"},{"id":5,"title":"Red Nail Polish","description":"The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.","category":"beauty","price":8.99,"discountPercentage":11.44,"rating":4.32,"stock":79,"tags":["beauty","nail polish"],"brand":"Nail Couture","sku":"BEA-NAI-NAI-005","weight":8,"dimensions":{"width":21.63,"height":16.48,"depth":29.84},"warrantyInformation":"1 month warranty","shippingInformation":"Ships overnight","availabilityStatus":"In Stock","reviews":[{"rating":2,"comment":"Poor quality!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Benjamin Wilson","reviewerEmail":"benjamin.wilson@x.dummyjson.com"},{"rating":5,"comment":"Great product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Liam Smith","reviewerEmail":"liam.smith@x.dummyjson.com"},{"rating":1,"comment":"Very unhappy with my purchase!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Clara Berry","reviewerEmail":"clara.berry@x.dummyjson.com"}],"returnPolicy":"No return policy","minimumOrderQuantity":22,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"4063010628104","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp"},{"id":6,"title":"Calvin Klein CK One","description":"CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It\'s a versatile fragrance suitable for everyday wear.","category":"fragrances","price":49.99,"discountPercentage":1.89,"rating":4.37,"stock":29,"tags":["fragrances","perfumes"],"brand":"Calvin Klein","sku":"FRA-CAL-CAL-006","weight":7,"dimensions":{"width":29.36,"height":27.76,"depth":20.72},"warrantyInformation":"1 week warranty","shippingInformation":"Ships overnight","availabilityStatus":"In Stock","reviews":[{"rating":2,"comment":"Very disappointed!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Layla Young","reviewerEmail":"layla.young@x.dummyjson.com"},{"rating":4,"comment":"Fast shipping!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Daniel Cook","reviewerEmail":"daniel.cook@x.dummyjson.com"},{"rating":3,"comment":"Not as described!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Jacob Cooper","reviewerEmail":"jacob.cooper@x.dummyjson.com"}],"returnPolicy":"90 days return policy","minimumOrderQuantity":9,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"2451534060749","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp","https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp","https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp"},{"id":7,"title":"Chanel Coco Noir Eau De","description":"Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.","category":"fragrances","price":129.99,"discountPercentage":16.51,"rating":4.26,"stock":58,"tags":["fragrances","perfumes"],"brand":"Chanel","sku":"FRA-CHA-CHA-007","weight":7,"dimensions":{"width":24.5,"height":25.7,"depth":25.98},"warrantyInformation":"3 year warranty","shippingInformation":"Ships overnight","availabilityStatus":"In Stock","reviews":[{"rating":4,"comment":"Highly impressed!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Ruby Andrews","reviewerEmail":"ruby.andrews@x.dummyjson.com"},{"rating":5,"comment":"Awesome product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Leah Henderson","reviewerEmail":"leah.henderson@x.dummyjson.com"},{"rating":5,"comment":"Very happy with my purchase!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Xavier Wright","reviewerEmail":"xavier.wright@x.dummyjson.com"}],"returnPolicy":"No return policy","minimumOrderQuantity":1,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"4091737746820","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp"},{"id":8,"title":"Dior J\'adore","description":"J\'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.","category":"fragrances","price":89.99,"discountPercentage":14.72,"rating":3.8,"stock":98,"tags":["fragrances","perfumes"],"brand":"Dior","sku":"FRA-DIO-DIO-008","weight":4,"dimensions":{"width":27.67,"height":28.28,"depth":11.83},"warrantyInformation":"1 week warranty","shippingInformation":"Ships in 2 weeks","availabilityStatus":"In Stock","reviews":[{"rating":5,"comment":"Great value for money!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Nicholas Bailey","reviewerEmail":"nicholas.bailey@x.dummyjson.com"},{"rating":4,"comment":"Great value for money!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Penelope Harper","reviewerEmail":"penelope.harper@x.dummyjson.com"},{"rating":4,"comment":"Great product!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Emma Miller","reviewerEmail":"emma.miller@x.dummyjson.com"}],"returnPolicy":"7 days return policy","minimumOrderQuantity":10,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"1445086097250","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/1.webp","https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/2.webp","https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/fragrances/dior-j\'adore/thumbnail.webp"},{"id":9,"title":"Dolce Shine Eau de","description":"Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It\'s a joyful and youthful scent.","category":"fragrances","price":69.99,"discountPercentage":0.62,"rating":3.96,"stock":4,"tags":["fragrances","perfumes"],"brand":"Dolce & Gabbana","sku":"FRA-DOL-DOL-009","weight":6,"dimensions":{"width":27.28,"height":29.88,"depth":18.3},"warrantyInformation":"3 year warranty","shippingInformation":"Ships in 1 month","availabilityStatus":"Low Stock","reviews":[{"rating":4,"comment":"Would buy again!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Mateo Bennett","reviewerEmail":"mateo.bennett@x.dummyjson.com"},{"rating":4,"comment":"Highly recommended!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Nolan Gonzalez","reviewerEmail":"nolan.gonzalez@x.dummyjson.com"},{"rating":5,"comment":"Very happy with my purchase!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Aurora Lawson","reviewerEmail":"aurora.lawson@x.dummyjson.com"}],"returnPolicy":"7 days return policy","minimumOrderQuantity":2,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"3023868210708","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp"},{"id":10,"title":"Gucci Bloom Eau de","description":"Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It\'s a modern and romantic scent.","category":"fragrances","price":79.99,"discountPercentage":14.39,"rating":2.74,"stock":91,"tags":["fragrances","perfumes"],"brand":"Gucci","sku":"FRA-GUC-GUC-010","weight":7,"dimensions":{"width":20.92,"height":21.68,"depth":11.2},"warrantyInformation":"6 months warranty","shippingInformation":"Ships overnight","availabilityStatus":"In Stock","reviews":[{"rating":1,"comment":"Very dissatisfied!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Cameron Perez","reviewerEmail":"cameron.perez@x.dummyjson.com"},{"rating":5,"comment":"Very happy with my purchase!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Daniel Cook","reviewerEmail":"daniel.cook@x.dummyjson.com"},{"rating":4,"comment":"Highly impressed!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Addison Wright","reviewerEmail":"addison.wright@x.dummyjson.com"}],"returnPolicy":"No return policy","minimumOrderQuantity":2,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"3170832177880","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp"},{"id":11,"title":"Annibale Colombo Bed","description":"The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.","category":"furniture","price":1899.99,"discountPercentage":8.57,"rating":4.77,"stock":88,"tags":["furniture","beds"],"brand":"Annibale Colombo","sku":"FUR-ANN-ANN-011","weight":10,"dimensions":{"width":28.16,"height":25.36,"depth":17.28},"warrantyInformation":"1 year warranty","shippingInformation":"Ships in 1 month","availabilityStatus":"In Stock","reviews":[{"rating":2,"comment":"Would not recommend!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Christopher West","reviewerEmail":"christopher.west@x.dummyjson.com"},{"rating":4,"comment":"Highly impressed!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Vivian Carter","reviewerEmail":"vivian.carter@x.dummyjson.com"},{"rating":1,"comment":"Poor quality!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Mason Wright","reviewerEmail":"mason.wright@x.dummyjson.com"}],"returnPolicy":"No return policy","minimumOrderQuantity":1,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"3610757456581","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp"},{"id":12,"title":"Annibale Colombo Sofa","description":"The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.","category":"furniture","price":2499.99,"discountPercentage":14.4,"rating":3.92,"stock":60,"tags":["furniture","sofas"],"brand":"Annibale Colombo","sku":"FUR-ANN-ANN-012","weight":6,"dimensions":{"width":12.75,"height":20.55,"depth":19.06},"warrantyInformation":"Lifetime warranty","shippingInformation":"Ships in 1 week","availabilityStatus":"In Stock","reviews":[{"rating":3,"comment":"Very unhappy with my purchase!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Christian Perez","reviewerEmail":"christian.perez@x.dummyjson.com"},{"rating":5,"comment":"Fast shipping!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Lillian Bishop","reviewerEmail":"lillian.bishop@x.dummyjson.com"},{"rating":1,"comment":"Poor quality!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Lillian Simmons","reviewerEmail":"lillian.simmons@x.dummyjson.com"}],"returnPolicy":"7 days return policy","minimumOrderQuantity":1,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"1777662847736","qrCode":"https://cdn.dummyjson.com/public/qr-code.png"},"images":["https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp"],"thumbnail":"https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp"},{"id":13,"title":"Bedside Table African Cherry","description":"The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.","category":"furniture","price":299.99,"discountPercentage":19.09,"rating":2.87,"stock":64,"tags":["furniture","bedside tables"],"brand":"Furniture Co.","sku":"FUR-FUR-BED-013","weight":2,"dimensions":{"width":13.47,"height":24.99,"depth":27.35},"warrantyInformation":"5 year warranty","shippingInformation":"Ships overnight","availabilityStatus":"In Stock","reviews":[{"rating":4,"comment":"Excellent quality!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Aaliyah Hanson","reviewerEmail":"aaliyah.hanson@x.dummyjson.com"},{"rating":4,"comment":"Excellent quality!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Liam Smith","reviewerEmail":"liam.smith@x.dummyjson.com"},{"rating":4,"comment":"Highly recommended!","date":"2025-04-30T09:41:02.053Z","reviewerName":"Avery Barnes","reviewerEmail":"avery.barnes@x.dummyjson.com"}],"returnPolicy":"7 days return policy","minimumOrderQuantity":3,"meta":{"createdAt":"2025-04-30T09:41:02.053Z","updatedAt":"2025-04-30T09:41:02.053Z","barcode":"6441287925979","qrCode":"https://cdn.dummyjson.c

In [13]:
data2 = res.json()
print(data2)

{'products': [{'id': 1, 'title': 'Essence Mascara Lash Princess', 'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', 'category': 'beauty', 'price': 9.99, 'discountPercentage': 10.48, 'rating': 2.56, 'stock': 99, 'tags': ['beauty', 'mascara'], 'brand': 'Essence', 'sku': 'BEA-ESS-ESS-001', 'weight': 4, 'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99}, 'warrantyInformation': '1 week warranty', 'shippingInformation': 'Ships in 3-5 business days', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 3, 'comment': 'Would not recommend!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Eleanor Collins', 'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}, {'rating': 4, 'comment': 'Very satisfied!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Lucas Gordon', 'reviewerEmail': 'lucas.gordon@x.dummyjson.com'}, {'rating': 5, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Eleanor Collins', 'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 48, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '5784719087687', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'}, {'id': 2, 'title': 'Eyeshadow Palette with Mirror', 'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.", 'category': 'beauty', 'price': 19.99, 'discountPercentage': 18.19, 'rating': 2.86, 'stock': 34, 'tags': ['beauty', 'eyeshadow'], 'brand': 'Glamour Beauty', 'sku': 'BEA-GLA-EYE-002', 'weight': 9, 'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67}, 'warrantyInformation': '1 year warranty', 'shippingInformation': 'Ships in 2 weeks', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 5, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Savannah Gomez', 'reviewerEmail': 'savannah.gomez@x.dummyjson.com'}, {'rating': 4, 'comment': 'Awesome product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Christian Perez', 'reviewerEmail': 'christian.perez@x.dummyjson.com'}, {'rating': 1, 'comment': 'Poor quality!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Nicholas Bailey', 'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}], 'returnPolicy': '7 days return policy', 'minimumOrderQuantity': 20, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '9170275171413', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'}, {'id': 3, 'title': 'Powder Canister', 'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.', 'category': 'beauty', 'price': 14.99, 'discountPercentage': 9.84, 'rating': 4.64, 'stock': 89, 'tags': ['beauty', 'face powder'], 'brand': 'Velvet Touch', 'sku': 'BEA-VEL-POW-003', 'weight': 8, 'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59}, 'warrantyInformation': '3 months warranty', 'shippingInformation': 'Ships in 1-2 business days', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 4, 'comment': 'Would buy again!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Alexander Jones', 'reviewerEmail': 'alexander.jones@x.dummyjson.com'}, {'rating': 5, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Elijah Cruz', 'reviewerEmail': 'elijah.cruz@x.dummyjson.com'}, {'rating': 1, 'comment': 'Very dissatisfied!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Avery Perez', 'reviewerEmail': 'avery.perez@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 22, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '8418883906837', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'}, {'id': 4, 'title': 'Red Lipstick', 'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.', 'category': 'beauty', 'price': 12.99, 'discountPercentage': 12.16, 'rating': 4.36, 'stock': 91, 'tags': ['beauty', 'lipstick'], 'brand': 'Chic Cosmetics', 'sku': 'BEA-CHI-LIP-004', 'weight': 1, 'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17}, 'warrantyInformation': '3 year warranty', 'shippingInformation': 'Ships in 1 week', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 4, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Liam Garcia', 'reviewerEmail': 'liam.garcia@x.dummyjson.com'}, {'rating': 5, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Ruby Andrews', 'reviewerEmail': 'ruby.andrews@x.dummyjson.com'}, {'rating': 5, 'comment': 'Would buy again!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Clara Berry', 'reviewerEmail': 'clara.berry@x.dummyjson.com'}], 'returnPolicy': '7 days return policy', 'minimumOrderQuantity': 40, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '9467746727219', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'}, {'id': 5, 'title': 'Red Nail Polish', 'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.', 'category': 'beauty', 'price': 8.99, 'discountPercentage': 11.44, 'rating': 4.32, 'stock': 79, 'tags': ['beauty', 'nail polish'], 'brand': 'Nail Couture', 'sku': 'BEA-NAI-NAI-005', 'weight': 8, 'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84}, 'warrantyInformation': '1 month warranty', 'shippingInformation': 'Ships overnight', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 2, 'comment': 'Poor quality!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Benjamin Wilson', 'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'}, {'rating': 5, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Liam Smith', 'reviewerEmail': 'liam.smith@x.dummyjson.com'}, {'rating': 1, 'comment': 'Very unhappy with my purchase!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Clara Berry', 'reviewerEmail': 'clara.berry@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 22, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '4063010628104', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'}, {'id': 6, 'title': 'Calvin Klein CK One', 'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.", 'category': 'fragrances', 'price': 49.99, 'discountPercentage': 1.89, 'rating': 4.37, 'stock': 29, 'tags': ['fragrances', 'perfumes'], 'brand': 'Calvin Klein', 'sku': 'FRA-CAL-CAL-006', 'weight': 7, 'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72}, 'warrantyInformation': '1 week warranty', 'shippingInformation': 'Ships overnight', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 2, 'comment': 'Very disappointed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Layla Young', 'reviewerEmail': 'layla.young@x.dummyjson.com'}, {'rating': 4, 'comment': 'Fast shipping!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Daniel Cook', 'reviewerEmail': 'daniel.cook@x.dummyjson.com'}, {'rating': 3, 'comment': 'Not as described!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Jacob Cooper', 'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}], 'returnPolicy': '90 days return policy', 'minimumOrderQuantity': 9, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '2451534060749', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'}, {'id': 7, 'title': 'Chanel Coco Noir Eau De', 'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.', 'category': 'fragrances', 'price': 129.99, 'discountPercentage': 16.51, 'rating': 4.26, 'stock': 58, 'tags': ['fragrances', 'perfumes'], 'brand': 'Chanel', 'sku': 'FRA-CHA-CHA-007', 'weight': 7, 'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98}, 'warrantyInformation': '3 year warranty', 'shippingInformation': 'Ships overnight', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 4, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Ruby Andrews', 'reviewerEmail': 'ruby.andrews@x.dummyjson.com'}, {'rating': 5, 'comment': 'Awesome product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Leah Henderson', 'reviewerEmail': 'leah.henderson@x.dummyjson.com'}, {'rating': 5, 'comment': 'Very happy with my purchase!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Xavier Wright', 'reviewerEmail': 'xavier.wright@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 1, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '4091737746820', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'}, {'id': 8, 'title': "Dior J'adore", 'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.", 'category': 'fragrances', 'price': 89.99, 'discountPercentage': 14.72, 'rating': 3.8, 'stock': 98, 'tags': ['fragrances', 'perfumes'], 'brand': 'Dior', 'sku': 'FRA-DIO-DIO-008', 'weight': 4, 'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83}, 'warrantyInformation': '1 week warranty', 'shippingInformation': 'Ships in 2 weeks', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 5, 'comment': 'Great value for money!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Nicholas Bailey', 'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}, {'rating': 4, 'comment': 'Great value for money!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Penelope Harper', 'reviewerEmail': 'penelope.harper@x.dummyjson.com'}, {'rating': 4, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Emma Miller', 'reviewerEmail': 'emma.miller@x.dummyjson.com'}], 'returnPolicy': '7 days return policy', 'minimumOrderQuantity': 10, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '1445086097250', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp", "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp", "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"], 'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}, {'id': 9, 'title': 'Dolce Shine Eau de', 'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.", 'category': 'fragrances', 'price': 69.99, 'discountPercentage': 0.62, 'rating': 3.96, 'stock': 4, 'tags': ['fragrances', 'perfumes'], 'brand': 'Dolce & Gabbana', 'sku': 'FRA-DOL-DOL-009', 'weight': 6, 'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3}, 'warrantyInformation': '3 year warranty', 'shippingInformation': 'Ships in 1 month', 'availabilityStatus': 'Low Stock', 'reviews': [{'rating': 4, 'comment': 'Would buy again!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Mateo Bennett', 'reviewerEmail': 'mateo.bennett@x.dummyjson.com'}, {'rating': 4, 'comment': 'Highly recommended!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Nolan Gonzalez', 'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'}, {'rating': 5, 'comment': 'Very happy with my purchase!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Aurora Lawson', 'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}], 'returnPolicy': '7 days return policy', 'minimumOrderQuantity': 2, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '3023868210708', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'}, {'id': 10, 'title': 'Gucci Bloom Eau de', 'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.", 'category': 'fragrances', 'price': 79.99, 'discountPercentage': 14.39, 'rating': 2.74, 'stock': 91, 'tags': ['fragrances', 'perfumes'], 'brand': 'Gucci', 'sku': 'FRA-GUC-GUC-010', 'weight': 7, 'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2}, 'warrantyInformation': '6 months warranty', 'shippingInformation': 'Ships overnight', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 1, 'comment': 'Very dissatisfied!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Cameron Perez', 'reviewerEmail': 'cameron.perez@x.dummyjson.com'}, {'rating': 5, 'comment': 'Very happy with my purchase!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Daniel Cook', 'reviewerEmail': 'daniel.cook@x.dummyjson.com'}, {'rating': 4, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Addison Wright', 'reviewerEmail': 'addison.wright@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 2, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '3170832177880', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp', 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp', 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'}, {'id': 11, 'title': 'Annibale Colombo Bed', 'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.', 'category': 'furniture', 'price': 1899.99, 'discountPercentage': 8.57, 'rating': 4.77, 'stock': 88, 'tags': ['furniture', 'beds'], 'brand': 'Annibale Colombo', 'sku': 'FUR-ANN-ANN-011', 'weight': 10, 'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28}, 'warrantyInformation': '1 year warranty', 'shippingInformation': 'Ships in 1 month', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 2, 'comment': 'Would not recommend!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Christopher West', 'reviewerEmail': 'christopher.west@x.dummyjson.com'}, {'rating': 4, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Vivian Carter', 'reviewerEmail': 'vivian.carter@x.dummyjson.com'}, {'rating': 1, 'comment': 'Poor quality!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Mason Wright', 'reviewerEmail': 'mason.wright@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 1, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '3610757456581', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'}, {'id': 12, 'title': 'Annibale Colombo Sofa', 'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.', 'category': 'furniture', 'price': 2499.99, 'discountPercentage': 14.4, 'rating': 3.92, 'stock': 60, 'tags': ['furniture', 'sofas'], 'brand': 'Annibale Colombo', 'sku': 'FUR-ANN-ANN-012', 'weight': 6, 'dimensions': {'width': 12.75, 'height': 20.55, 'depth': 19.06}, 'warrantyInformation': 'Lifetime warranty', 'shippingInformation': 'Ships in 1 week', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 3, 'comment': 'Very unhappy with my purchase!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Christian Perez', 'reviewerEmail': 'christian.perez@x.dummyjson.com'}, {'rating': 5, 'comment': 'Fast shipping!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Lillian Bishop', 'reviewerEmail': 'lillian.bishop@x.dummyjson.com'}, {'rating': 1, 'comment': 'Poor quality!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Lillian Simmons', 'reviewerEmail': 'lillian.simmons@x.dummyjson.com'}], 'returnPolicy': '7 days return policy', 'minimumOrderQuantity': 1, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '1777662847736', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp', 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp'}, {'id': 13, 'title': 'Bedside Table African Cherry', 'description': 'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.', '

In [35]:
print(data2["products"][0])

{'id': 1, 'title': 'Essence Mascara Lash Princess', 'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', 'category': 'beauty', 'price': 9.99, 'discountPercentage': 10.48, 'rating': 2.56, 'stock': 99, 'tags': ['beauty', 'mascara'], 'brand': 'Essence', 'sku': 'BEA-ESS-ESS-001', 'weight': 4, 'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99}, 'warrantyInformation': '1 week warranty', 'shippingInformation': 'Ships in 3-5 business days', 'availabilityStatus': 'In Stock', 'reviews': [{'rating': 3, 'comment': 'Would not recommend!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Eleanor Collins', 'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}, {'rating': 4, 'comment': 'Very satisfied!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Lucas Gordon', 'reviewerEmail': 'lucas.gordon@x.dummyjson.com'}, {'rating': 5, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Eleanor Collins', 'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}], 'returnPolicy': 'No return policy', 'minimumOrderQuantity': 48, 'meta': {'createdAt': '2025-04-30T09:41:02.053Z', 'updatedAt': '2025-04-30T09:41:02.053Z', 'barcode': '5784719087687', 'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'}, 'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'], 'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'}

#### Extract the title, price and rating of the first product

In [38]:
name = data2["products"][0]["title"]
price = data2["products"][0]["price"]
rating = data2["products"][0]["rating"]

print(name)
print(price)
print(rating)

Essence Mascara Lash Princess
9.99
2.56

In [39]:
print(data2["products"][0]["title"])
print(data2["products"][0]["price"])
print(data2["products"][0]["rating"])

Essence Mascara Lash Princess
9.99
2.56

In [19]:
df2 = pd.DataFrame(data2)
df2

                                             products  total  skip  limit
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194     0     30
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194     0     30
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194     0     30
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194     0     30
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194     0     30
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194     0     30
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194     0     30
12  {'id': 13, 'title': 'Bedside Table African Che...    194     0     30
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194     0     30
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194     0     30
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194     0     30
16  {'id': 17, 'title': 'Beef Steak', 'description...    194     0     30
17  {'id': 18, 'title': 'Cat Food', 'description':...    194     0     30
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194     0     30
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194     0     30
20  {'id': 21, 'title': 'Cucumber', 'description':...    194     0     30
21  {'id': 22, 'title': 'Dog Food', 'description':...    194     0     30
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194     0     30
23  {'id': 24, 'title': 'Fish Steak', 'description...    194     0     30
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194     0     30
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194     0     30
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194     0     30
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194     0     30
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194     0     30
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194     0     30

In [20]:
df2['products']

0     {'id': 1, 'title': 'Essence Mascara Lash Princ...
1     {'id': 2, 'title': 'Eyeshadow Palette with Mir...
2     {'id': 3, 'title': 'Powder Canister', 'descrip...
3     {'id': 4, 'title': 'Red Lipstick', 'descriptio...
4     {'id': 5, 'title': 'Red Nail Polish', 'descrip...
5     {'id': 6, 'title': 'Calvin Klein CK One', 'des...
6     {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...
7     {'id': 8, 'title': 'Dior J'adore', 'descriptio...
8     {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...
9     {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...
10    {'id': 11, 'title': 'Annibale Colombo Bed', 'd...
11    {'id': 12, 'title': 'Annibale Colombo Sofa', '...
12    {'id': 13, 'title': 'Bedside Table African Che...
13    {'id': 14, 'title': 'Knoll Saarinen Executive ...
14    {'id': 15, 'title': 'Wooden Bathroom Sink With...
15    {'id': 16, 'title': 'Apple', 'description': 'F...
16    {'id': 17, 'title': 'Beef Steak', 'description...
17    {'id': 18, 'title': 'Cat Food', 'description':...
18    {'id': 19, 'title': 'Chicken Meat', 'descripti...
19    {'id': 20, 'title': 'Cooking Oil', 'descriptio...
20    {'id': 21, 'title': 'Cucumber', 'description':...
21    {'id': 22, 'title': 'Dog Food', 'description':...
22    {'id': 23, 'title': 'Eggs', 'description': 'Fr...
23    {'id': 24, 'title': 'Fish Steak', 'description...
24    {'id': 25, 'title': 'Green Bell Pepper', 'desc...
25    {'id': 26, 'title': 'Green Chili Pepper', 'des...
26    {'id': 27, 'title': 'Honey Jar', 'description'...
27    {'id': 28, 'title': 'Ice Cream', 'description'...
28    {'id': 29, 'title': 'Juice', 'description': 'R...
29    {'id': 30, 'title': 'Kiwi', 'description': 'Nu...
Name: products, dtype: object

In [21]:
df2["products"][0].keys()

dict_keys(['id', 'title', 'description', 'category', 'price', 'discountPercentage', 'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions', 'warrantyInformation', 'shippingInformation', 'availabilityStatus', 'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images', 'thumbnail'])

In [22]:
df2.head()

                                            products  total  skip  limit
0  {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1  {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2  {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3  {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4  {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30

In [17]:
df2['title'] = df2['products'].apply(lambda x: x['title'])
df2['title']

0                 Essence Mascara Lash Princess
1                 Eyeshadow Palette with Mirror
2                               Powder Canister
3                                  Red Lipstick
4                               Red Nail Polish
5                           Calvin Klein CK One
6                       Chanel Coco Noir Eau De
7                                  Dior J'adore
8                            Dolce Shine Eau de
9                            Gucci Bloom Eau de
10                         Annibale Colombo Bed
11                        Annibale Colombo Sofa
12                 Bedside Table African Cherry
13    Knoll Saarinen Executive Conference Chair
14             Wooden Bathroom Sink With Mirror
15                                        Apple
16                                   Beef Steak
17                                     Cat Food
18                                 Chicken Meat
19                                  Cooking Oil
20                                     Cucumber
21                                     Dog Food
22                                         Eggs
23                                   Fish Steak
24                            Green Bell Pepper
25                           Green Chili Pepper
26                                    Honey Jar
27                                    Ice Cream
28                                        Juice
29                                         Kiwi
Name: title, dtype: object

In [18]:
df2.head()

,products,total,skip,limit,title
0,"{'id': 1, 'title': 'Essence Mascara Lash Princ...",194,0,30,Essence Mascara Lash Princess
1,"{'id': 2, 'title': 'Eyeshadow Palette with Mir...",194,0,30,Eyeshadow Palette with Mirror
2,"{'id': 3, 'title': 'Powder Canister', 'descrip...",194,0,30,Powder Canister
3,"{'id': 4, 'title': 'Red Lipstick', 'descriptio...",194,0,30,Red Lipstick
4,"{'id': 5, 'title': 'Red Nail Polish', 'descrip...",194,0,30,Red Nail Polish

In [50]:
df2['tags'] = df2['products'].apply(lambda x: x['tags'])
df2['tags']

0               [beauty, mascara]
1             [beauty, eyeshadow]
2           [beauty, face powder]
3              [beauty, lipstick]
4           [beauty, nail polish]
5          [fragrances, perfumes]
6          [fragrances, perfumes]
7          [fragrances, perfumes]
8          [fragrances, perfumes]
9          [fragrances, perfumes]
10              [furniture, beds]
11             [furniture, sofas]
12    [furniture, bedside tables]
13     [furniture, office chairs]
14          [furniture, bathroom]
15                       [fruits]
16                         [meat]
17       [pet supplies, cat food]
18                         [meat]
19           [cooking essentials]
20                   [vegetables]
21       [pet supplies, dog food]
22                        [dairy]
23                      [seafood]
24                   [vegetables]
25                   [vegetables]
26                   [condiments]
27                     [desserts]
28                    [beverages]
29                       [fruits]
Name: tags, dtype: object

In [51]:
df2['tag1'] = df2["tags"].apply(lambda x: x[0])
df2['tag2'] = df2['tags'].apply(lambda x: x[1])

IndexError: list index out of range

In [52]:
df2['tag1'] = df2["tags"].apply(lambda x: x[0])
df2['tag2'] = df2['tags'].apply(lambda x: x[1] if len(x) > 1 else None)

In [53]:
df2.head()

,products,total,skip,limit,title,tags,tag1,tag2
0,"{'id': 1, 'title': 'Essence Mascara Lash Princ...",194,0,30,Essence Mascara Lash Princess,"[beauty, mascara]",beauty,mascara
1,"{'id': 2, 'title': 'Eyeshadow Palette with Mir...",194,0,30,Eyeshadow Palette with Mirror,"[beauty, eyeshadow]",beauty,eyeshadow
2,"{'id': 3, 'title': 'Powder Canister', 'descrip...",194,0,30,Powder Canister,"[beauty, face powder]",beauty,face powder
3,"{'id': 4, 'title': 'Red Lipstick', 'descriptio...",194,0,30,Red Lipstick,"[beauty, lipstick]",beauty,lipstick
4,"{'id': 5, 'title': 'Red Nail Polish', 'descrip...",194,0,30,Red Nail Polish,"[beauty, nail polish]",beauty,nail polish

### Expanding products column into multiple columns and then concatinating it with the original df

In [23]:
products = df2["products"].apply(pd.Series)

df2 = pd.concat([products, df2[["total", "skip", "limit"]]], axis=1)

In [25]:
df2.head(2)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,total,skip,limit
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,194,0,30
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,194,0,30

In [26]:
df2['tag1'] = df2["tags"].apply(lambda x: x[0] if len(x) > 1 else None)
df2['tag2'] = df2['tags'].apply(lambda x: x[1] if len(x) > 1 else None)

In [27]:
df2.head(2)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,total,skip,limit,tag1,tag2
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,194,0,30,beauty,mascara
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,194,0,30,beauty,eyeshadow

In [29]:
df2.drop(columns=['tag1','tag2'],inplace=True)
df2.head(2)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,total,skip,limit
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,194,0,30
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,194,0,30

In [32]:
print(f"Number of Rows : {df2.shape[0]} | Number of Columns : {df2.shape[1]} ")

Number of Rows : 30 | Number of Columns : 25

In [30]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    30 non-null     int64
 1   title                 30 non-null     object
 2   description           30 non-null     object
 3   category              30 non-null     object
 4   price                 30 non-null     float64
 5   discountPercentage    30 non-null     float64
 6   rating                30 non-null     float64
 7   stock                 30 non-null     int64
 8   tags                  30 non-null     object
 9   brand                 15 non-null     object
 10  sku                   30 non-null     object
 11  weight                30 non-null     int64
 12  dimensions            30 non-null     object
 13  warrantyInformation   30 non-null     object
 14  shippingInformation   30 non-null     object
 15  availabilityStatus    30 non-null     object
 16  reviews               30 non-null     object
 17  returnPolicy          30 non-null     object
 18  minimumOrderQuantity  30 non-null     int64
 19  meta                  30 non-null     object
 20  images                30 non-null     object
 21  thumbnail             30 non-null     object
 22  total                 30 non-null     int64
 23  skip                  30 non-null     int64
 24  limit                 30 non-null     int64
dtypes: float64(3), int64(7), object(15)
memory usage: 6.0+ KB

In [33]:
df2['dimensions']

0     {'width': 15.14, 'height': 13.08, 'depth': 22.99}
1      {'width': 9.26, 'height': 22.47, 'depth': 27.67}
2     {'width': 29.27, 'height': 27.93, 'depth': 20.59}
3     {'width': 18.11, 'height': 28.38, 'depth': 22.17}
4     {'width': 21.63, 'height': 16.48, 'depth': 29.84}
5     {'width': 29.36, 'height': 27.76, 'depth': 20.72}
6       {'width': 24.5, 'height': 25.7, 'depth': 25.98}
7     {'width': 27.67, 'height': 28.28, 'depth': 11.83}
8      {'width': 27.28, 'height': 29.88, 'depth': 18.3}
9      {'width': 20.92, 'height': 21.68, 'depth': 11.2}
10    {'width': 28.16, 'height': 25.36, 'depth': 17.28}
11    {'width': 12.75, 'height': 20.55, 'depth': 19.06}
12    {'width': 13.47, 'height': 24.99, 'depth': 27.35}
13       {'width': 13.81, 'height': 7.5, 'depth': 5.62}
14      {'width': 7.98, 'height': 8.88, 'depth': 28.46}
15     {'width': 13.66, 'height': 11.01, 'depth': 9.73}
16      {'width': 18.9, 'height': 5.77, 'depth': 18.57}
17     {'width': 18.08, 'height': 9.26, 'depth': 21.86}
18    {'width': 11.03, 'height': 22.11, 'depth': 16.01}
19    {'width': 19.95, 'height': 27.54, 'depth': 24.86}
20     {'width': 12.8, 'height': 28.38, 'depth': 21.34}
21     {'width': 16.93, 'height': 27.15, 'depth': 9.29}
22     {'width': 11.42, 'height': 7.44, 'depth': 16.95}
23    {'width': 14.95, 'height': 26.31, 'depth': 11.27}
24    {'width': 15.33, 'height': 26.65, 'depth': 14.44}
25    {'width': 15.38, 'height': 18.12, 'depth': 19.92}
26     {'width': 9.28, 'height': 21.72, 'depth': 17.74}
27     {'width': 14.83, 'height': 15.07, 'depth': 24.2}
28    {'width': 18.56, 'height': 21.46, 'depth': 28.02}
29     {'width': 19.4, 'height': 18.67, 'depth': 17.13}
Name: dimensions, dtype: object

In [34]:
df2.sample()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,total,skip,limit
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,In Stock,"[{'rating': 5, 'comment': 'Very pleased!', 'da...",No return policy,42,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,194,0,30

In [35]:
dimensions = df2["dimensions"].apply(pd.Series)

df2 = pd.concat([df2, dimensions], axis=1)

In [36]:
df2.sample()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,meta,images,thumbnail,total,skip,limit,width,height,depth
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,194,0,30,24.5,25.7,25.98

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    30 non-null     int64
 1   title                 30 non-null     object
 2   description           30 non-null     object
 3   category              30 non-null     object
 4   price                 30 non-null     float64
 5   discountPercentage    30 non-null     float64
 6   rating                30 non-null     float64
 7   stock                 30 non-null     int64
 8   tags                  30 non-null     object
 9   brand                 15 non-null     object
 10  sku                   30 non-null     object
 11  weight                30 non-null     int64
 12  dimensions            30 non-null     object
 13  warrantyInformation   30 non-null     object
 14  shippingInformation   30 non-null     object
 15  availabilityStatus    30 non-null     object
 16  reviews               30 non-null     object
 17  returnPolicy          30 non-null     object
 18  minimumOrderQuantity  30 non-null     int64
 19  meta                  30 non-null     object
 20  images                30 non-null     object
 21  thumbnail             30 non-null     object
 22  total                 30 non-null     int64
 23  skip                  30 non-null     int64
 24  limit                 30 non-null     int64
 25  width                 30 non-null     float64
 26  height                30 non-null     float64
 27  depth                 30 non-null     float64
dtypes: float64(6), int64(7), object(15)
memory usage: 6.7+ KB