In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
df = pd.read_csv('synthetic_ecommerce_eda_messy.csv')

In [38]:
df.shape

(53664, 20)

In [39]:
df.head()

,order_id,customer_id,order_date,customer_age,city,region,product_category,quantity,unit_price,discount_pct,order_total,payment_method,sales_channel,shipping_weight,order_status,is_returning_customer,customer_rating,order_notes,unused_column,data_source
0,ORD130258,CUST10936,2023-10-16,NaN,Chicago,East,Electronics,2,35.93,32.3,48.65,Cash on Delivery,Website,14.70,Delivered,False,3.5,Deliver after 5 PM,NaN,Synthetic_Ecommerce
1,ORD123513,CUST21513,2024-09-08,32.0,Dallas,South,Clothing,5,130.16,4.3,622.82,Cash on Delivery,Mobile App,10.22,Delivered,True,4.1,Leave at door,NaN,Synthetic_Ecommerce
2,ORD127346,CUST11924,2025-09-19,40.0,Chicago,West,Beauty,6,25.29,12.5,132.77,Cash on Delivery,Marketplace,19.84,Delivered,True,4.8,Fragile item,NaN,Synthetic_Ecommerce
3,ORD133311,CUST19434,2023-08-25,37.0,Dallas,Midwest,Sports,1,181.38,8.4,166.14,Credit Card,Marketplace,20.16,Delivered,True,4.1,Deliver after 5 PM,NaN,Synthetic_Ecommerce
4,ORD129034,CUST14567,2024-05-24,59.0,Houston,East,Electronics,6,69.46,30.9,287.98,UPI,Marketplace,18.69,Delivered,True,4.5,No special instructions,NaN,Synthetic_Ecommerce

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53664 entries, 0 to 53663
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               53664 non-null  object
 1   customer_id            53664 non-null  object
 2   order_date             53664 non-null  object
 3   customer_age           49925 non-null  float64
 4   city                   53664 non-null  object
 5   region                 53664 non-null  object
 6   product_category       53664 non-null  object
 7   quantity               53664 non-null  int64
 8   unit_price             53664 non-null  object
 9   discount_pct           50438 non-null  float64
 10  order_total            53664 non-null  object
 11  payment_method         51500 non-null  object
 12  sales_channel          53664 non-null  object
 13  shipping_weight        52048 non-null  float64
 14  order_status           53664 non-null  object
 15  is_returning_customer  53664 non-null  bool
 16  customer_rating        48612 non-null  float64
 17  order_notes            48288 non-null  object
 18  unused_column          0 non-null      float64
 19  data_source            53664 non-null  object
dtypes: bool(1), float64(5), int64(1), object(13)
memory usage: 7.8+ MB

In [41]:
df.isnull().mean().sort_values(ascending=False) * 100

unused_column            100.000000
order_notes               10.017889
customer_rating            9.414132
customer_age               6.967427
discount_pct               6.011479
payment_method             4.032499
shipping_weight            3.011330
order_id                   0.000000
order_date                 0.000000
customer_id                0.000000
city                       0.000000
region                     0.000000
order_total                0.000000
unit_price                 0.000000
product_category           0.000000
quantity                   0.000000
is_returning_customer      0.000000
order_status               0.000000
sales_channel              0.000000
data_source                0.000000
dtype: float64

In [42]:
df = df.drop(columns='unused_column')

In [43]:
df.duplicated().sum()

np.int64(849)

In [44]:
df['order_id'].duplicated().sum()

np.int64(1075)

In [45]:
dupe_ids = df[df.duplicated(subset='order_id', keep=False)].sort_values('order_id')
dupe_ids.head(20)

,order_id,customer_id,order_date,customer_age,city,region,product_category,quantity,unit_price,discount_pct,order_total,payment_method,sales_channel,shipping_weight,order_status,is_returning_customer,customer_rating,order_notes,data_source
11467,ORD100040,CUST11982,2024-08-19,42.0,New York,East,Sports,4,68.17,15.6,230.14,Credit Card,Store,12.21,Processing,True,3.4,Gift order,Synthetic_Ecommerce
18494,ORD100040,CUST11982,2024-08-19,42.0,New York,East,Sports,4,68.17,15.6,230.14,Credit Card,Store,12.21,Processing,True,3.4,Gift order,Synthetic_Ecommerce
37677,ORD100147,CUST12807,2025-09-11,31.0,New York,South,Electronics,3,103.11,36.6,196.12,Credit Card,Mobile App,23.32,Delivered,True,NaN,Call before delivery,Synthetic_Ecommerce
46118,ORD100147,CUST12807,2025-09-11,31.0,New York,South,Electronics,3,103.11,36.6,196.12,Credit Card,Mobile App,23.32,Delivered,True,NaN,Call before delivery,Synthetic_Ecommerce
43901,ORD100182,CUST15967,2023-11-10,74.0,Chicago,South,Electronics,7,80.14,NaN,484.69,UPI,Mobile App,8.26,Delivered,False,2.8,NaN,Synthetic_Ecommerce
38268,ORD100182,CUST15967,2023-11-10,74.0,Chicago,South,Electronics,7,80.14,NaN,484.69,UPI,Mobile App,8.26,Delivered,False,2.8,NaN,Synthetic_Ecommerce
12188,ORD100199,CUST21542,16th Mar 2023,38.0,Phoenix,South,Beauty,4,52.52,36.6,133.19,Debit Card,Mobile App,17.09,Delivered,False,3.1,Deliver after 5 PM,Synthetic_Ecommerce
15547,ORD100199,CUST21542,16th Mar 2023,38.0,Phoenix,South,Beauty,4,52.52,36.6,133.19,Debit Card,Mobile App,17.09,Delivered,False,3.1,Deliver after 5 PM,Synthetic_Ecommerce
48617,ORD100212,CUST19468,2025-11-18,73.0,Dallas,West,Clothing,4,12.69,22.9,39.14,Credit Card,Store,16.49,Processing,True,3.0,Deliver after 5 PM,Synthetic_Ecommerce
11497,ORD100212,CUST19468,2025-11-18,73.0,Dallas,West,Clothing,4,12.69,22.9,39.14,Credit Card,Store,7.48,Processing,True,3.0,Deliver after 5 PM,Synthetic_Ecommerce
21809,ORD100385,CUST11473,05-25-2026,50.0,Los Angeles,Midwest,Books,4,20.02,22.8,61.82,Pay Pal,Website,11.03,Delivered,True,1.9,No special instructions,Synthetic_Ecommerce
29349,ORD100385,CUST11473,05-25-2026,50.0,Los Angeles,Midwest,Books,4,20.02,22.8,61.82,Pay Pal,Website,11.03,Delivered,True,1.9,No special instructions,Synthetic_Ecommerce
19932,ORD100429,CUST18584,01-28-2025,32.0,Dallas,South,Electronics,1,53.92,2.8,52.41,Cash on Delivery,Website,24.85,Delivered,True,3.7,Call before delivery,Synthetic_Ecommerce
877,ORD100429,CUST18584,01-28-2025,32.0,Dallas,South,Electronics,1,53.92,2.8,52.41,Cash on Delivery,Website,24.85,Delivered,True,3.7,Call before delivery,Synthetic_Ecommerce
4734,ORD100430,CUST11012,2023-09-26,64.0,Los Angeles,Midwest,Home,1,73.25,12.1,64.39,Debit Card,Store,13.14,Delivered,True,2.3,NaN,Synthetic_Ecommerce
43700,ORD100430,CUST11012,2023-09-26,64.0,Los Angeles,Midwest,Home,1,73.25,12.1,64.39,Debit Card,Store,13.14,Delivered,True,2.3,NaN,Synthetic_Ecommerce
1205,ORD100476,CUST20163,2025-09-09,56.0,New York,Midwest,Sports,6,20.37,33.9,80.79,UPI,Store,18.47,Delivered,True,3.4,No special instructions,Synthetic_Ecommerce
13263,ORD100476,CUST20163,2025-09-09,56.0,New York,Midwest,Sports,6,20.37,33.9,80.79,UPI,Store,18.47,Delivered,True,3.4,No special instructions,Synthetic_Ecommerce
22956,ORD100543,CUST12095,6th Aug 2026,19.0,Houston,West,Sports,1,$21.52,36.2,13.73,Credit Card,Mobile App,14.21,Cancelled,True,4.9,Gift order,Synthetic_Ecommerce
38981,ORD100543,CUST12095,6th Aug 2026,19.0,Houston,West,Sports,1,21.52,36.2,13.73,Credit Card,Mobile App,14.21,Cancelled,True,4.9,Gift order,Synthetic_Ecommerce

In [46]:
df = df.drop_duplicates(subset="order_id", keep="first")

In [47]:
df['order_id'].duplicated().sum()

np.int64(0)

In [48]:
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [49]:
df['order_date'].head(20)

0     2023-10-16
1     2024-09-08
2     2025-09-19
3     2023-08-25
4     2024-05-24
5     17/07/2025
6     2025-10-08
7     2024-04-13
8     2023-11-25
9     2024-09-26
10    06-02-2024
11    06-01-2024
12    2023-05-31
13    2024-11-15
14    2025-02-08
15    2022-11-16
16    2025.01.27
17    2023-03-04
18    2022-07-27
19    2022-12-07
Name: order_date, dtype: object

In [50]:
def parse_date(x):
    for fmt in ('%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y', '%Y.%m.%d'):
        try:
            return pd.to_datetime(x, format=fmt)
        except (ValueError, TypeError):
            continue
    return pd.to_datetime(x, errors='coerce')  # fallback for "26th Feb 2025" style

df['order_date_clean'] = df['order_date'].apply(parse_date)
df['order_date_clean'].isnull().sum()

np.int64(0)

In [51]:
df['order_date'] = df['order_date_clean']

In [52]:
df['order_date'].head(20)

0    2023-10-16
1    2024-09-08
2    2025-09-19
3    2023-08-25
4    2024-05-24
5    2025-07-17
6    2025-10-08
7    2024-04-13
8    2023-11-25
9    2024-09-26
10   2024-02-06
11   2024-01-06
12   2023-05-31
13   2024-11-15
14   2025-02-08
15   2022-11-16
16   2025-01-27
17   2023-03-04
18   2022-07-27
19   2022-12-07
Name: order_date, dtype: datetime64[ns]

In [53]:
df['unit_price'].head(20)

0      35.93
1     130.16
2      25.29
3     181.38
4      69.46
5      24.86
6       53.1
7      34.81
8      49.59
9      23.68
10     89.14
11     13.15
12     61.05
13     47.24
14     38.95
15    100.01
16     62.67
17     63.89
18    $31.23
19     74.95
Name: unit_price, dtype: object

In [54]:
df['unit_price'] = (df['unit_price'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False))

df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

In [55]:
df['unit_price'].head(20)

0      35.93
1     130.16
2      25.29
3     181.38
4      69.46
5      24.86
6      53.10
7      34.81
8      49.59
9      23.68
10     89.14
11     13.15
12     61.05
13     47.24
14     38.95
15    100.01
16     62.67
17     63.89
18     31.23
19     74.95
Name: unit_price, dtype: float64

In [56]:
df['order_total'] = (df['order_total'].astype(str).str.replace(',', '', regex=False))

df['order_total'] = pd.to_numeric(df['order_total'], errors='coerce')

In [57]:
df[['unit_price', 'order_total']].isnull().sum()

unit_price     0
order_total    0
dtype: int64

In [58]:
df.head()

,order_id,customer_id,order_date,customer_age,city,region,product_category,quantity,unit_price,discount_pct,order_total,payment_method,sales_channel,shipping_weight,order_status,is_returning_customer,customer_rating,order_notes,data_source,order_date_clean
0,ORD130258,CUST10936,2023-10-16,NaN,Chicago,East,Electronics,2,35.93,32.3,48.65,Cash on Delivery,Website,14.70,Delivered,False,3.5,Deliver after 5 PM,Synthetic_Ecommerce,2023-10-16
1,ORD123513,CUST21513,2024-09-08,32.0,Dallas,South,Clothing,5,130.16,4.3,622.82,Cash on Delivery,Mobile App,10.22,Delivered,True,4.1,Leave at door,Synthetic_Ecommerce,2024-09-08
2,ORD127346,CUST11924,2025-09-19,40.0,Chicago,West,Beauty,6,25.29,12.5,132.77,Cash on Delivery,Marketplace,19.84,Delivered,True,4.8,Fragile item,Synthetic_Ecommerce,2025-09-19
3,ORD133311,CUST19434,2023-08-25,37.0,Dallas,Midwest,Sports,1,181.38,8.4,166.14,Credit Card,Marketplace,20.16,Delivered,True,4.1,Deliver after 5 PM,Synthetic_Ecommerce,2023-08-25
4,ORD129034,CUST14567,2024-05-24,59.0,Houston,East,Electronics,6,69.46,30.9,287.98,UPI,Marketplace,18.69,Delivered,True,4.5,No special instructions,Synthetic_Ecommerce,2024-05-24

In [59]:
df['customer_age']

0         NaN
1        32.0
2        40.0
3        37.0
4        59.0
         ...
53659    58.0
53660    48.0
53661    40.0
53662    59.0
53663    57.0
Name: customer_age, Length: 52589, dtype: float64

In [63]:
print("Missing:", df['customer_age'].isnull().sum())

Missing: 3671

In [64]:
# Check age range
print(df['customer_age'].describe())

count    48918.000000
mean        46.741752
std         21.209631
min         -5.000000
25%         32.000000
50%         47.000000
75%         61.000000
max        999.000000
Name: customer_age, dtype: float64

In [65]:
# Convert impossible ages to NaN
df.loc[
    (df['customer_age'] < 18) | (df['customer_age'] > 100),
    'customer_age'
] = np.nan

# Fill missing ages with median
median_age = df['customer_age'].median()
df['customer_age'] = df['customer_age'].fillna(median_age)

In [66]:
# Final check
print("Missing after cleaning:", df['customer_age'].isnull().sum())

Missing after cleaning: 0

In [67]:
df['customer_age'] = df['customer_age'].astype('int64')

In [68]:
df['customer_age'].dtype

dtype('int64')

In [69]:
df['customer_age']

0        47
1        32
2        40
3        37
4        59
         ..
53659    58
53660    48
53661    40
53662    59
53663    57
Name: customer_age, Length: 52589, dtype: int64

In [70]:
df['customer_age'].describe()

count    52589.000000
mean        46.601323
std         16.152840
min         18.000000
25%         33.000000
50%         47.000000
75%         60.000000
max         75.000000
Name: customer_age, dtype: float64

In [72]:
df['order_notes'].isna().sum()

np.int64(5262)

In [73]:
df['order_notes'] = df['order_notes'].fillna('No notes')

In [74]:
df['order_notes'].isna().sum()

np.int64(0)

In [77]:
df.isna().sum()[df.isna().sum() > 0]

discount_pct       3159
payment_method     2116
shipping_weight    1584
customer_rating    4936
dtype: int64

In [80]:
df['customer_rating']

0        3.5
1        4.1
2        4.8
3        4.1
4        4.5
        ...
53659    4.6
53660    2.7
53661    1.3
53662    3.2
53663    4.4
Name: customer_rating, Length: 52589, dtype: float64

In [81]:
df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].median())

In [82]:
df['customer_rating'].isna().sum()

np.int64(0)

In [83]:
df.isna().sum()[df.isna().sum() > 0]

discount_pct       3159
payment_method     2116
shipping_weight    1584
dtype: int64

In [85]:
df['discount_pct']

0        32.3
1         4.3
2        12.5
3         8.4
4        30.9
         ...
53659     5.4
53660    26.6
53661    20.1
53662     NaN
53663     8.8
Name: discount_pct, Length: 52589, dtype: float64

In [86]:
df['discount_pct'] = df['discount_pct'].fillna(df['discount_pct'].median())

In [87]:
df.isna().sum()[df.isna().sum() > 0]

payment_method     2116
shipping_weight    1584
dtype: int64

In [88]:
df['payment_method']

0        Cash on Delivery
1        Cash on Delivery
2        Cash on Delivery
3             Credit Card
4                     UPI
               ...
53659                 UPI
53660                 UPI
53661              PayPal
53662          Debit Card
53663              PayPal
Name: payment_method, Length: 52589, dtype: object

In [89]:
df['payment_method'] = df['payment_method'].fillna('Unknown')

In [90]:
df.isna().sum()[df.isna().sum() > 0]

shipping_weight    1584
dtype: int64

In [91]:
df['shipping_weight']

0        14.70
1        10.22
2        19.84
3        20.16
4        18.69
         ...
53659     5.94
53660    21.81
53661    15.22
53662      NaN
53663    12.99
Name: shipping_weight, Length: 52589, dtype: float64

In [92]:
df['shipping_weight'] = df['shipping_weight'].fillna(df['shipping_weight'].median())

In [93]:
df.isna().sum()[df.isna().sum() > 0]

Series([], dtype: int64)