In [1]:
import pandas as pd

df = pd.DataFrame({
    "Emp_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Ravi","Priya","Amit","Neha","Karan","Sneha","Arjun","Pooja"],
    "Department": ["IT","HR","Sales","IT","Finance","HR","Sales","IT"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Pune","Mumbai","Delhi","Bangalore"],
    "Salary": [75000,55000,60000,85000,90000,58000,62000,78000],
    "Experience": [3,2,4,6,8,1,5,4]
})

df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [2]:
df.index   # attribute

RangeIndex(start=0, stop=8, step=1)

In [3]:
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [5]:
df.index= [x for x in 'abcdefgh']

In [6]:
df

   Emp_ID   Name Department       City  Salary  Experience
a     101   Ravi         IT      Delhi   75000           3
b     102  Priya         HR     Mumbai   55000           2
c     103   Amit      Sales      Delhi   60000           4
d     104   Neha         IT  Bangalore   85000           6
e     105  Karan    Finance       Pune   90000           8
f     106  Sneha         HR     Mumbai   58000           1
g     107  Arjun      Sales      Delhi   62000           5
h     108  Pooja         IT  Bangalore   78000           4

In [7]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')

In [9]:
df['Emp_ID']

a    101
b    102
c    103
d    104
e    105
f    106
g    107
h    108
Name: Emp_ID, dtype: int64

In [10]:
df.index=df['Emp_ID']
# The Emp_ID column remains in the DataFrame.

In [11]:
df

        Emp_ID   Name Department       City  Salary  Experience
Emp_ID
101        101   Ravi         IT      Delhi   75000           3
102        102  Priya         HR     Mumbai   55000           2
103        103   Amit      Sales      Delhi   60000           4
104        104   Neha         IT  Bangalore   85000           6
105        105  Karan    Finance       Pune   90000           8
106        106  Sneha         HR     Mumbai   58000           1
107        107  Arjun      Sales      Delhi   62000           5
108        108  Pooja         IT  Bangalore   78000           4

In [15]:
df.drop('Emp_ID',axis=1,inplace=True)

In [16]:
df

         Name Department       City  Salary  Experience
Emp_ID
101      Ravi         IT      Delhi   75000           3
102     Priya         HR     Mumbai   55000           2
103      Amit      Sales      Delhi   60000           4
104      Neha         IT  Bangalore   85000           6
105     Karan    Finance       Pune   90000           8
106     Sneha         HR     Mumbai   58000           1
107     Arjun      Sales      Delhi   62000           5
108     Pooja         IT  Bangalore   78000           4

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Emp_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Ravi","Priya","Amit","Neha","Karan","Sneha","Arjun","Pooja"],
    "Department": ["IT","HR","Sales","IT","Finance","HR","Sales","IT"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Pune","Mumbai","Delhi","Bangalore"],
    "Salary": [75000,55000,60000,85000,90000,58000,62000,78000],
    "Experience": [3,2,4,6,8,1,5,4]
})

df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [13]:
# this is the second approach to make changes in index of DataFrame
df.set_index('Emp_ID')

         Name Department       City  Salary  Experience
Emp_ID
101      Ravi         IT      Delhi   75000           3
102     Priya         HR     Mumbai   55000           2
103      Amit      Sales      Delhi   60000           4
104      Neha         IT  Bangalore   85000           6
105     Karan    Finance       Pune   90000           8
106     Sneha         HR     Mumbai   58000           1
107     Arjun      Sales      Delhi   62000           5
108     Pooja         IT  Bangalore   78000           4

In [14]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [15]:
df.set_index('Emp_ID',inplace=True)

In [16]:
df

         Name Department       City  Salary  Experience
Emp_ID
101      Ravi         IT      Delhi   75000           3
102     Priya         HR     Mumbai   55000           2
103      Amit      Sales      Delhi   60000           4
104      Neha         IT  Bangalore   85000           6
105     Karan    Finance       Pune   90000           8
106     Sneha         HR     Mumbai   58000           1
107     Arjun      Sales      Delhi   62000           5
108     Pooja         IT  Bangalore   78000           4

#### Why is set_index() preferred?
    Cleaner
    No duplicate information:
        Emp_ID
        101 Ravi
        102 Priya
    
    instead of 
        Emp_ID
        101  101 Ravi
        102  102 Priya
        
    More options
    df.set_index('Emp_ID', drop=False)  It keeps the column.
    
    df.set_index('Emp_ID', inplace=True) modifies the DataFrame directly.
    
    df.set_index(['Department', 'Emp_ID']) creates a MultiIndex.

In [17]:
df

         Name Department       City  Salary  Experience
Emp_ID
101      Ravi         IT      Delhi   75000           3
102     Priya         HR     Mumbai   55000           2
103      Amit      Sales      Delhi   60000           4
104      Neha         IT  Bangalore   85000           6
105     Karan    Finance       Pune   90000           8
106     Sneha         HR     Mumbai   58000           1
107     Arjun      Sales      Delhi   62000           5
108     Pooja         IT  Bangalore   78000           4

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Emp_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Ravi","Priya","Amit","Neha","Karan","Sneha","Arjun","Pooja"],
    "Department": ["IT","HR","Sales","IT","Finance","HR","Sales","IT"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Pune","Mumbai","Delhi","Bangalore"],
    "Salary": [75000,55000,60000,85000,90000,58000,62000,78000],
    "Experience": [3,2,4,6,8,1,5,4]
})

df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [19]:
df.set_index('Emp_ID', drop=False)

        Emp_ID   Name Department       City  Salary  Experience
Emp_ID
101        101   Ravi         IT      Delhi   75000           3
102        102  Priya         HR     Mumbai   55000           2
103        103   Amit      Sales      Delhi   60000           4
104        104   Neha         IT  Bangalore   85000           6
105        105  Karan    Finance       Pune   90000           8
106        106  Sneha         HR     Mumbai   58000           1
107        107  Arjun      Sales      Delhi   62000           5
108        108  Pooja         IT  Bangalore   78000           4

In [25]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [20]:
df.set_index('Emp_ID', drop=False, inplace=True)

In [21]:
df

        Emp_ID   Name Department       City  Salary  Experience
Emp_ID
101        101   Ravi         IT      Delhi   75000           3
102        102  Priya         HR     Mumbai   55000           2
103        103   Amit      Sales      Delhi   60000           4
104        104   Neha         IT  Bangalore   85000           6
105        105  Karan    Finance       Pune   90000           8
106        106  Sneha         HR     Mumbai   58000           1
107        107  Arjun      Sales      Delhi   62000           5
108        108  Pooja         IT  Bangalore   78000           4

In [22]:
import pandas as pd

df = pd.DataFrame({
    "Emp_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Ravi","Priya","Amit","Neha","Karan","Sneha","Arjun","Pooja"],
    "Department": ["IT","HR","Sales","IT","Finance","HR","Sales","IT"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Pune","Mumbai","Delhi","Bangalore"],
    "Salary": [75000,55000,60000,85000,90000,58000,62000,78000],
    "Experience": [3,2,4,6,8,1,5,4]
})

df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [23]:
df.set_index(['Department','City'])

                      Emp_ID   Name  Salary  Experience
Department City
IT         Delhi         101   Ravi   75000           3
HR         Mumbai        102  Priya   55000           2
Sales      Delhi         103   Amit   60000           4
IT         Bangalore     104   Neha   85000           6
Finance    Pune          105  Karan   90000           8
HR         Mumbai        106  Sneha   58000           1
Sales      Delhi         107  Arjun   62000           5
IT         Bangalore     108  Pooja   78000           4

In [24]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [25]:
df.set_index(['Department','City'],inplace=True)

In [26]:
df

                      Emp_ID   Name  Salary  Experience
Department City
IT         Delhi         101   Ravi   75000           3
HR         Mumbai        102  Priya   55000           2
Sales      Delhi         103   Amit   60000           4
IT         Bangalore     104   Neha   85000           6
Finance    Pune          105  Karan   90000           8
HR         Mumbai        106  Sneha   58000           1
Sales      Delhi         107  Arjun   62000           5
IT         Bangalore     108  Pooja   78000           4

In [27]:
df['Emp_ID']

Department  City
IT          Delhi        101
HR          Mumbai       102
Sales       Delhi        103
IT          Bangalore    104
Finance     Pune         105
HR          Mumbai       106
Sales       Delhi        107
IT          Bangalore    108
Name: Emp_ID, dtype: int64

In [28]:
df['Emp_ID']['IT']

City
Delhi        101
Bangalore    104
Bangalore    108
Name: Emp_ID, dtype: int64

In [29]:
df

                      Emp_ID   Name  Salary  Experience
Department City
IT         Delhi         101   Ravi   75000           3
HR         Mumbai        102  Priya   55000           2
Sales      Delhi         103   Amit   60000           4
IT         Bangalore     104   Neha   85000           6
Finance    Pune          105  Karan   90000           8
HR         Mumbai        106  Sneha   58000           1
Sales      Delhi         107  Arjun   62000           5
IT         Bangalore     108  Pooja   78000           4

In [30]:
df.loc[ 'HR']

        Emp_ID   Name  Salary  Experience
City
Mumbai     102  Priya   55000           2
Mumbai     106  Sneha   58000           1

In [31]:
df.loc['IT']

           Emp_ID   Name  Salary  Experience
City
Delhi         101   Ravi   75000           3
Bangalore     104   Neha   85000           6
Bangalore     108  Pooja   78000           4

In [40]:
df.loc['Delhi']

KeyError: 'Delhi'

The key point is:
.loc[] searches the outermost index level first.
Since Department is the outer index and City is the inner index, df.loc['IT'] works but df.loc['Delhi'] raises a KeyError.

In [32]:
df.loc['IT']

           Emp_ID   Name  Salary  Experience
City
Delhi         101   Ravi   75000           3
Bangalore     104   Neha   85000           6
Bangalore     108  Pooja   78000           4

In [42]:
df.loc[ ['IT','Delhi']]

KeyError: "['Delhi'] not in index"

In [43]:
df.loc['IT']

           Emp_ID   Name  Salary  Experience
City
Delhi         101   Ravi   75000           3
Bangalore     104   Neha   85000           6
Bangalore     108  Pooja   78000           4

In [44]:
df.loc['IT'].loc['Delhi']

Emp_ID          101
Name           Ravi
Salary        75000
Experience        3
Name: Delhi, dtype: object

In [45]:
df.loc['IT']

           Emp_ID   Name  Salary  Experience
City
Delhi         101   Ravi   75000           3
Bangalore     104   Neha   85000           6
Bangalore     108  Pooja   78000           4

In [33]:
df.loc['IT']['Salary'].reset_index()

        City  Salary
0      Delhi   75000
1  Bangalore   85000
2  Bangalore   78000

In [47]:
df.loc['IT']['Delhi']

KeyError: 'Delhi'

### How to access all rows with City = 'Delhi'?
#### Method 1: Specify both levels

In [40]:
df.loc[(slice(None), 'Delhi'), :].reset_index()

# Here:
# slice(None) means "all departments".
# 'Delhi' means City = Delhi.

  Department   City  Emp_ID   Name  Salary  Experience
0         IT  Delhi     101   Ravi   75000           3
1      Sales  Delhi     103   Amit   60000           4
2      Sales  Delhi     107  Arjun   62000           5

#### Method 2: Swap Index Levels

In [42]:
df2 = df.swaplevel()
df2.loc['Delhi'].reset_index()

  Department  Emp_ID   Name  Salary  Experience
0         IT     101   Ravi   75000           3
1      Sales     103   Amit   60000           4
2      Sales     107  Arjun   62000           5

In [36]:
df

                      Emp_ID   Name  Salary  Experience
Department City
IT         Delhi         101   Ravi   75000           3
HR         Mumbai        102  Priya   55000           2
Sales      Delhi         103   Amit   60000           4
IT         Bangalore     104   Neha   85000           6
Finance    Pune          105  Karan   90000           8
HR         Mumbai        106  Sneha   58000           1
Sales      Delhi         107  Arjun   62000           5
IT         Bangalore     108  Pooja   78000           4

In [37]:
df.index

MultiIndex([(     'IT',     'Delhi'),
            (     'HR',    'Mumbai'),
            (  'Sales',     'Delhi'),
            (     'IT', 'Bangalore'),
            ('Finance',      'Pune'),
            (     'HR',    'Mumbai'),
            (  'Sales',     'Delhi'),
            (     'IT', 'Bangalore')],
           names=['Department', 'City'])

In [38]:
df

                      Emp_ID   Name  Salary  Experience
Department City
IT         Delhi         101   Ravi   75000           3
HR         Mumbai        102  Priya   55000           2
Sales      Delhi         103   Amit   60000           4
IT         Bangalore     104   Neha   85000           6
Finance    Pune          105  Karan   90000           8
HR         Mumbai        106  Sneha   58000           1
Sales      Delhi         107  Arjun   62000           5
IT         Bangalore     108  Pooja   78000           4

In [57]:
import pandas as pd

df = pd.DataFrame({
    "Emp_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Ravi","Priya","Amit","Neha","Karan","Sneha","Arjun","Pooja"],
    "Department": ["IT","HR","Sales","IT","Finance","HR","Sales","IT"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Pune","Mumbai","Delhi","Bangalore"],
    "Salary": [75000,55000,60000,85000,90000,58000,62000,78000],
    "Experience": [3,2,4,6,8,1,5,4]
})

df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [2]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [3]:
df.iloc[[0,2,4]]

   Emp_ID   Name Department   City  Salary  Experience
0     101   Ravi         IT  Delhi   75000           3
2     103   Amit      Sales  Delhi   60000           4
4     105  Karan    Finance   Pune   90000           8

In [4]:
df.reindex(index=[0,2,4])

   Emp_ID   Name Department   City  Salary  Experience
0     101   Ravi         IT  Delhi   75000           3
2     103   Amit      Sales  Delhi   60000           4
4     105  Karan    Finance   Pune   90000           8

In [61]:
df.iloc[[0,2,4,6,8,10]]

IndexError: positional indexers are out-of-bounds

In [62]:
df.reindex(index=[0,2,4,6,8,10])

    Emp_ID   Name Department   City   Salary  Experience
0    101.0   Ravi         IT  Delhi  75000.0         3.0
2    103.0   Amit      Sales  Delhi  60000.0         4.0
4    105.0  Karan    Finance   Pune  90000.0         8.0
6    107.0  Arjun      Sales  Delhi  62000.0         5.0
8      NaN    NaN        NaN    NaN      NaN         NaN
10     NaN    NaN        NaN    NaN      NaN         NaN

#### NOTE :-
    1. When we use iloc[] we can only access those index which are there in df.
        If we try to access a range which is not there in df it will give us an error.
    2. Whereas when we use reindex and try to access those index whether they are there in df or not
        it will not show an error to us instead of that it will give NaN .

In [63]:
d={'a':10,'b':20}

In [64]:
d

{'a': 10, 'b': 20}

In [65]:
d['a']

10

In [66]:
d['b']

20

In [67]:
d['c']

KeyError: 'c'

In [68]:
d.get('a')

10

In [69]:
d.get('b')

20

In [70]:
d.get('c')

In [71]:
d.get('c',0)

0

In [72]:
key=input("Enter key to access=")
print(d[key])

Enter key to access= a

10

In [73]:
key=input("Enter key to access=")
print(d[key])

Enter key to access= e

KeyError: 'e'

In [75]:
key=input("Enter key to access=")
print(d.get(key))

Enter key to access= a

10

In [76]:
key=input("Enter key to access=")
print(d.get(key))

Enter key to access= f

None

In [77]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [5]:
key=int(input("Enter index to access="))
df.iloc[key]

Enter index to access= 3

Emp_ID              104
Name               Neha
Department           IT
City          Bangalore
Salary            85000
Experience            6
Name: 3, dtype: object

In [80]:
key=int(input("Enter inde to access="))
df.iloc[key]

Enter inde to access= 10

IndexError: single positional indexer is out-of-bounds

In [82]:
key=int(input("Enter inde to access="))
df.reindex(index=[key])

Enter inde to access= 10

    Emp_ID Name Department City  Salary  Experience
10     NaN  NaN        NaN  NaN     NaN         NaN

In [83]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [85]:
df['Name']

0     Ravi
1    Priya
2     Amit
3     Neha
4    Karan
5    Sneha
6    Arjun
7    Pooja
Name: Name, dtype: object

In [86]:
df[['Name','City']]

    Name       City
0   Ravi      Delhi
1  Priya     Mumbai
2   Amit      Delhi
3   Neha  Bangalore
4  Karan       Pune
5  Sneha     Mumbai
6  Arjun      Delhi
7  Pooja  Bangalore

In [87]:
df[['Name','City','Score']]

KeyError: "['Score'] not in index"

In [88]:
df.reindex(columns=['Name','City','Score'] )

    Name       City  Score
0   Ravi      Delhi    NaN
1  Priya     Mumbai    NaN
2   Amit      Delhi    NaN
3   Neha  Bangalore    NaN
4  Karan       Pune    NaN
5  Sneha     Mumbai    NaN
6  Arjun      Delhi    NaN
7  Pooja  Bangalore    NaN

In [89]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4

In [90]:
len(df)

8

In [93]:
df.loc[ 8 ]= [109,'Vishu','IT','Bangalore',18000,2]

In [94]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4
8     109  Vishu         IT  Bangalore   18000           2

In [97]:
list(df.index) + [9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [104]:
df.reindex( index =[0,1,2,3,4,5,6,7,8,9,10] )

    Emp_ID   Name Department       City   Salary  Experience
0    101.0   Ravi         IT      Delhi  75000.0         3.0
1    102.0  Priya         HR     Mumbai  55000.0         2.0
2    103.0   Amit      Sales      Delhi  60000.0         4.0
3    104.0   Neha         IT  Bangalore  85000.0         6.0
4    105.0  Karan    Finance       Pune  90000.0         8.0
5    106.0  Sneha         HR     Mumbai  58000.0         1.0
6    107.0  Arjun      Sales      Delhi  62000.0         5.0
7    108.0  Pooja         IT  Bangalore  78000.0         4.0
8    109.0  Vishu         IT  Bangalore  18000.0         2.0
9      NaN    NaN        NaN        NaN      NaN         NaN
10     NaN    NaN        NaN        NaN      NaN         NaN

In [100]:
df.reindex( index=list(df.index) + [9,10,11,12,13] )

    Emp_ID   Name Department       City   Salary  Experience
0    101.0   Ravi         IT      Delhi  75000.0         3.0
1    102.0  Priya         HR     Mumbai  55000.0         2.0
2    103.0   Amit      Sales      Delhi  60000.0         4.0
3    104.0   Neha         IT  Bangalore  85000.0         6.0
4    105.0  Karan    Finance       Pune  90000.0         8.0
5    106.0  Sneha         HR     Mumbai  58000.0         1.0
6    107.0  Arjun      Sales      Delhi  62000.0         5.0
7    108.0  Pooja         IT  Bangalore  78000.0         4.0
8    109.0  Vishu         IT  Bangalore  18000.0         2.0
9      NaN    NaN        NaN        NaN      NaN         NaN
10     NaN    NaN        NaN        NaN      NaN         NaN
11     NaN    NaN        NaN        NaN      NaN         NaN
12     NaN    NaN        NaN        NaN      NaN         NaN
13     NaN    NaN        NaN        NaN      NaN         NaN

In [105]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4
8     109  Vishu         IT  Bangalore   18000           2

In [107]:
list(range(1,21,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [108]:
len(df.index)

9

In [109]:
range(len(df.index),len(df.index)+20,1)

range(9, 29)

In [110]:
list(range(len(df.index),len(df.index)+20,1))

[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

In [111]:
df.reindex( index=list(df.index) + list(range(len(df.index),len(df.index)+20,1)) )

    Emp_ID   Name Department       City   Salary  Experience
0    101.0   Ravi         IT      Delhi  75000.0         3.0
1    102.0  Priya         HR     Mumbai  55000.0         2.0
2    103.0   Amit      Sales      Delhi  60000.0         4.0
3    104.0   Neha         IT  Bangalore  85000.0         6.0
4    105.0  Karan    Finance       Pune  90000.0         8.0
5    106.0  Sneha         HR     Mumbai  58000.0         1.0
6    107.0  Arjun      Sales      Delhi  62000.0         5.0
7    108.0  Pooja         IT  Bangalore  78000.0         4.0
8    109.0  Vishu         IT  Bangalore  18000.0         2.0
9      NaN    NaN        NaN        NaN      NaN         NaN
10     NaN    NaN        NaN        NaN      NaN         NaN
11     NaN    NaN        NaN        NaN      NaN         NaN
12     NaN    NaN        NaN        NaN      NaN         NaN
13     NaN    NaN        NaN        NaN      NaN         NaN
14     NaN    NaN        NaN        NaN      NaN         NaN
15     NaN    NaN        NaN        NaN      NaN         NaN
16     NaN    NaN        NaN        NaN      NaN         NaN
17     NaN    NaN        NaN        NaN      NaN         NaN
18     NaN    NaN        NaN        NaN      NaN         NaN
19     NaN    NaN        NaN        NaN      NaN         NaN
20     NaN    NaN        NaN        NaN      NaN         NaN
21     NaN    NaN        NaN        NaN      NaN         NaN
22     NaN    NaN        NaN        NaN      NaN         NaN
23     NaN    NaN        NaN        NaN      NaN         NaN
24     NaN    NaN        NaN        NaN      NaN         NaN
25     NaN    NaN        NaN        NaN      NaN         NaN
26     NaN    NaN        NaN        NaN      NaN         NaN
27     NaN    NaN        NaN        NaN      NaN         NaN
28     NaN    NaN        NaN        NaN      NaN         NaN

In [112]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4
8     109  Vishu         IT  Bangalore   18000           2

In [113]:
df.reindex( columns =['Name'])

    Name
0   Ravi
1  Priya
2   Amit
3   Neha
4  Karan
5  Sneha
6  Arjun
7  Pooja
8  Vishu

In [114]:
df.reindex( columns =['Emp_ID','Name'])

   Emp_ID   Name
0     101   Ravi
1     102  Priya
2     103   Amit
3     104   Neha
4     105  Karan
5     106  Sneha
6     107  Arjun
7     108  Pooja
8     109  Vishu

In [115]:
df.reindex( columns =['Emp_ID','Name','Marks'])

   Emp_ID   Name  Marks
0     101   Ravi    NaN
1     102  Priya    NaN
2     103   Amit    NaN
3     104   Neha    NaN
4     105  Karan    NaN
5     106  Sneha    NaN
6     107  Arjun    NaN
7     108  Pooja    NaN
8     109  Vishu    NaN

In [116]:
df.reindex( labels =['Emp_ID','Name','Marks'])

        Emp_ID Name Department City  Salary  Experience
Emp_ID     NaN  NaN        NaN  NaN     NaN         NaN
Name       NaN  NaN        NaN  NaN     NaN         NaN
Marks      NaN  NaN        NaN  NaN     NaN         NaN

In [118]:
df.reindex( labels =['Emp_ID','Name','Marks'],axis=0)

        Emp_ID Name Department City  Salary  Experience
Emp_ID     NaN  NaN        NaN  NaN     NaN         NaN
Name       NaN  NaN        NaN  NaN     NaN         NaN
Marks      NaN  NaN        NaN  NaN     NaN         NaN

In [119]:
df.reindex( labels =['Emp_ID','Name','Marks'],axis=1)

   Emp_ID   Name  Marks
0     101   Ravi    NaN
1     102  Priya    NaN
2     103   Amit    NaN
3     104   Neha    NaN
4     105  Karan    NaN
5     106  Sneha    NaN
6     107  Arjun    NaN
7     108  Pooja    NaN
8     109  Vishu    NaN

In [120]:
df.reindex( ['Emp_ID','Name','Marks'],axis=1)

   Emp_ID   Name  Marks
0     101   Ravi    NaN
1     102  Priya    NaN
2     103   Amit    NaN
3     104   Neha    NaN
4     105  Karan    NaN
5     106  Sneha    NaN
6     107  Arjun    NaN
7     108  Pooja    NaN
8     109  Vishu    NaN

In [121]:
df.reindex( ['Emp_ID','Name','Marks'])

        Emp_ID Name Department City  Salary  Experience
Emp_ID     NaN  NaN        NaN  NaN     NaN         NaN
Name       NaN  NaN        NaN  NaN     NaN         NaN
Marks      NaN  NaN        NaN  NaN     NaN         NaN

In [122]:
df.reindex( columns=['Emp_ID','Name','Marks'])

   Emp_ID   Name  Marks
0     101   Ravi    NaN
1     102  Priya    NaN
2     103   Amit    NaN
3     104   Neha    NaN
4     105  Karan    NaN
5     106  Sneha    NaN
6     107  Arjun    NaN
7     108  Pooja    NaN
8     109  Vishu    NaN

In [123]:
df.reindex( columns=['Emp_ID','Name','Marks'],fill_value=0)

   Emp_ID   Name  Marks
0     101   Ravi      0
1     102  Priya      0
2     103   Amit      0
3     104   Neha      0
4     105  Karan      0
5     106  Sneha      0
6     107  Arjun      0
7     108  Pooja      0
8     109  Vishu      0

In [124]:
df

   Emp_ID   Name Department       City  Salary  Experience
0     101   Ravi         IT      Delhi   75000           3
1     102  Priya         HR     Mumbai   55000           2
2     103   Amit      Sales      Delhi   60000           4
3     104   Neha         IT  Bangalore   85000           6
4     105  Karan    Finance       Pune   90000           8
5     106  Sneha         HR     Mumbai   58000           1
6     107  Arjun      Sales      Delhi   62000           5
7     108  Pooja         IT  Bangalore   78000           4
8     109  Vishu         IT  Bangalore   18000           2

In [125]:
df.reindex( index=[2,6,8,10])

    Emp_ID   Name Department       City   Salary  Experience
2    103.0   Amit      Sales      Delhi  60000.0         4.0
6    107.0  Arjun      Sales      Delhi  62000.0         5.0
8    109.0  Vishu         IT  Bangalore  18000.0         2.0
10     NaN    NaN        NaN        NaN      NaN         NaN

In [126]:
df.reindex( index=[2,6,8,10], columns = ['Emp_ID','Name','Score'])

    Emp_ID   Name  Score
2    103.0   Amit    NaN
6    107.0  Arjun    NaN
8    109.0  Vishu    NaN
10     NaN    NaN    NaN

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name":["Ravi","Priya","Amit","Neha","Karan"],
    "Department":["IT","HR","Sales","IT","Finance"],
    "Salary":[75000,55000,60000,85000,90000]
},
index=[103,101,105,102,104])

print(df)

      Name Department  Salary
103   Ravi         IT   75000
101  Priya         HR   55000
105   Amit      Sales   60000
102   Neha         IT   85000
104  Karan    Finance   90000

In [3]:
df

      Name Department  Salary
103   Ravi         IT   75000
101  Priya         HR   55000
105   Amit      Sales   60000
102   Neha         IT   85000
104  Karan    Finance   90000

In [4]:
df.sort_index()

      Name Department  Salary
101  Priya         HR   55000
102   Neha         IT   85000
103   Ravi         IT   75000
104  Karan    Finance   90000
105   Amit      Sales   60000

In [5]:
df.sort_index(ascending=False)

      Name Department  Salary
105   Amit      Sales   60000
104  Karan    Finance   90000
103   Ravi         IT   75000
102   Neha         IT   85000
101  Priya         HR   55000

In [6]:
df

      Name Department  Salary
103   Ravi         IT   75000
101  Priya         HR   55000
105   Amit      Sales   60000
102   Neha         IT   85000
104  Karan    Finance   90000

In [7]:
df.loc[105]

Name           Amit
Department    Sales
Salary        60000
Name: 105, dtype: object

In [8]:
df.at[105,'Name']

'Amit'

In [9]:
df.at[105,"Department"]

'Sales'

In [10]:
df

      Name Department  Salary
103   Ravi         IT   75000
101  Priya         HR   55000
105   Amit      Sales   60000
102   Neha         IT   85000
104  Karan    Finance   90000

In [11]:
df.loc[105]

Name           Amit
Department    Sales
Salary        60000
Name: 105, dtype: object

In [15]:
df.at[105]   # It will give us ann error because at[] requires one column name as a argument
             # It gives us a single output or we can say a single cell of data

TypeError: DataFrame._get_value() missing 1 required positional argument: 'col'

In [16]:
df.loc[:,'Department'] # All rows of the Department

103         IT
101         HR
105      Sales
102         IT
104    Finance
Name: Department, dtype: object

In [17]:
df.loc[105,'Name']

'Amit'

In [145]:
df.loc[[103,105],['Name','Department'] ]

     Name Department
103  Ravi         IT
105  Amit      Sales

In [148]:
df.loc[105,'Name']

'Amit'

In [149]:
df.at[105,'Name']

'Amit'

#### NOTE:- By the help of loc[] we can access multiple index or multiple columns
####        But with the use of at[] we can only access one index and one col at a time

In [150]:
df.loc[[103,105],['Name','Department'] ]

     Name Department
103  Ravi         IT
105  Amit      Sales

In [151]:
df.at[[103,105],['Name','Department'] ]

TypeError: unhashable type: 'list'

In [152]:
df

      Name Department  Salary
103   Ravi         IT   75000
101  Priya         HR   55000
105   Amit      Sales   60000
102   Neha         IT   85000
104  Karan    Finance   90000

In [153]:
df.iloc[2,0]

'Amit'

In [154]:
df.iat[2,0]

'Amit'