# WHAT IS PANDAS?

- Built on NumPy
- Works with tabular data (like Excel but 100x more powerful)
- Used for cleaning, exploring, transforming, and analyzing data

In [1]:
# Install if you don't have it (run only once)
# !pip install pandas numpy openpyxl xlrd

import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("Ready to become a Pandas Pro! 🚀")

Pandas version: 2.2.3
Ready to become a Pandas Pro! 🚀

In [4]:
# Creating a Series using random() module and randint() module by generating random numbers for labelled indexes.
yoyo = pd.Series(np.random.randint(50,100,size=5),index=["Aditya","Sakshi","Aryan","Rahul","Ankit"])
print(yoyo)

Aditya    60
Sakshi    76
Aryan     86
Rahul     63
Ankit     77
dtype: int32

# Pandas Core Data Structures

### 1. Series (1-dimensional labeled array)

Pandas Series is a one-dimensional labeled array that can hold any data type (like int, float, string, etc.).

In [9]:
# Example 1: Simple Series
scores = pd.Series([85, 90, 78, 92, 88])
print(scores)

# By default index taken by series is 0,1,2,3,... etc
# But we can give our own index too.
print()
# Example 2: Series with custom index (very important!)
students = pd.Series([85, 90, 78, 92, 88], 
                     index=["Ali", "Riya", "Rahul", "Priya", "Aman"])
print(students)

0    85
1    90
2    78
3    92
4    88
dtype: int64

Ali      85
Riya     90
Rahul    78
Priya    92
Aman     88
dtype: int64

In [3]:
# Series using Dictionary
dict_dt = {'a':40,'b':30}
d = pd.Series(dict_dt)
print(d)

print()
std_mark = pd.Series({'Aditya':90,'Ankit':95})
print(std_mark)

a    40
b    30
dtype: int64

Aditya    90
Ankit     95
dtype: int64

In [7]:
# while making series from the Dictionary if we give an index to it .
# Then the making as series will be depend on the index
std_mark1 = pd.Series({'Aditya':90,'Sakshi':99,'Ankit':95},index=["Aditya","Aryan","Sakshi"])
print(std_mark1)

# Since here in Index we have given 'Aryan' but we do not have any value of 'Aryan' in dict So it will give 'NaN'

Aditya    90.0
Aryan      NaN
Sakshi    99.0
dtype: float64

In [14]:
# Accessing Series elements
print(students)
print()
# print(students["Ali"])  # Access by index label. Output: 85
# print(students[0])    # Access by integer position in newer versions of pandas, this is not recommended as it can lead to ambiguity. Use iloc[] instead for position-based access.
# print(students.iloc[0])  # Access by integer position using iloc[]. Output: 85
# print(students[1:4])   # Access a range of elements it will print from index 1 to 3 (4 is exclusive)
# print(students["Ali":"Priya":1])  # Access a range of elements by index label
# print(students[["Ali", "Priya"]])  # Access multiple elements by index labels
print(students[students > 85])  # Access elements based on a condition

Ali      85
Riya     90
Rahul    78
Priya    92
Aman     88
dtype: int64

Riya     90
Priya    92
Aman     88
dtype: int64

In [10]:
# iloc[] is a safer method to get values by position, especially when the index labels are not unique or when you want to avoid ambiguity. 
# It is because it always refers to the integer position of the elements, regardless of the index labels. 
# This makes it more reliable when accessing elements by position, as it won't be affected by changes in the index 
# or duplicate labels

# In contrast, using the standard indexing (e.g., students[0]) can lead to ambiguity if the index labels are not unique or if they are integers that could be mistaken for positions. For example, if you have an index label that is an integer (like 0), it can be unclear whether students[0] refers to the first element by position or the element with the index label 0. This is why using iloc[] is recommended for position-based access, as it eliminates this ambiguity and ensures you are always accessing elements based on their position in the Series.
# If you want to access multiple elements by position, you can use iloc[] with a list of positions. For example, students.iloc[[0, 2]] will give you the first and third elements of the Series, regardless of their index labels.
# print(students.iloc[2])               # access by position . Here iloc[] is a safer method to get values
print(students.iloc[0:3])            # access a range of positions (0 to 2)
print("Mean:", students.mean())           # average
print("Max:", students.max(), "Min:", students.min())
# print(students.describe())       # summary statistics

Ali      85
Riya     90
Rahul    78
dtype: int64
Mean: 86.6
Max: 92 Min: 78

In [7]:
sales = pd.Series([45000, 52000, 48000, 61000, 59000, 67000],
                  index=["Jan", "Feb", "Mar", "Apr", "May", "Jun"])
print(sales)
print()
print("Total sales 6 months:", sales.sum())
print("Average monthly sales:", sales.mean())

Jan    45000
Feb    52000
Mar    48000
Apr    61000
May    59000
Jun    67000
dtype: int64

Total sales 6 months: 332000
Average monthly sales: 55333.333333333336

In [16]:
s = pd.Series(['Apple','banana',None,'APPLE','Banana',np.nan, 'orange','ORANGE','grapes'])
print(s)

0     Apple
1    banana
2      None
3     APPLE
4    Banana
5       NaN
6    orange
7    ORANGE
8    grapes
dtype: object

In [5]:
# ✅ 1. Count total number of missing values
print(s.isna().sum())

2

In [15]:
# ✅ 2. Replace all missing values with "unknown"
# s.fillna('unknown',inplace=True)   # Here 'inplace' = True will permanentaly change the value in the series
print(s)

0      Apple
1     banana
2    unknown
3      APPLE
4     Banana
5    unknown
6     orange
7     ORANGE
8     grapes
dtype: object

In [19]:
# ✅ 3. Drop all missing values
s.dropna() # it has changed the series on temporary basis. If we want to change the series permanentaly then we have to use
           # inplace = True
s # Here since we are printing the series 's' it will show the original series to us rather than the changed one

# s.dropna(inplace=True) # it will now change the series permanentaly

0     Apple
1    banana
2      None
3     APPLE
4    Banana
5       NaN
6    orange
7    ORANGE
8    grapes
dtype: object

In [21]:
# ✅ 4. Standardize the text - (remove spaces + lowercase)
s_clean = s.str.strip().str.lower()
s_clean

0     apple
1    banana
2      None
3     apple
4    banana
5       NaN
6    orange
7    orange
8    grapes
dtype: object

In [23]:
# ✅ 5. Replace variations
s_clean = s_clean.replace({
    'apple': 'apple',
    'banana': 'banana'
})
s_clean  # (after lowercase, this is already handled automatically)

0     apple
1    banana
2      None
3     apple
4    banana
5       NaN
6    orange
7    orange
8    grapes
dtype: object

In [ ]:
# ✅ 6. Replace empty strings with NaN
s_clean = s_clean.replace('', np.nan)

In [ ]:
# ✅ 7. Forward fill (ffill)
s_ffill = s_clean.fillna(method='ffill')

In [ ]:
# ✅ 8. Remove duplicates after cleaning
s_final = s_clean.drop_duplicates()

In [ ]:
# 🔥 Final Clean Pipeline (Best Practice)
s_final = (
    s.str.strip()
     .str.lower()
     .replace('', np.nan)
     .dropna()
     .drop_duplicates()
)

# 💡 Interview Tip

# Say this: “First I standardize text, then handle missing values, then remove duplicates.”

In [3]:
dt_practice = pd.Series([12, np.nan, 25, 18, np.nan, 30, 45, 18, 25, np.nan])
dt_practice

0    12.0
1     NaN
2    25.0
3    18.0
4     NaN
5    30.0
6    45.0
7    18.0
8    25.0
9     NaN
dtype: float64

In [11]:
count = (dt_practice == 18).sum()
print(count)

2

In [21]:
count_missing_index = dt_practice[dt_practice.isna()].index.tolist()
print(count_missing_index)

[1, 4, 9]

In [19]:
# sort the series in descending order
dt_practice.sort_values(ascending=False)

6    45.0
5    30.0
2    25.0
8    25.0
3    18.0
7    18.0
0    12.0
1     NaN
4     NaN
9     NaN
dtype: float64

In [18]:
# find the data which are greater than the mean of series
dt_practice[dt_practice > (dt_practice.mean())]

2    25.0
5    30.0
6    45.0
8    25.0
dtype: float64

In [17]:
# fill the null values with mean of series
dt_practice.fillna(dt_practice.mean())

0    12.000000
1    24.714286
2    25.000000
3    18.000000
4    24.714286
5    30.000000
6    45.000000
7    18.000000
8    25.000000
9    24.714286
dtype: float64

In [24]:
# 5. Maximum difference between any two values
print(dt_practice.max() - dt_practice.min())

33.0

In [27]:
# Fill missing values
mean = dt_practice.mean()
median = dt_practice.median()

data_filled = dt_practice.copy()
for i in dt_practice[dt_practice.isna()].index:     # dt_practice[dt_practice.isna()].index = this will gonna create the list of those indexes where null values are.
    if i % 2 == 0:
        data_filled[i] = mean
    else:
        data_filled[i] = median

data_filled

0    12.000000
1    25.000000
2    25.000000
3    18.000000
4    24.714286
5    30.000000
6    45.000000
7    18.000000
8    25.000000
9    25.000000
dtype: float64

In [31]:
# List of duplicate item in the Series which are occurred twice means these numbers have occured before in the series
dt_practice[dt_practice.duplicated()].tolist()

[nan, 18.0, 25.0, nan]

In [32]:
dt_practice.fillna(dt_practice.mean())

0    12.000000
1    24.714286
2    25.000000
3    18.000000
4    24.714286
5    30.000000
6    45.000000
7    18.000000
8    25.000000
9    24.714286
dtype: float64

# TEXT CLEANING IN PANDAS

### Lowercase String   ---> ravi singh vohra
### Uppercase String   ---> RAVI SINGH VOHRA
### Capitalise String  ---> Ravi singh vohra
### Title String       ---> Ravi Singh Vohra
### Camelcase String   ---> raviSinghVohra 
### Snakecase String   ---> ravi_singh_vohra

In [2]:
names=pd.Series( ['ravi','Aman Kumar','ayush Baunthiyal','RISHABH Rathaur','Diya KoTHAri'])
names

0                ravi
1          Aman Kumar
2    ayush Baunthiyal
3     RISHABH Rathaur
4        Diya KoTHAri
dtype: object

In [15]:
# string="ravi"
# string.upper()

# You can directly apply string functions on the string but YOU CANNOT APPLY DIrect string functions on string in SERIES.

names.str.upper()

# 👉 All text operations in pandas use: .str()
# str is a submodule of pandas. It contains string related functions which are used to manage the string data in pandas

# Syntax: pandas_object.str.string_methods()

0                RAVI
1          AMAN KUMAR
2    AYUSH BAUNTHIYAL
3     RISHABH RATHAUR
4        DIYA KOTHARI
dtype: object

### ✅ Lowercase / Uppercase / Capitalize / Tittle

In [19]:
# names.str.upper()
# names.str.lower()
# names.str.capitalize()
names.str.title()

0                Ravi
1          Aman Kumar
2    Ayush Baunthiyal
3     Rishabh Rathaur
4        Diya Kothari
dtype: object

In [17]:
names

0                ravi
1          Aman Kumar
2    ayush Baunthiyal
3     RISHABH Rathaur
4        Diya KoTHAri
dtype: object

### ✅ Remove Spaces

In [13]:
names.str.strip()     # both sides
# names.str.lstrip()    # left
# names.str.rstrip()    # right

0                ravi
1          Aman Kumar
2    ayush Baunthiyal
3     RISHABH Rathaur
4        Diya KoTHAri
dtype: object

### ✅ Replace Text

In [22]:
names.str.replace(" ", "_")

0                ravi
1          Aman_Kumar
2    ayush_Baunthiyal
3     RISHABH_Rathaur
4        Diya_KoTHAri
dtype: object

In [23]:
names.str.replace(" ", "_") # it will return a series and now if you want to do some mor text operations you cannot use string fun() directly
# names.str.replace(" ", "_").lower()  # it will give an error. You will have to use str() again to use any string methods

names.str.replace(" ", "_").str.lower()

0                ravi
1          aman_kumar
2    ayush_baunthiyal
3     rishabh_rathaur
4        diya_kothari
dtype: object

In [24]:
sentence=pd.Series( ['##@@my name@is ravi vohra####',
                     '$$$  I#study$Ai',
                     '@@$$$%%%    I love to%teach data science and ml###$$$   '])
sentence

0                        ##@@my name@is ravi vohra####
1                                      $$$  I#study$Ai
2    @@$$$%%%    I love to%teach data science and m...
dtype: object

In [42]:
# 🚀 STEP 1: First Rule — Always Start Simple
# 👉 As a beginner, don’t jump to complex code.

# Start with:

# sentence

# Observe output carefully.

# 🧹 STEP 2: Remove Garbage from Edges
# 👉 First thing to clean = starting and ending junk

# Why?
# Because it's easiest and safest

# ✅ Use strip()
sentence.str.strip('#@$% ')

# 💡 Beginner Thinking
# 👉 “I want to remove these characters ONLY from start and end”

# ⚠️ IMPORTANT LEARNING
# 👉 strip() does NOT clean inside text
# 👉 Only edges

# 🔧 STEP 3: Fix Internal Problems
# Now ask again:

# 👉 What is still wrong?
# ❌ @, #, %, $ still inside text

# ✅ Replace them
sentence.str.strip('#@$% ')\
        .str.replace('@', ' ')\
        .str.replace('#', ' ')\
        .str.replace('$', ' ')\
        .str.replace('%', ' ')

# 💡 Beginner Thinking
# 👉 “Wherever I see bad character → replace with space”

# 🧠 STEP 4: Fix Extra Spaces
# ✅ Remove extra spaces
# sentence.str.replace(r"\s+", " ", regex=True)
    
# 💡 Beginner Thinking
# 👉 \s+ = many spaces
# 👉 replace with one space

# 🎯 FINAL COMPLETE SOLUTION
# cleaned = sentence.str.strip('#@$% ')\
#                   .str.replace('@', ' ')\
#                   .str.replace('#', ' ')\
#                   .str.replace('$', ' ')\
#                   .str.replace('%', ' ')\
#                   .str.replace(r"\s+", " ", regex=True)\
#                   .str.title()

# cleaned = (
#     sentence.str.strip('#@$% ')
#             .str.replace('@', ' ')
#             .str.replace('#', ' ')
#             .str.replace('$', ' ')
#             .str.replace('%', ' ')
#             .str.replace(r"\s+", " ", regex=True)
#             .str.title()
# )

cleaned = (
    sentence.str.replace(r"[^a-zA-Z\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
            .str.title()
)

print(cleaned)

0                  My Name Is Ravi Vohra
1                             I Study Ai
2    I Love To Teach Data Science And Ml
dtype: object

🧠 HOW A BEGINNER SHOULD THINK (MOST IMPORTANT)

When you see dirty text:

🪜 Think in THIS ORDER
1️⃣ Observe
👉 What is wrong?

2️⃣ Clean edges
👉 use strip()

3️⃣ Clean inside
👉 use replace()

4️⃣ Fix spacing
👉 use regex

5️⃣ Format text
👉 use .title() / .lower()

❌ What Beginners Do Wrong :-
❌ Jump directly to regex
❌ Try everything in one step
❌ Don’t observe data

### 2. DataFrame (2-dimensional — the real star!)

Pandas DataFrame is a two-dimensional labeled table with rows and columns that can hold different data types.
DataFrame = Rows + Columns + Data
🔹 Important Properties
1. Columns = Each column is a Series Ex: df["Name"]
2. Index (row numbers) = df.index => Output: RangeIndex(start=0, stop=3, step=1)
3. Shape (rows, columns)

🔹 Creating DataFrame (Multiple Ways)
1. From Dictionary
Ex: pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6]
})
2. From List Ex: pd.DataFrame([[1,2],[3,4]], columns=["A","B"])
3. From NumPy
Ex: import numpy as np
    pd.DataFrame(np.random.rand(3,3))

In [5]:
# Example 1: Creating DataFrame from Dictionary
data = {
    'Name': ['Ali', 'Riya', 'Rahul', 'Priya', 'Aman'],
    'Age': [25, 30, 22, 28, 35],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Hyderabad'],
    'Salary': [65000, 80000, 45000, 72000, 95000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   28      Delhi   72000
4   Aman   35  Hyderabad   95000

In [19]:
# Run these on any DataFrame
print("Shape : ",df.shape)          # (rows, columns)
print("Column : ",df.columns)        # column names
print("RangeIndex : ",df.index)          # row labels
print(df.dtypes)         # data types
print()
# print(df.info())         # complete summary
# print(df.describe())     # only numeric columns
print(df.head(3))        # first 3 rows
print()
print(df.tail(2))        # last 2 rows
# print(df.sample(3))      # random 3 rows

Shape :  (5, 4)
Column :  Index(['Name', 'Age', 'City', 'Salary'], dtype='object')
RangeIndex :  RangeIndex(start=0, stop=5, step=1)
Name      object
Age        int64
City      object
Salary     int64
dtype: object

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000

    Name  Age       City  Salary
3  Priya   28      Delhi   72000
4   Aman   35  Hyderabad   95000

In [2]:
# 2nd way to make a Data-Frame by using multiple list and then giving column names while creating DataFrame
data_list = [
    ['Ali', 25, 'Delhi', 65000],
    ['Riya', 30, 'Mumbai', 80000],
    ['Rahul', 22, 'Bangalore', 45000],
    ['Priya', 22, 'Kochi', 55000],
    ['Aman', 22, 'Kolkata', 75000]
]

df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
print(df2)

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

### Accessing Data

In [3]:
print(df2['Name'])                    # single column → Series
print()
print(df2[['Name', 'Salary']])        # multiple columns → DataFrame

0      Ali
1     Riya
2    Rahul
3    Priya
4     Aman
Name: Name, dtype: object

    Name  Salary
0    Ali   65000
1   Riya   80000
2  Rahul   45000
3  Priya   55000
4   Aman   75000

In [6]:
# loc → uses labels
print(df.loc[0])                     # first row and all columns of that row

print()

print(df.loc[0:2, ['Name', 'Salary']])   # rows 0-2, specific columns

print()

# iloc → uses integer position
print(df.iloc[0:3, 0:2])             # first 3 rows, first 2 columns

Name        Ali
Age          25
City      Delhi
Salary    65000
Name: 0, dtype: object

    Name  Salary
0    Ali   65000
1   Riya   80000
2  Rahul   45000

    Name  Age
0    Ali   25
1   Riya   30
2  Rahul   22

In [2]:
import pandas as pd

# Complete DataFrame (Updated with all rows from image)
data = {
    'employee_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'employee_name': ['Ravi', 'Aman', 'Sneha', 'Karan', 'Neha', 'Pooja', 'Rahul', 'Simran', 'Vikas', 'Anjali'],
    'department': ['IT', 'HR', 'IT', 'Sales', 'HR', 'Sales', 'IT', 'HR', 'Sales', 'IT'],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'gender': ['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'salary': [75000, 50000, 68000, 45000, 52000, 47000, 72000, 51000, 46000, 80000],
    'experience': [5, 2, 4, 1, 3, 2, 6, 4, 2, 7],
    'performance_score': [88, 76, 91, 70, 82, 75, 95, 89, 72, 97]
}

df = pd.DataFrame(data)
df

,employee_id,employee_name,department,city,gender,salary,experience,performance_score
0,101,Ravi,IT,Delhi,Male,75000,5,88
1,102,Aman,HR,Mumbai,Male,50000,2,76
2,103,Sneha,IT,Delhi,Female,68000,4,91
3,104,Karan,Sales,Pune,Male,45000,1,70
4,105,Neha,HR,Mumbai,Female,52000,3,82
5,106,Pooja,Sales,Delhi,Female,47000,2,75
6,107,Rahul,IT,Pune,Male,72000,6,95
7,108,Simran,HR,Delhi,Female,51000,4,89
8,109,Vikas,Sales,Mumbai,Male,46000,2,72
9,110,Anjali,IT,Pune,Female,80000,7,97

In [3]:
# === Employees with experience 3, 4, or 5 years ===

exp_filtered = df[df['experience'].isin([3, 4, 5])]

print("Employees with Experience 3, 4, or 5 years:")
exp_filtered

Employees with Experience 3, 4, or 5 years:

,employee_id,employee_name,department,city,gender,salary,experience,performance_score
0,101,Ravi,IT,Delhi,Male,75000,5,88
2,103,Sneha,IT,Delhi,Female,68000,4,91
4,105,Neha,HR,Mumbai,Female,52000,3,82
7,108,Simran,HR,Delhi,Female,51000,4,89

In [6]:
# Alternative 1: Using OR condition
result1 = df[(df['experience'] == 3) | (df['experience'] == 4) | (df['experience'] == 5)]

# Alternative 2: Using query (Very clean and readable)
result2 = df.query("experience in [3, 4, 5]")

# Alternative 3:
result3 = df[ (df['experience'] >= 3) & (df['experience'] <= 5) ]

# Alternative 3: Using between() if range was continuous
# result3 = df[df['experience'].between(3, 5)]   # This also works here

exp_filtered = result2
exp_filtered

,employee_id,employee_name,department,city,gender,salary,experience,performance_score
0,101,Ravi,IT,Delhi,Male,75000,5,88
2,103,Sneha,IT,Delhi,Female,68000,4,91
4,105,Neha,HR,Mumbai,Female,52000,3,82
7,108,Simran,HR,Delhi,Female,51000,4,89

In [8]:
df[(df['experience'].isin([3, 5])) & (df['performance_score'] >= 85)]

,employee_id,employee_name,department,city,gender,salary,experience,performance_score
0,101,Ravi,IT,Delhi,Male,75000,5,88

In [9]:
data = {
    "student_name": [
        "Ravi", "Aman", "Sneha", "Karan", "Neha",
        "Pooja", "Rahul", "Simran", "Vikas", "Anjali"
    ],
    
    "math_marks": [
        85, 90, np.nan, 76, 88,
        92, np.nan, 81, 70, 95
    ],
    
    "science_marks": [
        78, np.nan, 89, 72, 91,
        85, 80, np.nan, 68, 94
    ],
    
    "english_marks": [
        82, 75, 88, np.nan, 90,
        87, 79, 84, np.nan, 96
    ],
    
    "attendance_percentage": [
        92, 88, np.nan, 75, 95,
        90, 85, np.nan, 80, 98
    ]
}

df = pd.DataFrame(data)
df

,student_name,math_marks,science_marks,english_marks,attendance_percentage
0,Ravi,85.0,78.0,82.0,92.0
1,Aman,90.0,NaN,75.0,88.0
2,Sneha,NaN,89.0,88.0,NaN
3,Karan,76.0,72.0,NaN,75.0
4,Neha,88.0,91.0,90.0,95.0
5,Pooja,92.0,85.0,87.0,90.0
6,Rahul,NaN,80.0,79.0,85.0
7,Simran,81.0,NaN,84.0,NaN
8,Vikas,70.0,68.0,NaN,80.0
9,Anjali,95.0,94.0,96.0,98.0

In [11]:
# === Total Marks (Math + Science + English) ===

# Fill NaN with 0 for total calculation (common practice)
df['total_marks'] = df[['math_marks', 'science_marks', 'english_marks']].fillna(0).sum(axis=1)

# Show result with Total Marks
result = df[['student_name', 'math_marks', 'science_marks', 'english_marks', 'total_marks']]
result

  student_name  math_marks  science_marks  english_marks  total_marks
0         Ravi        85.0           78.0           82.0        245.0
1         Aman        90.0            NaN           75.0        165.0
2        Sneha         NaN           89.0           88.0        177.0
3        Karan        76.0           72.0            NaN        148.0
4         Neha        88.0           91.0           90.0        269.0
5        Pooja        92.0           85.0           87.0        264.0
6        Rahul         NaN           80.0           79.0        159.0
7       Simran        81.0            NaN           84.0        165.0
8        Vikas        70.0           68.0            NaN        138.0
9       Anjali        95.0           94.0           96.0        285.0

In [8]:
# Example 1: Salary > 70000
# high_earners = df2[df2['Salary'] > 70000]
high_earners = df2.query("Salary > 70000")
print(high_earners)

print()

# Example 2: Multiple conditions
# delhi_high = df2[(df2['City'] == 'Delhi') & (df2['Salary'] > 60000)]
# print(delhi_high)
dl_high = df2.query("City == 'Delhi' and Salary > 60000")
print(dl_high)

print() 

# Example 3: Using .query() (cleaner syntax)
young_delhi = df2.query("Age < 28 and City == 'Delhi'")
print(young_delhi)

# 1. Use df.query() — Best for filtering with conditions (SQL-like)
# Good when you want readable filtering.
# ✅ Clean
# ✅ Readable
# ❌ Slightly slower sometimes
# ❌ Can't use complex Python logic easily

# 2. Use Boolean Indexing — Most common & flexible (Recommended default)
# This is usually best in real projects.
# ✅ Very flexible
# ✅ Works with all logic
# ✅ Most widely used
# ✅ Faster in many cases

# What should YOU use?

# Use this rule:
# Filtering only → Boolean indexing
# Filtering readable SQL style → query()
# Filtering + column select → .loc[] ⭐ best
# Position based → .iloc[]

print()
using_loc = df2.loc[df2["Age"] > 25, ["Name", "Salary"]]
print(using_loc)

   Name  Age     City  Salary
1  Riya   30   Mumbai   80000
4  Aman   22  Kolkata   75000

  Name  Age   City  Salary
0  Ali   25  Delhi   65000

  Name  Age   City  Salary
0  Ali   25  Delhi   65000

   Name  Salary
1  Riya   80000

In [29]:
df2

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

In [7]:
# creating a new column in the existing Dataframe [df2]
df2["Designation"] = ["IT","Sales","Testing","Engineer","CA"]
df2

    Name  Age       City  Salary Designation
0    Ali   25      Delhi   65000          IT
1   Riya   30     Mumbai   80000       Sales
2  Rahul   22  Bangalore   45000     Testing
3  Priya   22      Kochi   55000    Engineer
4   Aman   22    Kolkata   75000          CA

In [12]:
# creating a new column in the existing Dataframe [df2]
df2["email"] = ['ali@company.com','riya@company.com','rahul@company.com','Priya@company.com',np.nan]
df2

    Name  Age       City  Salary Designation              email
0    Ali   25      Delhi   65000          IT    ali@company.com
1   Riya   30     Mumbai   80000       Sales   riya@company.com
2  Rahul   22  Bangalore   45000     Testing  rahul@company.com
3  Priya   22      Kochi   55000    Engineer  Priya@company.com
4   Aman   22    Kolkata   75000          CA                NaN

In [46]:
# DROPING A CLOMUN FROM THE DATAFRAME
df2.drop("Designation",axis = 1) # it doesnot remove from the main data it just shows you a snapshot of what it will look like
# if you print df2 it will still show Designation column.

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

In [47]:
df2

    Name  Age       City  Salary Designation
0    Ali   25      Delhi   65000          IT
1   Riya   30     Mumbai   80000       Sales
2  Rahul   22  Bangalore   45000     Testing
3  Priya   22      Kochi   55000    Engineer
4   Aman   22    Kolkata   75000          CA

In [48]:
# To remove any column permanently we will use 'inplace = True' attribute in drop()
df2.drop("Designation",axis = 1,inplace = True)

In [49]:
df2

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

# 📘 Pandas drop() Function – Axis Explained

# 🔹 1. Purpose of drop() = The drop() function in Pandas is used to remove rows or columns from a DataFrame.
          df.drop(labels, axis, inplace)

# 🔹 2. Understanding axis
        axis = 0  =  Rows (default)	
        axis = 1  =  Columns 

# 🔹 3. Dropping Columns = To remove a column, use axis = 1
        df.drop("Designation", axis=1)

# 🔹 4. Dropping Rows = To remove a row, use axis = 0 (or default)
        df.drop(0, axis=0)

        👉 Removes the row with index 0

# 🔹 5. Default Behavior (Important) = If axis is not specified:
        df.drop("Designation")
        
        ✔️ Equivalent to:

        df.drop("Designation", axis=0)

        👉 It will try to remove a row, not a column
        👉 May cause KeyError if no such row exists

# 🔹 6. Using inplace=True
        df.drop("Designation", axis=1, inplace=True)

        inplace = True → modifies original DataFrame
        Without it → returns a new DataFrame

# 🔹 7. Alternative (Cleaner Syntax) = Instead of axis, you can use:

        df.drop(columns=["Designation"])
        
        👉 Preferred in interviews (more readable)

# 🔹 8. Common Errors

        ❌ Wrong:
        
        df.drop("Designation")

        ➡️ Error:
        KeyError: "['Designation'] not found in axis"
        
        ✔️ Correct:
        
        df.drop("Designation", axis=1)

# 🔹 9. Summary
        drop() removes rows or columns
        Default axis = 0 → rows
        Use axis = 1 → columns
        Use inplace=True to update original data
        Prefer columns= for cleaner code

SIMILARLY YOU CAN DROP OTHER COLUMN ALSO. 
IF YOU WANT TO DROP MULTIPLE COLUMN THEN FOLLOW THE SAME PATH AND PUT ALL THE COLUMN NAME IN A LIST
Syntax = dataFrame_Name.drop([Col1,Col2,...ColN], inplace = True)

In [10]:
sales_data = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    'Region': ['North', 'South', 'North', 'East', 'South'],
    'Units': [10, 25, 15, 8, 30],
    'Revenue': [500000, 750000, 300000, 400000, 900000]
})
sales_data

  Product Region  Units  Revenue
0  Laptop  North     10   500000
1   Phone  South     25   750000
2  Tablet  North     15   300000
3  Laptop   East      8   400000
4   Phone  South     30   900000

In [37]:
print(sales_data[sales_data['Revenue'] > 400000])

  Product Region  Units  Revenue
0  Laptop  North     10   500000
1   Phone  South     25   750000
4   Phone  South     30   900000

In [11]:
sales_data

  Product Region  Units  Revenue
0  Laptop  North     10   500000
1   Phone  South     25   750000
2  Tablet  North     15   300000
3  Laptop   East      8   400000
4   Phone  South     30   900000

In [15]:
sales_data[(sales_data['Revenue'] >= 500000) & (sales_data['Region'] == 'North')]

  Product Region  Units  Revenue
0  Laptop  North     10   500000

# Handling Missing Data In Pandas

In [27]:
data_missing = {
    'A': [1,2, np.nan, 4, 5],
    'B': [1,2,3,4,5],
    'C': [1, 2, 3, np.nan,np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

miss_data = pd.DataFrame(data_missing)
miss_data

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

### 1. Finding Missing Data = using 'isna()'

In [28]:
miss_data.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [29]:
miss_data.isna().sum() # Output will be the sum of how many NaN values each column contains.

A    1
B    0
C    2
D    3
dtype: int64

In [30]:
miss_data.isna().any() # Output: Here i want that if any the columns have atleast one NaN values

A     True
B    False
C     True
D     True
dtype: bool

### 2. Removing Missing Values = It works on the basis of Rows

In [32]:
miss_data.dropna() # Since all the rows have atleast one NaN values except row = 0 so all the data will be removed and only row = 0 will remain

     A  B    C    D
0  1.0  1  1.0  1.0

In [34]:
miss_data.dropna(thresh = 3)  # thresh = any_value it basically checks that if the rows have that usch amount of NON NULL values in it

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

### 3. Filling the missing Data

In [38]:
miss_data.fillna(0)  # It will fill all the NaN values with '0' but the change is temporary to make it permanent we will use 'inplace=True'

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [37]:
miss_data

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [41]:
miss_data.fillna(value = 100)  # it will replace all the NaN with 100

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  100.0
2  100.0  3    3.0  100.0
3    4.0  4  100.0  100.0
4    5.0  5  100.0    5.0

In [44]:
values = {'A':0,'B':100,'C':200,'D':150}
miss_data.fillna(value = values)  # since A and B columns does not have any NaN value so it will get ignored

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  150.0
2  0.0  3    3.0  150.0
3  4.0  4  200.0  150.0
4  5.0  5  200.0    5.0

dropna() = Works on rows
fillna() = works on columns
isna() = works on column

In [45]:
miss_data

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [46]:
# Forward Fill (ffill) = 👉 Fills missing values using previous (above) 
miss_data.ffill()

# ✅ Output Explanation:
# Column A → NaN at index 2 becomes 2.0
# Column C → NaN becomes 3.0
# Column D → fills downward from 1.0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  2.0  3  3.0  1.0
3  4.0  4  3.0  1.0
4  5.0  5  3.0  5.0

In [48]:
# Backward Fill (bfill) = 👉 Fills missing values using next (below) value
miss_data.bfill()

# ✅ Output Explanation:
# Column A → NaN at index 2 becomes 4.0
# Column C → NaN becomes next valid (none below → stays NaN at end)
# Column D → all NaNs become 5.0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  5.0
2  4.0  3  3.0  5.0
3  4.0  4  NaN  5.0
4  5.0  5  NaN  5.0

Note - If any column starts with NaN which means at 0th row of any co,umn if there is NaN and if we are using ffill() on that column
       then that value will remain NaN. Why? Because there is no previous value above it.
       ✔️ Rule: ffill can only copy from above, so first row NaN cannot be filled.

        What happens with bfill()?
        👉 Result:
        
        The first row (index 0) will be filled using next valid value
        Example: if next value is 2.0, it becomes 2.0
        
        ✔️ Rule: bfill fills using below values, so it works for first row NaN

        Best Practice (Handle Edge Cases)

        👉 miss_data.ffill().bfill()
        
        👉 Why this works:
        
        ffill() fills middle NaNs
        bfill() fills starting NaNs (like index 0)

        Key Takeaway
        ffill() ❌ cannot fill starting NaN
        bfill() ❌ cannot fill ending NaN
        ✔️ Combine both for complete filling

In [49]:
miss_data.ffill().bfill()

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  2.0  3  3.0  1.0
3  4.0  4  3.0  1.0
4  5.0  5  3.0  5.0

# Merging , Joining And Concatination

In [50]:
# DataFrame 1: Customers
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Amit", "Riya", "John", "Sara"],
    "city": ["Delhi", "Mumbai", "Pune", "Delhi"]
})

# DataFrame 2: Orders
df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 2, 5, 6],
    "product": ["Laptop", "Mobile", "Tablet", "Camera", "Watch"]
})

In [52]:
df_customers

   customer_id  name    city
0            1  Amit   Delhi
1            2  Riya  Mumbai
2            3  John    Pune
3            4  Sara   Delhi

In [53]:
df_orders

   order_id  customer_id product
0       101            1  Laptop
1       102            2  Mobile
2       103            2  Tablet
3       104            5  Camera
4       105            6   Watch

### 1. MERGING (Most Important 🔥)

In [51]:
# 🔹 Inner Join (Common records only)
pd.merge(df_customers, df_orders, on="customer_id", how="inner")

   customer_id  name    city  order_id product
0            1  Amit   Delhi       101  Laptop
1            2  Riya  Mumbai       102  Mobile
2            2  Riya  Mumbai       103  Tablet

In [56]:
# 🔹 Left Join
pd.merge(df_customers, df_orders, on="customer_id", how="left")

# 👉 All customers + matching orders
# 👉 Customers without orders → NaN

   customer_id  name    city  order_id product
0            1  Amit   Delhi     101.0  Laptop
1            2  Riya  Mumbai     102.0  Mobile
2            2  Riya  Mumbai     103.0  Tablet
3            3  John    Pune       NaN     NaN
4            4  Sara   Delhi       NaN     NaN

In [57]:
# 🔹 Right Join
pd.merge(df_customers, df_orders, on="customer_id", how="right")

# 👉 All orders + matching customers
# 👉 Orders with no customer → NaN

   customer_id  name    city  order_id product
0            1  Amit   Delhi       101  Laptop
1            2  Riya  Mumbai       102  Mobile
2            2  Riya  Mumbai       103  Tablet
3            5   NaN     NaN       104  Camera
4            6   NaN     NaN       105   Watch

In [58]:
# 🔹 Outer Join (Full Join)
pd.merge(df_customers, df_orders, on="customer_id", how="outer")

   customer_id  name    city  order_id product
0            1  Amit   Delhi     101.0  Laptop
1            2  Riya  Mumbai     102.0  Mobile
2            2  Riya  Mumbai     103.0  Tablet
3            3  John    Pune       NaN     NaN
4            4  Sara   Delhi       NaN     NaN
5            5   NaN     NaN     104.0  Camera
6            6   NaN     NaN     105.0   Watch

### 2. JOIN (Index-based)

In [59]:
# First set index:

df1 = df_customers.set_index("customer_id")
df2 = df_orders.set_index("customer_id")

In [60]:
# 🔹 Left Join using .join()
df1.join(df2, how="left")

# 👉 Works similar to merge but uses index

             name    city  order_id product
customer_id
1            Amit   Delhi     101.0  Laptop
2            Riya  Mumbai     102.0  Mobile
2            Riya  Mumbai     103.0  Tablet
3            John    Pune       NaN     NaN
4            Sara   Delhi       NaN     NaN

### 3. CONCATENATION

In [61]:
# 🔹 Row-wise (Stack rows)
pd.concat([df_customers, df_customers])

# 👉 Doubles the rows

   customer_id  name    city
0            1  Amit   Delhi
1            2  Riya  Mumbai
2            3  John    Pune
3            4  Sara   Delhi
0            1  Amit   Delhi
1            2  Riya  Mumbai
2            3  John    Pune
3            4  Sara   Delhi

In [62]:
# 🔹 Column-wise (Side by side)
pd.concat([df_customers, df_orders], axis=1)

# 👉 Joins columns (may create NaN if sizes differ)

   customer_id  name    city  order_id  customer_id product
0          1.0  Amit   Delhi       101            1  Laptop
1          2.0  Riya  Mumbai       102            2  Mobile
2          3.0  John    Pune       103            2  Tablet
3          4.0  Sara   Delhi       104            5  Camera
4          NaN   NaN     NaN       105            6   Watch

# GROUP BY AND AGGREGATION

🔹 1. What is groupby()?
        👉 groupby() is used to:
        
        Split → Apply → Combine
        
        Split data into groups on the basis of common data/row.
        Apply agg. function (sum, mean, count, etc.)
        Combine results

In [3]:
df_groupby = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Finance", "IT"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Salary": [60000, 50000, 70000, 45000, 80000, 65000],
    "Experience": [2, 3, 5, 2, 7, 4]
})

df_groupby

  Department Employee  Salary  Experience
0         IT        A   60000           2
1         HR        B   50000           3
2         IT        C   70000           5
3         HR        D   45000           2
4    Finance        E   80000           7
5         IT        F   65000           4

In [71]:
# 🔹  Basic Grouping

# 👉 Group by single column
df_groupby.groupby("Department")
# will not show output until an aggregation function is used

In [4]:
list( df_groupby.groupby("Department") )

[('Finance',
    Department Employee  Salary  Experience
  4    Finance        E   80000           7),
 ('HR',
    Department Employee  Salary  Experience
  1         HR        B   50000           3
  3         HR        D   45000           2),
 ('IT',
    Department Employee  Salary  Experience
  0         IT        A   60000           2
  2         IT        C   70000           5
  5         IT        F   65000           4)]

### 🔹 Aggregation Functions

In [9]:
# 👉 Sum
df_groupby.groupby("Department")["Salary"].sum().reset_index()

  Department  Salary
0    Finance   80000
1         HR   95000
2         IT  195000

In [6]:
# 👉 Mean
# df_groupby.groupby("Department")["Salary"].mean()

print()
# 👉 Count
# df_groupby.groupby("Department")["Employee"].count()

print()
# 👉 Multiple aggregations
df_groupby.groupby("Department")["Salary"].agg(["sum", "mean", "max", "min"])
# here it means that we have grouped the table using Department Column and then we have applied the aggregation functions on
# the salary column.
# other agg fun are :- median , count

               sum     mean    max    min
Department
Finance      80000  80000.0  80000  80000
HR           95000  47500.0  50000  45000
IT          195000  65000.0  70000  60000

### 🔹 Group by Multiple Columns

In [70]:
df_groupby.groupby(["Department", "Experience"])["Salary"].mean()

Department  Experience
Finance     7             80000.0
HR          2             45000.0
            3             50000.0
IT          2             60000.0
            4             65000.0
            5             70000.0
Name: Salary, dtype: float64

### 🔹 Reset Index (Very Important)

In [8]:
df_groupby.groupby("Department")["Salary"].mean().reset_index()

  Department   Salary
0    Finance  80000.0
1         HR  47500.0
2         IT  65000.0

In [ ]:
# | Before reset_index() | After reset_index() |
# | -------------------- | ------------------- |
# | Department = index   | Department = column |
# | Harder to use        | Easy to use         |

# 🔹 Quick Memory Trick
# groupby() → column becomes index
# reset_index() → index becomes column again

### 🔹 Aggregating Multiple Columns

In [10]:
df_groupby.groupby("Department").agg({
    "Salary": ["sum", "mean"],
    "Experience": "max"
})

            Salary          Experience
               sum     mean        max
Department
Finance      80000  80000.0          7
HR           95000  47500.0          3
IT          195000  65000.0          5

### 🔹 Named Aggregation (Clean Output 🔥)

In [11]:
df_groupby.groupby("Department").agg(
    avg_salary=("Salary", "mean"),
    total_salary=("Salary", "sum")
)

            avg_salary  total_salary
Department
Finance        80000.0         80000
HR             47500.0         95000
IT             65000.0        195000

### 🔹 count() vs size()

In [17]:
# df_groupby.groupby("Department").count()
df_groupby.groupby("Department").size()

# ✔️ Difference:

# count() → ignores NaN
# size() → counts all rows

Department
Finance    1
HR         2
IT         3
dtype: int64

### 🔹 value_counts() (Shortcut)

In [18]:
df_groupby["Department"].value_counts()

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

### 🔹 Real Interview Examples 🔥

In [ ]:
# 👉 Avg salary per department
df.groupby("Department")["Salary"].mean()

# 👉 Highest salary employee per dept
df.loc[df.groupby("Department")["Salary"].idxmax()]

# 👉 Employees earning above dept average
df[df["Salary"] > df.groupby("Department")["Salary"].transform("mean")]

# 📘 Pandas Pivot Tables – Complete Guide

### 🔹 1. What is a Pivot Table?

👉 A pivot table is used to:

Summarize, group, and aggregate data in a tabular format

✔️ Similar to Excel Pivot Table
✔️ Built on top of groupby()

### 🔹 2. Why Use Pivot Table?

✔️ Quick summary of large data
✔️ Multi-dimensional analysis
✔️ Cleaner than complex groupby()

### 🔹 3. Create Sample Dataset

In [2]:
df_pvt= pd.DataFrame({
    "Date": ["2024-01", "2024-01", "2024-02", "2024-02", "2024-03"],
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi"],
    "Product": ["Laptop", "Laptop", "Mobile", "Mobile", "Laptop"],
    "Sales": [50000, 60000, 30000, 40000, 70000],
    "Quantity": [5, 6, 3, 4, 7]
})

df_pvt

      Date    City Product  Sales  Quantity
0  2024-01   Delhi  Laptop  50000         5
1  2024-01  Mumbai  Laptop  60000         6
2  2024-02   Delhi  Mobile  30000         3
3  2024-02  Mumbai  Mobile  40000         4
4  2024-03   Delhi  Laptop  70000         7

### 🔹 4. Basic Pivot Table

In [25]:
pd.pivot_table(df_pvt, values="Sales", index="City")
# 👉 Output: Average sales per city
# Here is the little catch that here we haven't give any aggregate function means we haven't specified any agg. fun()
# But the question is 🔹 Why is it giving average (mean)?

# 👉 Because pivot_table() has a default aggregation function
# ✅ Default: aggfunc = "mean"

# 🔹 So internally, your code behaves like:

# pd.pivot_table(df, values="Sales", index="City", aggfunc="mean")

# 👉 That’s why you get average sales per city

# So if you will not specify which aggfunc to use. It will use 'mean' as a by default aggfunc

# 🔹 Why Pandas chose mean as default?

# Because:
# Average is the most commonly used summary
# Same default behavior as many statistical tools

# 🔹 Common Mistake (Interview Trap ⚠️)

# Many students think:

# “Pivot table is just grouping”

# ❌ Wrong
# ✔️ It always aggregates, even if you don’t specify

          Sales
City
Delhi   50000.0
Mumbai  50000.0

### 🔹 5. Key Parameters (VERY IMPORTANT)

In [22]:
pd.pivot_table(
    df_pvt,
    values="Sales",
    index="City",
    columns="Product",
    aggfunc="sum"
)

# 🔑 Meaning:
# values → column to aggregate
# index → rows (grouping)
# columns → columns (grouping)
# aggfunc → function (sum, mean, etc.)

Product  Laptop  Mobile
City
Delhi    120000   30000
Mumbai    60000   40000

### 🔹 6. Multiple Aggregations

In [23]:
pd.pivot_table(
    df_pvt,
    values="Sales",
    index="City",
    aggfunc=["sum", "mean", "max"]
)

           sum     mean    max
         Sales    Sales  Sales
City
Delhi   150000  50000.0  70000
Mumbai  100000  50000.0  60000

In [3]:
df_pvt

      Date    City Product  Sales  Quantity
0  2024-01   Delhi  Laptop  50000         5
1  2024-01  Mumbai  Laptop  60000         6
2  2024-02   Delhi  Mobile  30000         3
3  2024-02  Mumbai  Mobile  40000         4
4  2024-03   Delhi  Laptop  70000         7

In [5]:
pd.pivot_table(df_pvt,values="Sales",index="City",columns="Product",aggfunc="sum")

Product  Laptop  Mobile
City
Delhi    120000   30000
Mumbai    60000   40000

In 'values' you should give only numeric columns. If you give any other column which have other data and not numeric data it will give an error.