In [1]:
import numpy as np
import pandas as pd

In [2]:
coffee = pd.read_csv("coffee.csv")
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [3]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [4]:
coffee.sample()

      Day Coffee Type  Units Sold
0  Monday    Espresso          25

In [7]:
coffee.loc[0] # Syntax: df.loc[#rows, #columns
# Here we have not given any column value so it will take all the columns for 0th row

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [10]:
coffee.loc[[0,3]] # 0th and 3rd index row

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
3  Tuesday       Latte          20

In [11]:
coffee.loc[0:3] # from 0th to 3rd index row

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [12]:
coffee.loc[0:3, "Day"]

0     Monday
1     Monday
2    Tuesday
3    Tuesday
Name: Day, dtype: object

In [14]:
coffee.loc[0:3, ["Day","Units Sold"]] # here you can not use numbers to access columns 
# because .loc[] only gets that rows and cols which are equal to this value

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [16]:
coffee.iloc[0:3,0:2] # Here You can use numbers to access both rows and cols because it gets the data by the index positions
# Also here the outer value is exclusive but in the .loc[] we saw it was inclusive.

       Day Coffee Type
0   Monday    Espresso
1   Monday       Latte
2  Tuesday    Espresso

In [17]:
coffee.at[0,"Day"]

'Monday'

In [ ]:
coffee