In [1]:
import numpy as np
import pandas as pd

In [47]:
coffee = pd.read_csv("coffee.csv")

# ACCESSING DATA WITH PANDAS

In [20]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [3]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [4]:
coffee.sample()

      Day Coffee Type  Units Sold
0  Monday    Espresso          25

In [7]:
coffee.loc[0] # Syntax: df.loc[#rows, #columns
# Here we have not given any column value so it will take all the columns for 0th row

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [10]:
coffee.loc[[0,3]] # 0th and 3rd index row

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
3  Tuesday       Latte          20

In [11]:
coffee.loc[0:3] # from 0th to 3rd index row

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [12]:
coffee.loc[0:3, "Day"]

0     Monday
1     Monday
2    Tuesday
3    Tuesday
Name: Day, dtype: object

In [14]:
coffee.loc[0:3, ["Day","Units Sold"]] # here you can not use numbers to access columns 
# because .loc[] only gets that rows and cols which are equal to this value

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [16]:
coffee.iloc[0:3,0:2] # Here You can use numbers to access both rows and cols because it gets the data by the index positions
# Also here the outer value is exclusive but in the .loc[] we saw it was inclusive.

       Day Coffee Type
0   Monday    Espresso
1   Monday       Latte
2  Tuesday    Espresso

In [17]:
coffee.at[0,"Day"]

'Monday'

In [18]:
coffee.iat[0,0]

'Monday'

In [21]:
coffee.sort_values("Day")

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
9      Friday       Latte          35
0      Monday    Espresso          25
1      Monday       Latte          15
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35
6    Thursday    Espresso          40
7    Thursday       Latte          30
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25

In [22]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [23]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

# Filtering Data

In [24]:
bios = pd.read_csv("results.csv")

In [25]:
bios.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [26]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [28]:
# Find those athlete who have scored first place
bios.loc[bios['place'] == 1]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
31,1900.0,Summer,Fencing,"Épée, Individual, Men (Olympic)","Élie, Comte de Lastours",11,FRA,NaN,1.0,False,NaN
39,1900.0,Summer,Tennis,"Doubles, Handicap, Men (Olympic (non-medal))",Max Decugis,12,FRA,Spalding de Garmendia,1.0,False,NaN
40,NaN,NaN,Tennis,"Singles, Men (Intercalated)",Max Decugis,12,FRA,NaN,1.0,False,Gold
41,NaN,NaN,Tennis,"Doubles, Mixed (Intercalated)",Max Decugis,12,FRA,Marie Decugis,1.0,False,Gold
42,NaN,NaN,Tennis,"Doubles, Men (Intercalated)",Max Decugis,12,FRA,Maurice Germot,1.0,False,Gold
...,...,...,...,...,...,...,...,...,...,...,...
308139,2022.0,Winter,Figure Skating (Skating),"Team, Mixed (Olympic)",Aleksandr Gallyamov,148811,ROC,ROC,1.0,False,Gold
308141,2022.0,Winter,Figure Skating (Skating),"Team, Mixed (Olympic)",Mark Kondratyuk,148812,ROC,ROC,1.0,False,Gold
308290,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Marco Odermatt,148903,SUI,NaN,1.0,False,Gold
308326,2018.0,Summer,Triathlon,"Relay, Mixed Youth (YOG)",Anja Weber,148920,SUI,Europe 1,1.0,False,Gold
308340,2022.0,Winter,Freestyle Skiing (Skiing),"Ski Cross, Men (Olympic)",Ryan Regez,148931,SUI,NaN,1.0,False,Gold

In [30]:
# Find the athlete_id and medal of those athlete who have scored first place
bios.loc[bios['place'] == 1, ['athlete_id','medal']]

        athlete_id medal
31              11   NaN
39              12   NaN
40              12  Gold
41              12  Gold
42              12  Gold
...            ...   ...
308139      148811  Gold
308141      148812  Gold
308290      148903  Gold
308326      148920  Gold
308340      148931  Gold

[16719 rows x 2 columns]

In [31]:
# Find the athlete_id and medal of those athlete who have scored first place
bios[bios['place'] == 1][['athlete_id','medal']]

        athlete_id medal
31              11   NaN
39              12   NaN
40              12  Gold
41              12  Gold
42              12  Gold
...            ...   ...
308139      148811  Gold
308141      148812  Gold
308290      148903  Gold
308326      148920  Gold
308340      148931  Gold

[16719 rows x 2 columns]

In [32]:
# Find the athlete_id and medal of those athlete who have scored first place and also type of olymipics is summer
bios[ (bios['place'] == 1) & (bios['type'] == 'Summer') ][['athlete_id','medal']]

        athlete_id medal
31              11   NaN
39              12   NaN
48              12  Gold
84              19  Gold
85              20  Gold
...            ...   ...
306357      147717  Gold
306375      147736  Gold
306429      147794  Gold
306432      147797  Gold
308326      148920  Gold

[13882 rows x 2 columns]

In [ ]:
bios[bios['name'].str.contains('sam')] # by this code you can find any name which contains 'sam' in it.

In [34]:
# Find those athletes whose country is wither 'USA' , 'FRA', 'UK' and their place is 1st and olympics type is summer
bios[ (bios['noc'].isin(["USA","FRA","UK"])) & (bios['place'] == 1) & (bios['type'] == 'Summer') ][['athlete_id','medal']]

        athlete_id medal
31              11   NaN
39              12   NaN
48              12  Gold
84              19  Gold
85              20  Gold
...            ...   ...
306283      147642  Gold
306288      147647  Gold
306330      147690  Gold
306429      147794  Gold
306432      147797  Gold

[3465 rows x 2 columns]

In [35]:
# Same above question can be done by using query()
bios.query('noc in ["USA", "FRA", "UK"] and place == 1 and type == "Summer"')[['athlete_id', 'medal']]

        athlete_id medal
31              11   NaN
39              12   NaN
48              12  Gold
84              19  Gold
85              20  Gold
...            ...   ...
306283      147642  Gold
306288      147647  Gold
306330      147690  Gold
306429      147794  Gold
306432      147797  Gold

[3465 rows x 2 columns]

# ADDING / REMOVING COLUMNS

In [60]:
coffee_new = coffee.copy() # if we do not use this copy() then both the coffee and coffee_new will point to same memory location
# where the data is stored and if we change in one variable it will lead to change in the another.

In [51]:
coffee_new.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [64]:
coffee_new['price'] = 6.99

In [65]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price  price
0     Monday    Espresso          25       4.99   6.99
1     Monday       Latte          15       6.99   6.99
2    Tuesday    Espresso          30       4.99   6.99
3    Tuesday       Latte          20       6.99   6.99
4  Wednesday    Espresso          35       4.99   6.99

In [66]:
coffee_new['Coffee Type'].value_counts()

Coffee Type
Espresso    7
Latte       7
Name: count, dtype: int64

In [67]:
coffee_new['new_price'] = np.where(coffee_new['Coffee Type'] == 'Espresso', 4.99,6.99)

In [63]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       4.99
1     Monday       Latte          15       6.99
2    Tuesday    Espresso          30       4.99
3    Tuesday       Latte          20       6.99
4  Wednesday    Espresso          35       4.99

In [68]:
coffee_new.drop(columns=['price'],inplace=True)

In [69]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       4.99
1     Monday       Latte          15       6.99
2    Tuesday    Espresso          30       4.99
3    Tuesday       Latte          20       6.99
4  Wednesday    Espresso          35       4.99

In [70]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [71]:
coffee_new['revenue'] = coffee_new['Units Sold'] * coffee_new['new_price']

In [72]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       4.99   124.75
1     Monday       Latte          15       6.99   104.85
2    Tuesday    Espresso          30       4.99   149.70
3    Tuesday       Latte          20       6.99   139.80
4  Wednesday    Espresso          35       4.99   174.65

In [75]:
coffee_new = coffee_new.rename(columns={'new_price':'Coffee Price', 'revenue':'Coffee Revenue'})

In [74]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       4.99   124.75
1     Monday       Latte          15       6.99   104.85
2    Tuesday    Espresso          30       4.99   149.70
3    Tuesday       Latte          20       6.99   139.80
4  Wednesday    Espresso          35       4.99   174.65