In [2]:
from IPython.display import HTML, display

display(HTML("""
<div style="
background:linear-gradient(135deg,#00A651,#00C853,#2196F3);
padding:20px;
border-radius:15px;
color:white;
font-size:42px;
font-weight:bold;
text-align:center;
font-family:Segoe UI;
margin:15px 0px;
box-shadow:0 4px 20px rgba(0,0,0,0.3);
">
Pivots
</div>
"""))

In [3]:
import pandas as pd

df = pd.DataFrame({
    'Date':['2025-01','2025-01',
            '2025-02','2025-02'],
    'Product':['Laptop','Mobile',
               'Laptop','Mobile'],
    'Sales':[10000,5000,
             12000,7000]
})

df

      Date Product  Sales
0  2025-01  Laptop  10000
1  2025-01  Mobile   5000
2  2025-02  Laptop  12000
3  2025-02  Mobile   7000

In [4]:
df.pivot(index='Date',columns='Product',values='Sales')

Product  Laptop  Mobile
Date
2025-01   10000    5000
2025-02   12000    7000