# 1. Text Analyzer Tool (BEST for learning)

### ✔ Count words
### ✔ Count characters
### ✔ Count sentences
### ✔ Most frequent word
### ✔ Remove punctuation

### Features:

### User enters a paragraph

### Your code analyzes it using loops + string functions + lists

In [10]:
para = input("Enter any paragraph / word : ").strip()
# print(para)
# 1. Remove punctuation
punctuations = ".,!?;:-_()[]{}\"'"
clean_text = ""
for char in para:
    if char not in punctuations:
        clean_text += char
# print(clean_text)

# 2. Count Words
para_length = len(clean_text.split(" "))
print(f"Total number of words in the Para you entered are : {para_length}")

# 3. Count characters
char_count = 0
for char in clean_text:
    if char != " ":
        char_count += 1
print(f"Total number of Characters in the Para you entered are : {char_count}")

# 4. Count Sentences
sentence_count = 0
for char in para:
    if char in ".!?":
        sentence_count += 1
print(f"Total number of Sentences in the Para you entered are : {sentence_count}")

# 5. Most frequent word
freq = {}
for w in clean_text:
    w = w.lower()
    if w in freq:
        freq[w] += 1
    else:
        freq[w] = 1

# find word with highest count
most_frequent = max(freq, key=freq.get)
print("Most Frequent Word:", most_frequent)

Enter any paragraph / word :   Hello! my name is Aditya Raj. I am a data analyst. I am very fond of data. I am also a software developer.

Total number of words in the Para you entered are : 23
Total number of Characters in the Para you entered are : 79
Total number of Sentences in the Para you entered are : 5
Most Frequent Word:

# 2. To-Do List App (Console)

### ✔ Add tasks
### ✔ Remove tasks
### ✔ View tasks
### ✔ Mark complete

In [27]:
print("========================")
print("\tTO-DO LIST")
print("========================\n")

print('''1. Add Task
2. View Tasks
3. Remove Task
4. Exit\n''')

task = []

while True:
    task_number = int(input("Choose an option from the above : "))
    
    if task_number == 1:
        new_task = input("Enter a New Task you want to Add in To-Do list : ")
        task.append(new_task)
        print("\n Task Added Successfully!!")
        
    elif task_number == 2:
        if len(task) == 0:
            print("No tasks found!\n")
        else:
            print("\nYour Tasks are:")
            for i in range(len(task)):
                print(f"{i+1}. {task[i]}")
            print()
            
    elif task_number == 3:
        del_task = int(input("Enter the task number which you want to delete :"))
        if len(task) == 0:
            print("No tasks available to delete!\n")
        else:
            del_task = int(input("Enter the task number which you want to delete: "))
            if 1 <= del_task <= len(task):
                task.pop(del_task - 1)
                print("Task Deleted Successfully!\n")
            else:
                print("Invalid task number!\n")

    # 4. Exit
    elif task_number == 4:
        print("Exiting program... Thank you!")
        break

    else:
        print("Invalid option! Please enter 1–4.\n")

========================
	TO-DO LIST
========================

1. Add Task
2. View Tasks
3. Remove Task
4. Exit

Choose an option from the above :  2

No tasks found!

Choose an option from the above :  1
Enter a New Task you want to Add in To-Do list :  Study Python

 Task Added Successfully!!

Choose an option from the above :  1
Enter a New Task you want to Add in To-Do list :  Study Data analytics

 Task Added Successfully!!

Choose an option from the above :  2

Your Tasks are:
1. Study Python
2. Study Data analytics

Choose an option from the above :  4

Exiting program... Thank you!

# 3. BASIC CALCULATOR

In [35]:
print("========================")
print("\tTO-DO LIST")
print("========================\n")

num = int(input("Enter how many numbers you want to enter into Calculator : "))
num_list = []

for i in range(1,num+1):
    number = int(input(f"Enter the number {i} : "))
    num_list.append(number)

print('''\n1. Addition
2. Subtarction
3. Multiplication
4. Divison
5. Exit\n''')

while True:
    task_number = int(input("Choose an option from the above : "))

    if task_number == 1:
        # sum_list = 0
        # for i in range(len(num_list)):
        #     sum_list += num_list[i]
        print("Sum of Numbers you have entered is : ",sum(num_list))

    # 2. Subtraction
    elif task_number == 2:
        result = num_list[0]              # start from first number
        for i in range(1, len(num_list)): # subtract the rest
            result -= num_list[i]
        print("Result of Subtraction is :", result)

    # 3. Multiplication
    elif task_number == 3:
        result = 1
        for n in num_list:
            result *= n
        print("Result of Multiplication is :", result)

    # 4. Division
    elif task_number == 4:
        result = num_list[0]
        division_possible = True
        for i in range(1, len(num_list)):
            if num_list[i] == 0:
                print("Error: Cannot divide by zero! One of the numbers is 0.")
                division_possible = False
                break
            result /= num_list[i]
        if division_possible:
            print("Result of Division is :", result)

     # 4. Exit
    elif task_number == 5:
        print("Exiting program... Thank you!")
        break

    else:
        print("Invalid option! Please enter 1–5.\n")

========================
	TO-DO LIST
========================

Enter how many numbers you want to enter into Calculator :  2
Enter the number 1 :  10
Enter the number 2 :  23

1. Addition
2. Subtarction
3. Multiplication
4. Divison
5. Exit

Choose an option from the above :  1

Sum of Numbers you have entered is :  33

Choose an option from the above :  5

Exiting program... Thank you!

# 4. Count the Vowels

In [9]:
sentence = input("Enter a Sentence and i will count the number of times vowels are coming : ").lower()
count = 0
vowel = []

for char in sentence:
    if char in 'aeiou':
        count += 1
        vowel.append(char)
print(f"Vowels found : {vowel} | Count: {count} ")

Enter a Sentence and i will count the number of times vowels are coming :  Aditya Raj

Vowels found : ['a', 'i', 'a', 'a'] | Count: 4

# 5. Count Words and Their Length

In [14]:
# sentence = input("Enter a sentence and will count number of words in it and their length : ")
# list_sentence = sentence.split()
# print(f"Total Words : {len(list_sentence)} ")
# for word in list_sentence:
#     print(f"Length of '{word}' : {len(word)}")

sentence = input("Enter a sentence: ")

words = sentence.split()

print(f"Total Words: {len(words)}")
for w in words:
    print(f"{w} -> {len(w)}")

Enter a sentence:  hello there

Total Words: 2
hello -> 5
there -> 5

# 6. Find the Longest Word in a Sentence

In [28]:
# sentence = input("Enter a sentence: ")

# words = sentence.split()

# longest_word = [words[0]]
# for word in words:
#     if len(word) > len(longest_word[0]):
#         longest_word.pop()
#         longest_word.append(word)
# print(f"Longest Word : {longest_word[0]} ( Length : {len(longest_word[0])} )")

sentence = input("Enter a sentence: ")

words = sentence.split()

# Handle empty input case
if not words:
    print("No words found.")
else:
    # Step 1: Find the maximum length
    max_len = 0
    for word in words:
        if len(word) > max_len:
            max_len = len(word)

    # Step 2: Collect all words having max length
    longest_words = []
    for word in words:
        if len(word) == max_len:
            longest_words.append(word)

    # Step 3: Print results
    print(f"Longest word: {', '.join(longest_words)}")
    print(f"Length: {max_len}")

Enter a sentence:  cat bat rat mat

Longest word: cat, bat, rat, mat
Length: 3

In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[1,2,3] , [4,5,6] , [7,8,9]], columns = ['A','B','C'], index=['x','y','z'])
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [3]:
data_list = [
    ['Ali', 25, 'Delhi', 65000],
    ['Riya', 30, 'Mumbai', 80000],
    ['Rahul', 22, 'Bangalore', 45000],
    ['Priya', 22, 'Kochi', 55000],
    ['Aman', 22, 'Kolkata', 75000]
]

df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
print(df2)

    Name  Age       City  Salary
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

## Basic Questions

In [22]:
# 1. Display first 3 rows
# df2.head(3)

# 2. Display only Name column
# df2.Name
# df2['Name']

# 3. Display Name and Salary columns together
# df2[['Name', 'Salary']]

# 4. Find total number of rows and columns
# df2.shape

# 5. Display column names
# df2.columns

# 6. Check data types of all columns
# df2.dtypes

# 7. Find maximum salary
# print(df2['Salary'].max())

# 8. Find minimum age
# print(df2['Age'].min())

## Filtering Questions

In [23]:
# 1. Show employees whose age is 22
df2[ df2['Age'] == 22 ]

    Name  Age       City  Salary
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

In [24]:
# 2. Show employees whose salary is greater than 60000
df2[ df2['Salary'] > 60000 ]

   Name  Age     City  Salary
0   Ali   25    Delhi   65000
1  Riya   30   Mumbai   80000
4  Aman   22  Kolkata   75000

In [25]:
# 3. Show employees from Delhi
df2[ df2['City'] == 'Delhi' ]

  Name  Age   City  Salary
0  Ali   25  Delhi   65000

In [27]:
# 4. Show employees whose salary is between 50000 and 80000
df2.query("Salary > 50000 and Salary < 80000")

    Name  Age     City  Salary
0    Ali   25    Delhi   65000
3  Priya   22    Kochi   55000
4   Aman   22  Kolkata   75000

In [28]:
# 5. Show employees whose city starts with "K"
df2[ df2['City'].str.startswith("K") ]

    Name  Age     City  Salary
3  Priya   22    Kochi   55000
4   Aman   22  Kolkata   75000

In [29]:
# 6. Show employees whose name contains "a"
df2[ df2['Name'].str.contains('a') ]

    Name  Age       City  Salary
1   Riya   30     Mumbai   80000
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000

In [30]:
# 7. Show employees whose age is not 22
df2[ ~(df2['Age'] == 22) ]

   Name  Age    City  Salary
0   Ali   25   Delhi   65000
1  Riya   30  Mumbai   80000

In [31]:
# 8. Show employees with salary less than average salary
df2 [ df2['Salary'] < df2['Salary'].mean() ]

    Name  Age       City  Salary
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000

## Sorting Questions

In [34]:
# 1. Sort data by salary ascending order
df2.sort_values(by='Salary')

    Name  Age       City  Salary
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
0    Ali   25      Delhi   65000
4   Aman   22    Kolkata   75000
1   Riya   30     Mumbai   80000

In [35]:
# 2. Sort data by salary descending order
df2.sort_values(by = 'Salary', ascending = False)

    Name  Age       City  Salary
1   Riya   30     Mumbai   80000
4   Aman   22    Kolkata   75000
0    Ali   25      Delhi   65000
3  Priya   22      Kochi   55000
2  Rahul   22  Bangalore   45000

In [36]:
# 3. Sort by age then salary
print(df2.sort_values(by=['Age', 'Salary']))

    Name  Age       City  Salary
2  Rahul   22  Bangalore   45000
3  Priya   22      Kochi   55000
4   Aman   22    Kolkata   75000
0    Ali   25      Delhi   65000
1   Riya   30     Mumbai   80000

## Updating Questions

In [42]:
# 1. Increase everyone's salary by 5000
df2['Salary'] = df2['Salary']+5000  # it will permanentaly change the column of salary and update it

In [43]:
df2

    Name  Age       City  Salary
0    Ali   25      Delhi   75000
1   Riya   30     Mumbai   90000
2  Rahul   22  Bangalore   55000
3  Priya   22      Kochi   65000
4   Aman   22    Kolkata   85000

In [48]:
# 2. Change Rahul's city to Hyderabad
# df2.loc[df2['Name'] == 'Rahul', 'City'] # this will bring you the city of person named Rahul

df2.loc[df2['Name'] == 'Rahul', 'City'] = 'Hyderabad' # this will change the city name of Rahul

In [49]:
df2

    Name  Age       City  Salary
0    Ali   25      Delhi   75000
1   Riya   30     Mumbai   90000
2  Rahul   22  Hyderabad   55000
3  Priya   22      Kochi   65000
4   Aman   22    Kolkata   85000

In [50]:
# 3. Add new column Bonus with value 10000 for all employees
df2['Bonus'] = 10000
df2

    Name  Age       City  Salary  Bonus
0    Ali   25      Delhi   75000  10000
1   Riya   30     Mumbai   90000  10000
2  Rahul   22  Hyderabad   55000  10000
3  Priya   22      Kochi   65000  10000
4   Aman   22    Kolkata   85000  10000

In [51]:
# 4. Create new column Tax as 10% of salary
df2['Tax'] = (0.10 * df2['Salary'] )

In [52]:
df2

    Name  Age       City  Salary  Bonus     Tax
0    Ali   25      Delhi   75000  10000  7500.0
1   Riya   30     Mumbai   90000  10000  9000.0
2  Rahul   22  Hyderabad   55000  10000  5500.0
3  Priya   22      Kochi   65000  10000  6500.0
4   Aman   22    Kolkata   85000  10000  8500.0

In [54]:
# 5. Create new column Salary_After_Tax
# df2['Salary_After_Tax'] = (df2['Salary'] - (0.10 * df2['Salary'] ) )

# or
df2['Salary_After_Tax'] = df2['Salary'] - df2['Tax']
df2

    Name  Age       City  Salary  Bonus     Tax  Salary_After_Tax
0    Ali   25      Delhi   75000  10000  7500.0           67500.0
1   Riya   30     Mumbai   90000  10000  9000.0           81000.0
2  Rahul   22  Hyderabad   55000  10000  5500.0           49500.0
3  Priya   22      Kochi   65000  10000  6500.0           58500.0
4   Aman   22    Kolkata   85000  10000  8500.0           76500.0

## Conditional Column Questions

In [56]:
# Create a column Status
# "High" if salary > 70000
# "Medium" if salary between 50000 and 70000
# "Low" otherwise

def check_status(salary):
    if salary > 70000:
        return 'High'
    elif salary >= 50000:
        return 'Medium'
    else:
        return 'Low'

df2['Status'] = df2['Salary'].apply(check_status)

In [57]:
df2

    Name  Age       City  Salary  Bonus     Tax  Salary_After_Tax  Status
0    Ali   25      Delhi   75000  10000  7500.0           67500.0    High
1   Riya   30     Mumbai   90000  10000  9000.0           81000.0    High
2  Rahul   22  Hyderabad   55000  10000  5500.0           49500.0  Medium
3  Priya   22      Kochi   65000  10000  6500.0           58500.0  Medium
4   Aman   22    Kolkata   85000  10000  8500.0           76500.0    High

In [58]:
# Create column Adult
# Condition:
# "Yes" if age >= 18
# "No" otherwise

def check_age(age):
    if age >= 18:
        return "YES"
    else:
        return "NO"

df2['Adult'] = df2['Age'].apply(check_age)

In [59]:
df2

,Name,Age,City,Salary,Bonus,Tax,Salary_After_Tax,Status,Adult
0,Ali,25,Delhi,75000,10000,7500.0,67500.0,High,YES
1,Riya,30,Mumbai,90000,10000,9000.0,81000.0,High,YES
2,Rahul,22,Hyderabad,55000,10000,5500.0,49500.0,Medium,YES
3,Priya,22,Kochi,65000,10000,6500.0,58500.0,Medium,YES
4,Aman,22,Kolkata,85000,10000,8500.0,76500.0,High,YES

## Row/Column Manipulation

In [61]:
# 1. Add a new employee row
new_row = {'Name':'Vik','Age':28,'City':'Delhi','Salary':70000,'Bonus':10000,
           'Tax':7000.0,'Salary_After_Tax':63000.0,'Status':'High','Adult':'YES'}
df2 = pd.concat([df2, pd.DataFrame([new_row])], ignore_index=True)

In [62]:
df2

,Name,Age,City,Salary,Bonus,Tax,Salary_After_Tax,Status,Adult
0,Ali,25,Delhi,75000,10000,7500.0,67500.0,High,YES
1,Riya,30,Mumbai,90000,10000,9000.0,81000.0,High,YES
2,Rahul,22,Hyderabad,55000,10000,5500.0,49500.0,Medium,YES
3,Priya,22,Kochi,65000,10000,6500.0,58500.0,Medium,YES
4,Aman,22,Kolkata,85000,10000,8500.0,76500.0,High,YES
5,Vik,28,Delhi,70000,10000,7000.0,63000.0,High,YES

In [64]:
# 2. Delete City column
df2.drop(columns = ['City']) # it has not dropped the column permanentaly for that we have to use inplace=True

    Name  Age  Salary  Bonus     Tax  Salary_After_Tax  Status Adult
0    Ali   25   75000  10000  7500.0           67500.0    High   YES
1   Riya   30   90000  10000  9000.0           81000.0    High   YES
2  Rahul   22   55000  10000  5500.0           49500.0  Medium   YES
3  Priya   22   65000  10000  6500.0           58500.0  Medium   YES
4   Aman   22   85000  10000  8500.0           76500.0    High   YES
5    Vik   28   70000  10000  7000.0           63000.0    High   YES

In [6]:
df3 = pd.DataFrame({
    "emp_id": [101, 102, 103, 104],
    "name": ["Ravi", "Anjali", "Karan", "Sneha"],
    "department": ["IT", "HR", "Finance", "Sales"],
    "salary": [60000, 45000, 55000, 50000]
})

df3

   emp_id    name department  salary
0     101    Ravi         IT   60000
1     102  Anjali         HR   45000
2     103   Karan    Finance   55000
3     104   Sneha      Sales   50000

In [12]:
# write a code where we have to delete the detail of karan and final df should contatin only empi id and emp name
df3[['emp_id','name']].drop(2) # by default here axis = 0 which means rows

   emp_id    name
0     101    Ravi
1     102  Anjali
3     104   Sneha

In [13]:
df3[ df3['name'].str.lower() != "karan" ][['emp_id','name']]

   emp_id    name
0     101    Ravi
1     102  Anjali
3     104   Sneha

In [3]:
data = {
    'Emp_ID': ['E101', 'E102', 'E103', 'E104', 'E105',
               'E106', 'E107', 'E108', 'E109', 'E110'],

    'Name': [' aryan', 'RIYA ', 'Rahul123', 'priya@',
             'AMAN', 'sneha ', 'viKAs99',
             'KARAN#', 'Neha', 'roहित'],

    'Department': ['IT ', 'hr', 'Finance',
                   'IT', ' sales', 'HR ',
                   'finance ', 'Marketing',
                   'IT', 'Sales '],

    'Salary': ['50000', '65000 ', 'not available',
               '72000', '54000',
               ' 61000', '48000',
               '85000', None, '70000'],

    'Email': ['aryan@gmail.com ',
              'RIYA@GMAIL.COM',
              'rahul123@gmail',
              'priya@@gmail.com',
              'aman.gmail.com',
              ' sneha@gmail.com',
              None,
              'karan#gmail.com',
              'neha@gmail.com ',
              'rohit@gmail.com']
}

df3 = pd.DataFrame(data)

print(df3)

  Emp_ID      Name Department         Salary             Email
0   E101     aryan        IT           50000  aryan@gmail.com
1   E102     RIYA          hr         65000     RIYA@GMAIL.COM
2   E103  Rahul123    Finance  not available    rahul123@gmail
3   E104    priya@         IT          72000  priya@@gmail.com
4   E105      AMAN      sales          54000    aman.gmail.com
5   E106    sneha         HR           61000   sneha@gmail.com
6   E107   viKAs99   finance           48000              None
7   E108    KARAN#  Marketing          85000   karan#gmail.com
8   E109      Neha         IT           None   neha@gmail.com
9   E110     roहित     Sales           70000   rohit@gmail.com

## Practice Questions

### A. Basic Inspection

#### 1. Display first 5 rows

In [4]:
df3.head()

  Emp_ID      Name Department         Salary             Email
0   E101     aryan        IT           50000  aryan@gmail.com
1   E102     RIYA          hr         65000     RIYA@GMAIL.COM
2   E103  Rahul123    Finance  not available    rahul123@gmail
3   E104    priya@         IT          72000  priya@@gmail.com
4   E105      AMAN      sales          54000    aman.gmail.com

#### 2. Check shape of dataframe

In [5]:
df3.shape

(10, 5)

#### 3. Display all column names

In [9]:
df3.columns.tolist()

['Emp_ID', 'Name', 'Department', 'Salary', 'Email']

#### 4. Check datatype of each column

In [10]:
df3.dtypes

Emp_ID        object
Name          object
Department    object
Salary        object
Email         object
dtype: object

#### 5. Find missing values in each column

In [14]:
df3.isna().sum()

Emp_ID        0
Name          0
Department    0
Salary        1
Email         1
dtype: int64

### B. Updating Data

#### 6. Change department hr and HR to HR

In [28]:
df3['Department'] = df3['Department'].replace(['hr', 'HR'], 'HR')

In [29]:
df3

  Emp_ID      Name Department         Salary             Email
0   E101     aryan         IT          50000  aryan@gmail.com
1   E102     RIYA          HR         65000     RIYA@GMAIL.COM
2   E103  Rahul123    Finance  not available    rahul123@gmail
3   E104    priya@         IT          72000  priya@@gmail.com
4   E105      AMAN      Sales          54000    aman.gmail.com
5   E106    sneha          HR          61000   sneha@gmail.com
6   E107   viKAs99    finance          48000              None
7   E108    KARAN#  Marketing          85000   karan#gmail.com
8   E109      Neha         IT           None   neha@gmail.com
9   E110     roहित      Sales          70000   rohit@gmail.com

#### 7. Replace sales and Sales with Sales

In [31]:
df3['Department'] = df3['Department'].str.strip().replace({
    'sales': 'Sales',
    'Sales': 'Sales'
})

print(df3)

# Here, first we are stripping the extra space if there are any where the sales data is present than after that we are
# replacing it with the correct form of it

  Emp_ID      Name Department         Salary             Email
0   E101     aryan         IT          50000  aryan@gmail.com
1   E102     RIYA          HR         65000     RIYA@GMAIL.COM
2   E103  Rahul123    Finance  not available    rahul123@gmail
3   E104    priya@         IT          72000  priya@@gmail.com
4   E105      AMAN      Sales          54000    aman.gmail.com
5   E106    sneha          HR          61000   sneha@gmail.com
6   E107   viKAs99    finance          48000              None
7   E108    KARAN#  Marketing          85000   karan#gmail.com
8   E109      Neha         IT           None   neha@gmail.com
9   E110     roहित      Sales          70000   rohit@gmail.com

#### 8. Update Rahul123 to Rahul

In [33]:
df3['Name'] = df3['Name'].str.strip().replace('Rahul123','Rahul')

In [34]:
df3

  Emp_ID     Name Department         Salary             Email
0   E101    aryan         IT          50000  aryan@gmail.com
1   E102     RIYA         HR         65000     RIYA@GMAIL.COM
2   E103    Rahul    Finance  not available    rahul123@gmail
3   E104   priya@         IT          72000  priya@@gmail.com
4   E105     AMAN      Sales          54000    aman.gmail.com
5   E106    sneha         HR          61000   sneha@gmail.com
6   E107  viKAs99    finance          48000              None
7   E108   KARAN#  Marketing          85000   karan#gmail.com
8   E109     Neha         IT           None   neha@gmail.com
9   E110    roहित      Sales          70000   rohit@gmail.com

In [35]:
df3['Name'] = df3['Name'].str.strip()
df3

  Emp_ID     Name Department         Salary             Email
0   E101    aryan         IT          50000  aryan@gmail.com
1   E102     RIYA         HR         65000     RIYA@GMAIL.COM
2   E103    Rahul    Finance  not available    rahul123@gmail
3   E104   priya@         IT          72000  priya@@gmail.com
4   E105     AMAN      Sales          54000    aman.gmail.com
5   E106    sneha         HR          61000   sneha@gmail.com
6   E107  viKAs99    finance          48000              None
7   E108   KARAN#  Marketing          85000   karan#gmail.com
8   E109     Neha         IT           None   neha@gmail.com
9   E110    roहित      Sales          70000   rohit@gmail.com

#### 9. Replace finance and Finance with Finance

In [36]:
df3['Department'] = df3['Department'].str.strip().replace({
    'finance': 'Finance',
    'Finance': 'Finance'
})

df3

  Emp_ID     Name Department         Salary             Email
0   E101    aryan         IT          50000  aryan@gmail.com
1   E102     RIYA         HR         65000     RIYA@GMAIL.COM
2   E103    Rahul    Finance  not available    rahul123@gmail
3   E104   priya@         IT          72000  priya@@gmail.com
4   E105     AMAN      Sales          54000    aman.gmail.com
5   E106    sneha         HR          61000   sneha@gmail.com
6   E107  viKAs99    Finance          48000              None
7   E108   KARAN#  Marketing          85000   karan#gmail.com
8   E109     Neha         IT           None   neha@gmail.com
9   E110    roहित      Sales          70000   rohit@gmail.com

#### 10. Apply strip() to all the columns at once

In [37]:
df3 = df3.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)

# How it works:
    # apply() goes through every column
    # str.strip() is applied only on text (object) columns
    # numeric columns remain unchanged

In [38]:
df3

  Emp_ID     Name Department         Salary             Email
0   E101    aryan         IT          50000   aryan@gmail.com
1   E102     RIYA         HR          65000    RIYA@GMAIL.COM
2   E103    Rahul    Finance  not available    rahul123@gmail
3   E104   priya@         IT          72000  priya@@gmail.com
4   E105     AMAN      Sales          54000    aman.gmail.com
5   E106    sneha         HR          61000   sneha@gmail.com
6   E107  viKAs99    Finance          48000              None
7   E108   KARAN#  Marketing          85000   karan#gmail.com
8   E109     Neha         IT           None    neha@gmail.com
9   E110    roहित      Sales          70000   rohit@gmail.com

#### 11. Replace missing salary with 0

In [39]:
df3

  Emp_ID     Name Department         Salary             Email
0   E101    aryan         IT          50000   aryan@gmail.com
1   E102     RIYA         HR          65000    RIYA@GMAIL.COM
2   E103    Rahul    Finance  not available    rahul123@gmail
3   E104   priya@         IT          72000  priya@@gmail.com
4   E105     AMAN      Sales          54000    aman.gmail.com
5   E106    sneha         HR          61000   sneha@gmail.com
6   E107  viKAs99    Finance          48000              None
7   E108   KARAN#  Marketing          85000   karan#gmail.com
8   E109     Neha         IT           None    neha@gmail.com
9   E110    roहित      Sales          70000   rohit@gmail.com

In [46]:
df3['Salary'] = df3['Salary'].replace(['not available', 'None', None], 0)
df3

  Emp_ID     Name Department Salary             Email
0   E101    aryan         IT  50000   aryan@gmail.com
1   E102     RIYA         HR  65000    RIYA@GMAIL.COM
2   E103    Rahul    Finance      0    rahul123@gmail
3   E104   priya@         IT  72000  priya@@gmail.com
4   E105     AMAN      Sales  54000    aman.gmail.com
5   E106    sneha         HR  61000   sneha@gmail.com
6   E107  viKAs99    Finance  48000              None
7   E108   KARAN#  Marketing  85000   karan#gmail.com
8   E109     Neha         IT      0    neha@gmail.com
9   E110    roहित      Sales  70000   rohit@gmail.com

#### 12. Change all department names to uppercase

In [52]:
df3['Department'] = df3['Department'].str.upper()
df3

  Emp_ID     Name Department Salary             Email
0   E101    aryan         IT  50000   aryan@gmail.com
1   E102     RIYA         HR  65000    RIYA@GMAIL.COM
2   E103    Rahul    FINANCE      0    rahul123@gmail
3   E104   priya@         IT  72000  priya@@gmail.com
4   E105     AMAN      SALES  54000    aman.gmail.com
5   E106    sneha         HR  61000   sneha@gmail.com
6   E107  viKAs99    FINANCE  48000              None
7   E108   KARAN#  MARKETING  85000   karan#gmail.com
8   E109     Neha         IT      0    neha@gmail.com
9   E110    roहित      SALES  70000   rohit@gmail.com

#### 13. Convert all names to title case

In [54]:
df3['Name'] = df3['Name'].str.title()
df3

  Emp_ID     Name Department Salary             Email
0   E101    Aryan         IT  50000   aryan@gmail.com
1   E102     Riya         HR  65000    RIYA@GMAIL.COM
2   E103    Rahul    FINANCE      0    rahul123@gmail
3   E104   Priya@         IT  72000  priya@@gmail.com
4   E105     Aman      SALES  54000    aman.gmail.com
5   E106    Sneha         HR  61000   sneha@gmail.com
6   E107  Vikas99    FINANCE  48000              None
7   E108   Karan#  MARKETING  85000   karan#gmail.com
8   E109     Neha         IT      0    neha@gmail.com
9   E110    Roहित      SALES  70000   rohit@gmail.com

#### 14. Remove special characters and numbers from names

In [55]:
df3

  Emp_ID     Name Department Salary             Email
0   E101    Aryan         IT  50000   aryan@gmail.com
1   E102     Riya         HR  65000    RIYA@GMAIL.COM
2   E103    Rahul    FINANCE      0    rahul123@gmail
3   E104   Priya@         IT  72000  priya@@gmail.com
4   E105     Aman      SALES  54000    aman.gmail.com
5   E106    Sneha         HR  61000   sneha@gmail.com
6   E107  Vikas99    FINANCE  48000              None
7   E108   Karan#  MARKETING  85000   karan#gmail.com
8   E109     Neha         IT      0    neha@gmail.com
9   E110    Roहित      SALES  70000   rohit@gmail.com

In [56]:
df3['Name'] = df3['Name'].str.replace(r'[^a-zA-Z\u0900-\u097F ]', '', regex=True)
df3

# What this does:
    # a-zA-Z → keeps English letters
    # \u0900-\u097F → keeps Hindi characters
    # space " " → keeps spaces
    # ^ → means remove everything except these

  Emp_ID   Name Department Salary             Email
0   E101  Aryan         IT  50000   aryan@gmail.com
1   E102   Riya         HR  65000    RIYA@GMAIL.COM
2   E103  Rahul    FINANCE      0    rahul123@gmail
3   E104  Priya         IT  72000  priya@@gmail.com
4   E105   Aman      SALES  54000    aman.gmail.com
5   E106  Sneha         HR  61000   sneha@gmail.com
6   E107  Vikas    FINANCE  48000              None
7   E108  Karan  MARKETING  85000   karan#gmail.com
8   E109   Neha         IT      0    neha@gmail.com
9   E110  Roहित      SALES  70000   rohit@gmail.com

#### 15. Convert all emails to lowercase and correct the format of email

In [57]:
df3

  Emp_ID   Name Department Salary             Email
0   E101  Aryan         IT  50000   aryan@gmail.com
1   E102   Riya         HR  65000    RIYA@GMAIL.COM
2   E103  Rahul    FINANCE      0    rahul123@gmail
3   E104  Priya         IT  72000  priya@@gmail.com
4   E105   Aman      SALES  54000    aman.gmail.com
5   E106  Sneha         HR  61000   sneha@gmail.com
6   E107  Vikas    FINANCE  48000              None
7   E108  Karan  MARKETING  85000   karan#gmail.com
8   E109   Neha         IT      0    neha@gmail.com
9   E110  Roहित      SALES  70000   rohit@gmail.com

In [58]:
df3['Email'] = df3['Email'].str.lower()
df3

  Emp_ID   Name Department Salary             Email
0   E101  Aryan         IT  50000   aryan@gmail.com
1   E102   Riya         HR  65000    riya@gmail.com
2   E103  Rahul    FINANCE      0    rahul123@gmail
3   E104  Priya         IT  72000  priya@@gmail.com
4   E105   Aman      SALES  54000    aman.gmail.com
5   E106  Sneha         HR  61000   sneha@gmail.com
6   E107  Vikas    FINANCE  48000              None
7   E108  Karan  MARKETING  85000   karan#gmail.com
8   E109   Neha         IT      0    neha@gmail.com
9   E110  Roहित      SALES  70000   rohit@gmail.com

In [60]:
df3['Email'] = df3['Email'].str.replace('#', '@', regex=False)

df3['Email'] = df3['Email'].apply(
    lambda x: x + '.com'
    if pd.notnull(x) and '@' in x and not x.endswith('.com')
    else x
)

df3['Email'] = df3['Email'].apply(
    lambda x: x.replace('.gmail', '@gmail')
    if pd.notnull(x) and '.gmail' in x
    else x
)

df3['Email'] = df3['Email'].str.replace(r'@+', '@', regex=True)

df3

  Emp_ID   Name Department Salary               Email
0   E101  Aryan         IT  50000     aryan@gmail.com
1   E102   Riya         HR  65000      riya@gmail.com
2   E103  Rahul    FINANCE      0  rahul123@gmail.com
3   E104  Priya         IT  72000     priya@gmail.com
4   E105   Aman      SALES  54000      aman@gmail.com
5   E106  Sneha         HR  61000     sneha@gmail.com
6   E107  Vikas    FINANCE  48000                None
7   E108  Karan  MARKETING  85000     karan@gmail.com
8   E109   Neha         IT      0      neha@gmail.com
9   E110  Roहित      SALES  70000     rohit@gmail.com

### C. Filtering Questions

#### 16. Show employees from IT department

In [61]:
df3

  Emp_ID   Name Department Salary               Email
0   E101  Aryan         IT  50000     aryan@gmail.com
1   E102   Riya         HR  65000      riya@gmail.com
2   E103  Rahul    FINANCE      0  rahul123@gmail.com
3   E104  Priya         IT  72000     priya@gmail.com
4   E105   Aman      SALES  54000      aman@gmail.com
5   E106  Sneha         HR  61000     sneha@gmail.com
6   E107  Vikas    FINANCE  48000                None
7   E108  Karan  MARKETING  85000     karan@gmail.com
8   E109   Neha         IT      0      neha@gmail.com
9   E110  Roहित      SALES  70000     rohit@gmail.com

In [62]:
df3[ df3['Department'] == 'IT' ]

  Emp_ID   Name Department Salary            Email
0   E101  Aryan         IT  50000  aryan@gmail.com
3   E104  Priya         IT  72000  priya@gmail.com
8   E109   Neha         IT      0   neha@gmail.com

#### 17. Show employees whose salary is greater than 60000

In [69]:
# first we have to convert Salary column into integer from string
df3['Salary'] = pd.to_numeric(df3['Salary'], errors='coerce')
# errors='coerce' → converts invalid strings to NaN

In [70]:
df3[ df3['Salary'] > 60000 ]

  Emp_ID   Name Department  Salary            Email
1   E102   Riya         HR   65000   riya@gmail.com
3   E104  Priya         IT   72000  priya@gmail.com
5   E106  Sneha         HR   61000  sneha@gmail.com
7   E108  Karan  MARKETING   85000  karan@gmail.com
9   E110  Roहित      SALES   70000  rohit@gmail.com

#### 18. Show rows where email is missing

In [71]:
df3[ df3['Email'].isnull() ]

  Emp_ID   Name Department  Salary Email
6   E107  Vikas    FINANCE   48000  None

### D. Adding New Columns

#### 19. Create column Bonus 10% of salary

In [72]:
df3['Bonus'] = df3['Salary']*0.10
df3

  Emp_ID   Name Department  Salary               Email   Bonus
0   E101  Aryan         IT   50000     aryan@gmail.com  5000.0
1   E102   Riya         HR   65000      riya@gmail.com  6500.0
2   E103  Rahul    FINANCE       0  rahul123@gmail.com     0.0
3   E104  Priya         IT   72000     priya@gmail.com  7200.0
4   E105   Aman      SALES   54000      aman@gmail.com  5400.0
5   E106  Sneha         HR   61000     sneha@gmail.com  6100.0
6   E107  Vikas    FINANCE   48000                None  4800.0
7   E108  Karan  MARKETING   85000     karan@gmail.com  8500.0
8   E109   Neha         IT       0      neha@gmail.com     0.0
9   E110  Roहित      SALES   70000     rohit@gmail.com  7000.0

#### 20. Create column Tax 5% of salary

In [74]:
df3['Tax'] = df3['Salary']*0.05
df3

  Emp_ID   Name Department  Salary               Email   Bonus     Tax
0   E101  Aryan         IT   50000     aryan@gmail.com  5000.0  2500.0
1   E102   Riya         HR   65000      riya@gmail.com  6500.0  3250.0
2   E103  Rahul    FINANCE       0  rahul123@gmail.com     0.0     0.0
3   E104  Priya         IT   72000     priya@gmail.com  7200.0  3600.0
4   E105   Aman      SALES   54000      aman@gmail.com  5400.0  2700.0
5   E106  Sneha         HR   61000     sneha@gmail.com  6100.0  3050.0
6   E107  Vikas    FINANCE   48000                None  4800.0  2400.0
7   E108  Karan  MARKETING   85000     karan@gmail.com  8500.0  4250.0
8   E109   Neha         IT       0      neha@gmail.com     0.0     0.0
9   E110  Roहित      SALES   70000     rohit@gmail.com  7000.0  3500.0

#### 21. Create column Net_Salary Salary + Bonus - Tax

In [75]:
df3['Net_salary'] = df3['Salary'] + df3['Bonus'] - df3['Tax']
df3

,Emp_ID,Name,Department,Salary,Email,Bonus,Tax,Net_salary
0,E101,Aryan,IT,50000,aryan@gmail.com,5000.0,2500.0,52500.0
1,E102,Riya,HR,65000,riya@gmail.com,6500.0,3250.0,68250.0
2,E103,Rahul,FINANCE,0,rahul123@gmail.com,0.0,0.0,0.0
3,E104,Priya,IT,72000,priya@gmail.com,7200.0,3600.0,75600.0
4,E105,Aman,SALES,54000,aman@gmail.com,5400.0,2700.0,56700.0
5,E106,Sneha,HR,61000,sneha@gmail.com,6100.0,3050.0,64050.0
6,E107,Vikas,FINANCE,48000,None,4800.0,2400.0,50400.0
7,E108,Karan,MARKETING,85000,karan@gmail.com,8500.0,4250.0,89250.0
8,E109,Neha,IT,0,neha@gmail.com,0.0,0.0,0.0
9,E110,Roहित,SALES,70000,rohit@gmail.com,7000.0,3500.0,73500.0

### E. Data Type Handling

#### 22. Fill missing salary using average salary

In [76]:
df3

,Emp_ID,Name,Department,Salary,Email,Bonus,Tax,Net_salary
0,E101,Aryan,IT,50000,aryan@gmail.com,5000.0,2500.0,52500.0
1,E102,Riya,HR,65000,riya@gmail.com,6500.0,3250.0,68250.0
2,E103,Rahul,FINANCE,0,rahul123@gmail.com,0.0,0.0,0.0
3,E104,Priya,IT,72000,priya@gmail.com,7200.0,3600.0,75600.0
4,E105,Aman,SALES,54000,aman@gmail.com,5400.0,2700.0,56700.0
5,E106,Sneha,HR,61000,sneha@gmail.com,6100.0,3050.0,64050.0
6,E107,Vikas,FINANCE,48000,None,4800.0,2400.0,50400.0
7,E108,Karan,MARKETING,85000,karan@gmail.com,8500.0,4250.0,89250.0
8,E109,Neha,IT,0,neha@gmail.com,0.0,0.0,0.0
9,E110,Roहित,SALES,70000,rohit@gmail.com,7000.0,3500.0,73500.0

In [90]:
df3['Salary'] = pd.to_numeric(df3['Salary'], errors='coerce')
# NaN is coming because after pd.to_numeric(..., errors='coerce'), invalid values became NaN.
df3['Salary'] = df3['Salary'].fillna(0)

avg_salary = df3[df3['Salary'] != 0]['Salary'].mean()

df3['Salary'] = df3['Salary'].replace(0, int(avg_salary))

df3

,Emp_ID,Name,Department,Salary,Email,Bonus,Tax,Net_salary
0,E101,Aryan,IT,50000.0,aryan@gmail.com,5000.0,2500.0,52500.0
1,E102,Riya,HR,65000.0,riya@gmail.com,6500.0,3250.0,68250.0
2,E103,Rahul,FINANCE,63125.0,rahul123@gmail.com,0.0,0.0,0.0
3,E104,Priya,IT,72000.0,priya@gmail.com,7200.0,3600.0,75600.0
4,E105,Aman,SALES,54000.0,aman@gmail.com,5400.0,2700.0,56700.0
5,E106,Sneha,HR,61000.0,sneha@gmail.com,6100.0,3050.0,64050.0
6,E107,Vikas,FINANCE,48000.0,None,4800.0,2400.0,50400.0
7,E108,Karan,MARKETING,85000.0,karan@gmail.com,8500.0,4250.0,89250.0
8,E109,Neha,IT,63125.0,neha@gmail.com,0.0,0.0,0.0
9,E110,Roहित,SALES,70000.0,rohit@gmail.com,7000.0,3500.0,73500.0

##### Since our Salary column was in 'Object' Format hence we were not able to apply replace function and agg func on it directly
##### For that first we have converted our Salary Column into numeric Col.
##### Second since we have converted it into numeric now it will show NaN inplace of some invalid data
##### Now we have to fill that NaN with 0 by using fillna().
##### and then we will apply our method to replace 0 with the mean of the salary column

In [94]:
# int(df3[df3['Salary'] != 0]['Salary'].mean())

### F. Duplicate & Missing Data

#### 23. Check duplicate rows

In [96]:
df3[df3.duplicated()]

Empty DataFrame
Columns: [Emp_ID, Name, Department, Salary, Email, Bonus, Tax, Net_salary]
Index: []

In [98]:
# Count duplicate rows
print(df3.duplicated().sum())

0

### G. String Handling

#### 24. Extract username from email

In [99]:
df3['Email'].str.split("@")

0       [aryan, gmail.com]
1        [riya, gmail.com]
2    [rahul123, gmail.com]
3       [priya, gmail.com]
4        [aman, gmail.com]
5       [sneha, gmail.com]
6                     None
7       [karan, gmail.com]
8        [neha, gmail.com]
9       [rohit, gmail.com]
Name: Email, dtype: object

In [102]:
df3['Username'] = df3['Email'].str.split("@").str[0]
df3

,Emp_ID,Name,Department,Salary,Email,Bonus,Tax,Net_salary,Username
0,E101,Aryan,IT,50000.0,aryan@gmail.com,5000.0,2500.0,52500.0,aryan
1,E102,Riya,HR,65000.0,riya@gmail.com,6500.0,3250.0,68250.0,riya
2,E103,Rahul,FINANCE,63125.0,rahul123@gmail.com,0.0,0.0,0.0,rahul123
3,E104,Priya,IT,72000.0,priya@gmail.com,7200.0,3600.0,75600.0,priya
4,E105,Aman,SALES,54000.0,aman@gmail.com,5400.0,2700.0,56700.0,aman
5,E106,Sneha,HR,61000.0,sneha@gmail.com,6100.0,3050.0,64050.0,sneha
6,E107,Vikas,FINANCE,48000.0,None,4800.0,2400.0,50400.0,None
7,E108,Karan,MARKETING,85000.0,karan@gmail.com,8500.0,4250.0,89250.0,karan
8,E109,Neha,IT,63125.0,neha@gmail.com,0.0,0.0,0.0,neha
9,E110,Roहित,SALES,70000.0,rohit@gmail.com,7000.0,3500.0,73500.0,rohit

#### 25. Find length of each employee name

In [104]:
df3['Name_length'] = df3['Name'].str.len()
df3

,Emp_ID,Name,Department,Salary,Email,Bonus,Tax,Net_salary,Username,Name_length
0,E101,Aryan,IT,50000.0,aryan@gmail.com,5000.0,2500.0,52500.0,aryan,5
1,E102,Riya,HR,65000.0,riya@gmail.com,6500.0,3250.0,68250.0,riya,4
2,E103,Rahul,FINANCE,63125.0,rahul123@gmail.com,0.0,0.0,0.0,rahul123,5
3,E104,Priya,IT,72000.0,priya@gmail.com,7200.0,3600.0,75600.0,priya,5
4,E105,Aman,SALES,54000.0,aman@gmail.com,5400.0,2700.0,56700.0,aman,4
5,E106,Sneha,HR,61000.0,sneha@gmail.com,6100.0,3050.0,64050.0,sneha,5
6,E107,Vikas,FINANCE,48000.0,None,4800.0,2400.0,50400.0,None,5
7,E108,Karan,MARKETING,85000.0,karan@gmail.com,8500.0,4250.0,89250.0,karan,5
8,E109,Neha,IT,63125.0,neha@gmail.com,0.0,0.0,0.0,neha,4
9,E110,Roहित,SALES,70000.0,rohit@gmail.com,7000.0,3500.0,73500.0,rohit,5