# Sampling in Pandas

### Sampling means selecting some rows from a dataset.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name':['A','B','C','D','E','F'],
    'Marks':[85,90,78,92,88,95]
})

print(df)

  Name  Marks
0    A     85
1    B     90
2    C     78
3    D     92
4    E     88
5    F     95

### Type 1: Random Sampling by Number of Rows

In [7]:
df.sample( n = 3 ) # Take 3 random rows

  Name  Marks
2    C     78
1    B     90
0    A     85

### Type 2: Fraction Sampling

In [6]:
df.sample(frac = 0.5)  # Take 50% of rows

  Name  Marks
5    F     95
4    E     88
2    C     78

### Type 3: Sampling With Replacement

In [8]:
df.sample(n=4, replace=True)   # Same row can be selected multiple times.

  Name  Marks
0    A     85
2    C     78
4    E     88
0    A     85

### Type 4: Sampling Without Replacement (Default)

In [9]:
df.sample(n=3, replace=False)  # Each row appears once.

  Name  Marks
5    F     95
4    E     88
0    A     85

# Resampling in Pandas

### Resampling is used with date-time data to change frequency.

In [14]:
import pandas as pd

data = {
    'Sales':[100,120,150,130,200,190,200,206]
}

dates = pd.date_range('2026-01-01', periods=8)

dt = pd.DataFrame(data, index=dates)

dt

            Sales
2026-01-01    100
2026-01-02    120
2026-01-03    150
2026-01-04    130
2026-01-05    200
2026-01-06    190
2026-01-07    200
2026-01-08    206

### Downsampling - Converting high frequency data into lower frequency.

In [23]:
# Daily → Monthly
dt.resample('ME').sum()

            Sales
2026-01-31   1296

### Resampling Functions

#### 1. Sum

In [20]:
dt.resample('ME').sum()

            Sales
2026-01-31   1296

#### 2. Mean

In [24]:
dt.resample('ME').mean()

            Sales
2026-01-31  162.0

#### 3. Max & Min

In [26]:
# dt.resample('ME').max()
dt.resample('ME').min()

            Sales
2026-01-31    100

#### 4. Count

In [27]:
dt.resample('ME').count()

            Sales
2026-01-31      8

### Upsampling - Lower frequency → Higher frequency

In [28]:
df = pd.DataFrame(
    {'Sales':[100,200,300]},
    index=pd.to_datetime([
        '2025-01-01',
        '2025-02-01',
        '2025-03-01'
    ])
)
df

            Sales
2025-01-01    100
2025-02-01    200
2025-03-01    300

#### Create Daily Rows

In [30]:
df.resample('D').asfreq()

            Sales
2025-01-01  100.0
2025-01-02    NaN
2025-01-03    NaN
2025-01-04    NaN
2025-01-05    NaN
2025-01-06    NaN
2025-01-07    NaN
2025-01-08    NaN
2025-01-09    NaN
2025-01-10    NaN
2025-01-11    NaN
2025-01-12    NaN
2025-01-13    NaN
2025-01-14    NaN
2025-01-15    NaN
2025-01-16    NaN
2025-01-17    NaN
2025-01-18    NaN
2025-01-19    NaN
2025-01-20    NaN
2025-01-21    NaN
2025-01-22    NaN
2025-01-23    NaN
2025-01-24    NaN
2025-01-25    NaN
2025-01-26    NaN
2025-01-27    NaN
2025-01-28    NaN
2025-01-29    NaN
2025-01-30    NaN
2025-01-31    NaN
2025-02-01  200.0
2025-02-02    NaN
2025-02-03    NaN
2025-02-04    NaN
2025-02-05    NaN
2025-02-06    NaN
2025-02-07    NaN
2025-02-08    NaN
2025-02-09    NaN
2025-02-10    NaN
2025-02-11    NaN
2025-02-12    NaN
2025-02-13    NaN
2025-02-14    NaN
2025-02-15    NaN
2025-02-16    NaN
2025-02-17    NaN
2025-02-18    NaN
2025-02-19    NaN
2025-02-20    NaN
2025-02-21    NaN
2025-02-22    NaN
2025-02-23    NaN
2025-02-24    NaN
2025-02-25    NaN
2025-02-26    NaN
2025-02-27    NaN
2025-02-28    NaN
2025-03-01  300.0

#### Fill Missing Values After Upsampling
    Forward Fill

In [32]:
df.resample('D').ffill()

            Sales
2025-01-01    100
2025-01-02    100
2025-01-03    100
2025-01-04    100
2025-01-05    100
2025-01-06    100
2025-01-07    100
2025-01-08    100
2025-01-09    100
2025-01-10    100
2025-01-11    100
2025-01-12    100
2025-01-13    100
2025-01-14    100
2025-01-15    100
2025-01-16    100
2025-01-17    100
2025-01-18    100
2025-01-19    100
2025-01-20    100
2025-01-21    100
2025-01-22    100
2025-01-23    100
2025-01-24    100
2025-01-25    100
2025-01-26    100
2025-01-27    100
2025-01-28    100
2025-01-29    100
2025-01-30    100
2025-01-31    100
2025-02-01    200
2025-02-02    200
2025-02-03    200
2025-02-04    200
2025-02-05    200
2025-02-06    200
2025-02-07    200
2025-02-08    200
2025-02-09    200
2025-02-10    200
2025-02-11    200
2025-02-12    200
2025-02-13    200
2025-02-14    200
2025-02-15    200
2025-02-16    200
2025-02-17    200
2025-02-18    200
2025-02-19    200
2025-02-20    200
2025-02-21    200
2025-02-22    200
2025-02-23    200
2025-02-24    200
2025-02-25    200
2025-02-26    200
2025-02-27    200
2025-02-28    200
2025-03-01    300

#### Backward Fill

In [34]:
df.resample('D').bfill()

            Sales
2025-01-01    100
2025-01-02    200
2025-01-03    200
2025-01-04    200
2025-01-05    200
2025-01-06    200
2025-01-07    200
2025-01-08    200
2025-01-09    200
2025-01-10    200
2025-01-11    200
2025-01-12    200
2025-01-13    200
2025-01-14    200
2025-01-15    200
2025-01-16    200
2025-01-17    200
2025-01-18    200
2025-01-19    200
2025-01-20    200
2025-01-21    200
2025-01-22    200
2025-01-23    200
2025-01-24    200
2025-01-25    200
2025-01-26    200
2025-01-27    200
2025-01-28    200
2025-01-29    200
2025-01-30    200
2025-01-31    200
2025-02-01    200
2025-02-02    300
2025-02-03    300
2025-02-04    300
2025-02-05    300
2025-02-06    300
2025-02-07    300
2025-02-08    300
2025-02-09    300
2025-02-10    300
2025-02-11    300
2025-02-12    300
2025-02-13    300
2025-02-14    300
2025-02-15    300
2025-02-16    300
2025-02-17    300
2025-02-18    300
2025-02-19    300
2025-02-20    300
2025-02-21    300
2025-02-22    300
2025-02-23    300
2025-02-24    300
2025-02-25    300
2025-02-26    300
2025-02-27    300
2025-02-28    300
2025-03-01    300

#### Interpolation

In [37]:
df.resample('D').interpolate()
# interpolate() = basically checks how much is the difference between one row and the another in the original df
# then it divides that difference by the number of days between them and then adds that number to the last value

                 Sales
2025-01-01  100.000000
2025-01-02  103.225806
2025-01-03  106.451613
2025-01-04  109.677419
2025-01-05  112.903226
2025-01-06  116.129032
2025-01-07  119.354839
2025-01-08  122.580645
2025-01-09  125.806452
2025-01-10  129.032258
2025-01-11  132.258065
2025-01-12  135.483871
2025-01-13  138.709677
2025-01-14  141.935484
2025-01-15  145.161290
2025-01-16  148.387097
2025-01-17  151.612903
2025-01-18  154.838710
2025-01-19  158.064516
2025-01-20  161.290323
2025-01-21  164.516129
2025-01-22  167.741935
2025-01-23  170.967742
2025-01-24  174.193548
2025-01-25  177.419355
2025-01-26  180.645161
2025-01-27  183.870968
2025-01-28  187.096774
2025-01-29  190.322581
2025-01-30  193.548387
2025-01-31  196.774194
2025-02-01  200.000000
2025-02-02  203.571429
2025-02-03  207.142857
2025-02-04  210.714286
2025-02-05  214.285714
2025-02-06  217.857143
2025-02-07  221.428571
2025-02-08  225.000000
2025-02-09  228.571429
2025-02-10  232.142857
2025-02-11  235.714286
2025-02-12  239.285714
2025-02-13  242.857143
2025-02-14  246.428571
2025-02-15  250.000000
2025-02-16  253.571429
2025-02-17  257.142857
2025-02-18  260.714286
2025-02-19  264.285714
2025-02-20  267.857143
2025-02-21  271.428571
2025-02-22  275.000000
2025-02-23  278.571429
2025-02-24  282.142857
2025-02-25  285.714286
2025-02-26  289.285714
2025-02-27  292.857143
2025-02-28  296.428571
2025-03-01  300.000000