In [52]:
from IPython.display import HTML, display
display(HTML("""
<div style="
background:linear-gradient(135deg,#00A651,#00C853,#2196F3);
padding:20px;
border-radius:15px;
color:white;
font-size:42px;
font-weight:bold;
text-align:center;
font-family:Segoe UI;
margin:15px 0px;
box-shadow:0 4px 20px rgba(0,0,0,0.3);
">
Time Series Analysis
</div>
"""))

In [8]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Date': [
        '2026-01-01',
        '2026-01-02',
        None,
        'invalid_date'
    ],
    'mango': np.random.randint(1,101,size=4)
})

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

df

        Date  mango
0 2026-01-01     21
1 2026-01-02     27
2        NaT     36
3        NaT     76

In [9]:
df.isna()

    Date  mango
0  False  False
1  False  False
2   True  False
3   True  False

In [12]:
df['Date'].isna()

0    False
1    False
2     True
3     True
Name: Date, dtype: bool

In [13]:
df[df['Date'].isna()]

  Date  mango
2  NaT     36
3  NaT     76

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Sales": [100, 120, 150, 130, 180]
},
index=pd.date_range("2026-06-01", periods=5)
                 )

print(df)

            Sales
2026-06-01    100
2026-06-02    120
2026-06-03    150
2026-06-04    130
2026-06-05    180

In [18]:
df["Sales"].shift(1)

2026-06-01      NaN
2026-06-02    100.0
2026-06-03    120.0
2026-06-04    150.0
2026-06-05    130.0
Freq: D, Name: Sales, dtype: float64

In [19]:
df["Sales"].shift(-1)

2026-06-01    120.0
2026-06-02    150.0
2026-06-03    130.0
2026-06-04    180.0
2026-06-05      NaN
Freq: D, Name: Sales, dtype: float64

In [20]:
df["Sales"].shift(2)

2026-06-01      NaN
2026-06-02      NaN
2026-06-03    100.0
2026-06-04    120.0
2026-06-05    150.0
Freq: D, Name: Sales, dtype: float64

In [41]:

df = pd.DataFrame({
    "Sales": [100, 120, 150, 130, 180,200,150,210,230,190]
},
index=pd.date_range("2026-06-01", periods=10)
                 )

print(df)

            Sales
2026-06-01    100
2026-06-02    120
2026-06-03    150
2026-06-04    130
2026-06-05    180
2026-06-06    200
2026-06-07    150
2026-06-08    210
2026-06-09    230
2026-06-10    190

### Calculate the difference on current day sale  with previous day sale

In [23]:
df['Sales']

2026-06-01    100
2026-06-02    120
2026-06-03    150
2026-06-04    130
2026-06-05    180
2026-06-06    200
2026-06-07    150
2026-06-08    210
2026-06-09    230
2026-06-10    190
Freq: D, Name: Sales, dtype: int64

In [24]:
df['Sales'].shift(-1)

2026-06-01    120.0
2026-06-02    150.0
2026-06-03    130.0
2026-06-04    180.0
2026-06-05    200.0
2026-06-06    150.0
2026-06-07    210.0
2026-06-08    230.0
2026-06-09    190.0
2026-06-10      NaN
Freq: D, Name: Sales, dtype: float64

In [25]:
df['Sales']-df['Sales'].shift(-1)

2026-06-01   -20.0
2026-06-02   -30.0
2026-06-03    20.0
2026-06-04   -50.0
2026-06-05   -20.0
2026-06-06    50.0
2026-06-07   -60.0
2026-06-08   -20.0
2026-06-09    40.0
2026-06-10     NaN
Freq: D, Name: Sales, dtype: float64

In [26]:
df['Sales'].shift(-1)-df['Sales']

2026-06-01    20.0
2026-06-02    30.0
2026-06-03   -20.0
2026-06-04    50.0
2026-06-05    20.0
2026-06-06   -50.0
2026-06-07    60.0
2026-06-08    20.0
2026-06-09   -40.0
2026-06-10     NaN
Freq: D, Name: Sales, dtype: float64

In [27]:
df

            Sales
2026-06-01    100
2026-06-02    120
2026-06-03    150
2026-06-04    130
2026-06-05    180
2026-06-06    200
2026-06-07    150
2026-06-08    210
2026-06-09    230
2026-06-10    190

In [29]:
df['Sales'].shift(1)

2026-06-01      NaN
2026-06-02    100.0
2026-06-03    120.0
2026-06-04    150.0
2026-06-05    130.0
2026-06-06    180.0
2026-06-07    200.0
2026-06-08    150.0
2026-06-09    210.0
2026-06-10    230.0
Freq: D, Name: Sales, dtype: float64

In [30]:
df['Sales']

2026-06-01    100
2026-06-02    120
2026-06-03    150
2026-06-04    130
2026-06-05    180
2026-06-06    200
2026-06-07    150
2026-06-08    210
2026-06-09    230
2026-06-10    190
Freq: D, Name: Sales, dtype: int64

In [32]:
df['Sales'].shift(freq='D')

2026-06-02    100
2026-06-03    120
2026-06-04    150
2026-06-05    130
2026-06-06    180
2026-06-07    200
2026-06-08    150
2026-06-09    210
2026-06-10    230
2026-06-11    190
Freq: D, Name: Sales, dtype: int64

In [33]:
df['Sales'].shift(freq='2D')

2026-06-03    100
2026-06-04    120
2026-06-05    150
2026-06-06    130
2026-06-07    180
2026-06-08    200
2026-06-09    150
2026-06-10    210
2026-06-11    230
2026-06-12    190
Freq: D, Name: Sales, dtype: int64

In [34]:
df['Sales'].shift(freq='-1D')

2026-05-31    100
2026-06-01    120
2026-06-02    150
2026-06-03    130
2026-06-04    180
2026-06-05    200
2026-06-06    150
2026-06-07    210
2026-06-08    230
2026-06-09    190
Freq: D, Name: Sales, dtype: int64

In [35]:
df

            Sales
2026-06-01    100
2026-06-02    120
2026-06-03    150
2026-06-04    130
2026-06-05    180
2026-06-06    200
2026-06-07    150
2026-06-08    210
2026-06-09    230
2026-06-10    190

### Calculate DoD growth percentage

In [39]:
df["Sales"].shift(1)

2026-06-01      NaN
2026-06-02    100.0
2026-06-03    120.0
2026-06-04    150.0
2026-06-05    130.0
2026-06-06    180.0
2026-06-07    200.0
2026-06-08    150.0
2026-06-09    210.0
2026-06-10    230.0
Freq: D, Name: Sales, dtype: float64

In [42]:
df["Sales_Shift_1"]=df["Sales"].shift(1)

In [43]:
df["Growth_%"] = ((df["Sales"] - df["Sales"].shift(1))/ df["Sales"].shift(1)) * 100

In [44]:
df

            Sales  Sales_Shift_1   Growth_%
2026-06-01    100            NaN        NaN
2026-06-02    120          100.0  20.000000
2026-06-03    150          120.0  25.000000
2026-06-04    130          150.0 -13.333333
2026-06-05    180          130.0  38.461538
2026-06-06    200          180.0  11.111111
2026-06-07    150          200.0 -25.000000
2026-06-08    210          150.0  40.000000
2026-06-09    230          210.0   9.523810
2026-06-10    190          230.0 -17.391304

In [45]:
df["Sales"].shift(1)

2026-06-01      NaN
2026-06-02    100.0
2026-06-03    120.0
2026-06-04    150.0
2026-06-05    130.0
2026-06-06    180.0
2026-06-07    200.0
2026-06-08    150.0
2026-06-09    210.0
2026-06-10    230.0
Freq: D, Name: Sales, dtype: float64

In [46]:
df["Sales"].shift(1,fill_value=0)

2026-06-01      0
2026-06-02    100
2026-06-03    120
2026-06-04    150
2026-06-05    130
2026-06-06    180
2026-06-07    200
2026-06-08    150
2026-06-09    210
2026-06-10    230
Freq: D, Name: Sales, dtype: int64

In [47]:
df["Growth_%"] = ((df["Sales"] - df["Sales"].shift(1,fill_value=0))/ df["Sales"].shift(1,fill_value=0)) * 100

In [48]:
df

            Sales  Sales_Shift_1   Growth_%
2026-06-01    100            NaN        inf
2026-06-02    120          100.0  20.000000
2026-06-03    150          120.0  25.000000
2026-06-04    130          150.0 -13.333333
2026-06-05    180          130.0  38.461538
2026-06-06    200          180.0  11.111111
2026-06-07    150          200.0 -25.000000
2026-06-08    210          150.0  40.000000
2026-06-09    230          210.0   9.523810
2026-06-10    190          230.0 -17.391304

In [49]:
df["Sales_Shift_1"]=df["Sales"].shift(1,fill_value=0)

In [50]:
df

            Sales  Sales_Shift_1   Growth_%
2026-06-01    100              0        inf
2026-06-02    120            100  20.000000
2026-06-03    150            120  25.000000
2026-06-04    130            150 -13.333333
2026-06-05    180            130  38.461538
2026-06-06    200            180  11.111111
2026-06-07    150            200 -25.000000
2026-06-08    210            150  40.000000
2026-06-09    230            210   9.523810
2026-06-10    190            230 -17.391304

### Resampling

#### Resampling is a processs to convert the frequency

In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)

dates = pd.date_range(
    start='2026-01-01',
    periods=80,
    freq='D'
)

sales = np.random.randint(
    100,
    1000,
    size=80
)

df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

df.set_index('Date', inplace=True)

df

            Sales
Date
2026-01-01    202
2026-01-02    535
2026-01-03    960
2026-01-04    370
2026-01-05    206
...           ...
2026-03-17    608
2026-03-18    875
2026-03-19    134
2026-03-20    305
2026-03-21    180

[80 rows x 1 columns]

In [5]:
df.resample('M')

In [6]:
list(df.resample('M'))

[(Timestamp('2026-01-31 00:00:00'),
              Sales
  Date
  2026-01-01    202
  2026-01-02    535
  2026-01-03    960
  2026-01-04    370
  2026-01-05    206
  2026-01-06    171
  2026-01-07    800
  2026-01-08    120
  2026-01-09    714
  2026-01-10    221
  2026-01-11    566
  2026-01-12    314
  2026-01-13    430
  2026-01-14    558
  2026-01-15    187
  2026-01-16    472
  2026-01-17    199
  2026-01-18    971
  2026-01-19    763
  2026-01-20    230
  2026-01-21    761
  2026-01-22    408
  2026-01-23    869
  2026-01-24    443
  2026-01-25    591
  2026-01-26    513
  2026-01-27    905
  2026-01-28    485
  2026-01-29    291
  2026-01-30    376
  2026-01-31    260),
 (Timestamp('2026-02-28 00:00:00'),
              Sales
  Date
  2026-02-01    559
  2026-02-02    413
  2026-02-03    121
  2026-02-04    352
  2026-02-05    847
  2026-02-06    956
  2026-02-07    660
  2026-02-08    574
  2026-02-09    158
  2026-02-10    610
  2026-02-11    781
  2026-02-12    575
  2026-02-13    799
  2026-02-14    882
  2026-02-15    289
  2026-02-16    786
  2026-02-17    662
  2026-02-18    975
  2026-02-19    666
  2026-02-20    343
  2026-02-21    931
  2026-02-22    604
  2026-02-23    230
  2026-02-24    584
  2026-02-25    918
  2026-02-26    746
  2026-02-27    120
  2026-02-28    940),
 (Timestamp('2026-03-31 00:00:00'),
              Sales
  Date
  2026-03-01    266
  2026-03-02    373
  2026-03-03    487
  2026-03-04    700
  2026-03-05    415
  2026-03-06    113
  2026-03-07    341
  2026-03-08    876
  2026-03-09    445
  2026-03-10    664
  2026-03-11    997
  2026-03-12    439
  2026-03-13    191
  2026-03-14    466
  2026-03-15    554
  2026-03-16    527
  2026-03-17    608
  2026-03-18    875
  2026-03-19    134
  2026-03-20    305
  2026-03-21    180)]

In [8]:
df.resample('M').sum()   # day wise data ----> monthly sum    high frequency data ----> low frequency data  = downsampling

            Sales
Date
2026-01-31  14891
2026-02-28  17081
2026-03-31   9956

In [9]:
df.resample('W').sum()

            Sales
Date
2026-01-04   2067
2026-01-11   2798
2026-01-18   3131
2026-01-25   4065
2026-02-01   3389
2026-02-08   3923
2026-02-15   4094
2026-02-22   4967
2026-03-01   3804
2026-03-08   3305
2026-03-15   3756
2026-03-22   2629

In [10]:
df.resample('Y').sum()

            Sales
Date
2026-12-31  41928

In [11]:
df

            Sales
Date
2026-01-01    202
2026-01-02    535
2026-01-03    960
2026-01-04    370
2026-01-05    206
...           ...
2026-03-17    608
2026-03-18    875
2026-03-19    134
2026-03-20    305
2026-03-21    180

[80 rows x 1 columns]

In [15]:
df.resample('W').sum()

            Sales
Date
2026-01-04   2067
2026-01-11   2798
2026-01-18   3131
2026-01-25   4065
2026-02-01   3389
2026-02-08   3923
2026-02-15   4094
2026-02-22   4967
2026-03-01   3804
2026-03-08   3305
2026-03-15   3756
2026-03-22   2629

In [16]:
df.resample('7D').sum()

            Sales
Date
2026-01-01   3244
2026-01-08   2923
2026-01-15   3583
2026-01-22   4214
2026-01-29   2372
2026-02-05   4586
2026-02-12   4968
2026-02-19   4276
2026-02-26   3632
2026-03-05   3851
2026-03-12   3660
2026-03-19    619

In [17]:
df.resample('3D').sum()

            Sales
Date
2026-01-01   1697
2026-01-04    747
2026-01-07   1634
2026-01-10   1101
2026-01-13   1175
2026-01-16   1642
2026-01-19   1754
2026-01-22   1720
2026-01-25   2009
2026-01-28   1152
2026-01-31   1232
2026-02-03   1320
2026-02-06   2190
2026-02-09   1549
2026-02-12   2256
2026-02-15   1737
2026-02-18   1984
2026-02-21   1765
2026-02-24   2248
2026-02-27   1326
2026-03-02   1560
2026-03-05    869
2026-03-08   1985
2026-03-11   1627
2026-03-14   1547
2026-03-17   1617
2026-03-20    485

In [19]:

df = pd.DataFrame({
    'Sales':[10000, 15000, 12000, 18000]
},
index=pd.to_datetime([
    '2025-01-01',
    '2025-02-01',
    '2025-03-01',
    '2025-04-01'
]))

df

            Sales
2025-01-01  10000
2025-02-01  15000
2025-03-01  12000
2025-04-01  18000

In [21]:
list(df.resample('D'))

[(Timestamp('2025-01-01 00:00:00'),
              Sales
  2025-01-01  10000),
 (Timestamp('2025-01-02 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-03 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-04 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-05 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-06 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-07 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-08 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-09 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-10 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-11 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-12 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-13 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-14 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-15 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-16 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-17 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-18 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-19 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-20 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-21 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-22 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-23 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-24 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-25 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-26 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-27 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-28 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-29 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-30 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-01-31 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-01 00:00:00'),
              Sales
  2025-02-01  15000),
 (Timestamp('2025-02-02 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-03 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-04 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-05 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-06 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-07 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-08 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-09 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-10 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-11 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-12 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-13 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-14 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-15 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-16 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-17 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-18 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-19 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-20 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-21 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-22 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-23 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-24 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-25 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-26 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-27 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-02-28 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-01 00:00:00'),
              Sales
  2025-03-01  12000),
 (Timestamp('2025-03-02 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-03 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-04 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-05 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-06 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-07 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-08 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-09 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-10 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-11 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-12 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-13 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-14 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-15 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-16 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-17 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-18 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-19 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-20 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-21 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-22 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-23 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-24 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-25 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-26 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-27 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-28 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-29 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-30 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-03-31 00:00:00'),
  Empty DataFrame
  Columns: [Sales]
  Index: []),
 (Timestamp('2025-04-01 00:00:00'),
              Sales
  2025-04-01  18000)]

In [22]:
df.resample('D').sum()

            Sales
2025-01-01  10000
2025-01-02      0
2025-01-03      0
2025-01-04      0
2025-01-05      0
...           ...
2025-03-28      0
2025-03-29      0
2025-03-30      0
2025-03-31      0
2025-04-01  18000

[91 rows x 1 columns]

In [23]:
df.resample('D').ffill()

            Sales
2025-01-01  10000
2025-01-02  10000
2025-01-03  10000
2025-01-04  10000
2025-01-05  10000
...           ...
2025-03-28  12000
2025-03-29  12000
2025-03-30  12000
2025-03-31  12000
2025-04-01  18000

[91 rows x 1 columns]

In [25]:
df

            Sales
2025-01-01  10000
2025-02-01  15000
2025-03-01  12000
2025-04-01  18000

In [27]:
d=df.resample('D')

In [30]:
pd.DataFrame(d).head(34)

            0                                           1
0  2025-01-01                     Sales
2025-01-01  10000
1  2025-01-02  Empty DataFrame
Columns: [Sales]
Index: []
2  2025-01-03  Empty DataFrame
Columns: [Sales]
Index: []
3  2025-01-04  Empty DataFrame
Columns: [Sales]
Index: []
4  2025-01-05  Empty DataFrame
Columns: [Sales]
Index: []
5  2025-01-06  Empty DataFrame
Columns: [Sales]
Index: []
6  2025-01-07  Empty DataFrame
Columns: [Sales]
Index: []
7  2025-01-08  Empty DataFrame
Columns: [Sales]
Index: []
8  2025-01-09  Empty DataFrame
Columns: [Sales]
Index: []
9  2025-01-10  Empty DataFrame
Columns: [Sales]
Index: []
10 2025-01-11  Empty DataFrame
Columns: [Sales]
Index: []
11 2025-01-12  Empty DataFrame
Columns: [Sales]
Index: []
12 2025-01-13  Empty DataFrame
Columns: [Sales]
Index: []
13 2025-01-14  Empty DataFrame
Columns: [Sales]
Index: []
14 2025-01-15  Empty DataFrame
Columns: [Sales]
Index: []
15 2025-01-16  Empty DataFrame
Columns: [Sales]
Index: []
16 2025-01-17  Empty DataFrame
Columns: [Sales]
Index: []
17 2025-01-18  Empty DataFrame
Columns: [Sales]
Index: []
18 2025-01-19  Empty DataFrame
Columns: [Sales]
Index: []
19 2025-01-20  Empty DataFrame
Columns: [Sales]
Index: []
20 2025-01-21  Empty DataFrame
Columns: [Sales]
Index: []
21 2025-01-22  Empty DataFrame
Columns: [Sales]
Index: []
22 2025-01-23  Empty DataFrame
Columns: [Sales]
Index: []
23 2025-01-24  Empty DataFrame
Columns: [Sales]
Index: []
24 2025-01-25  Empty DataFrame
Columns: [Sales]
Index: []
25 2025-01-26  Empty DataFrame
Columns: [Sales]
Index: []
26 2025-01-27  Empty DataFrame
Columns: [Sales]
Index: []
27 2025-01-28  Empty DataFrame
Columns: [Sales]
Index: []
28 2025-01-29  Empty DataFrame
Columns: [Sales]
Index: []
29 2025-01-30  Empty DataFrame
Columns: [Sales]
Index: []
30 2025-01-31  Empty DataFrame
Columns: [Sales]
Index: []
31 2025-02-01                     Sales
2025-02-01  15000
32 2025-02-02  Empty DataFrame
Columns: [Sales]
Index: []
33 2025-02-03  Empty DataFrame
Columns: [Sales]
Index: []

In [31]:
df

            Sales
2025-01-01  10000
2025-02-01  15000
2025-03-01  12000
2025-04-01  18000

In [32]:
df.resample('D').ffill().head(34)

            Sales
2025-01-01  10000
2025-01-02  10000
2025-01-03  10000
2025-01-04  10000
2025-01-05  10000
2025-01-06  10000
2025-01-07  10000
2025-01-08  10000
2025-01-09  10000
2025-01-10  10000
2025-01-11  10000
2025-01-12  10000
2025-01-13  10000
2025-01-14  10000
2025-01-15  10000
2025-01-16  10000
2025-01-17  10000
2025-01-18  10000
2025-01-19  10000
2025-01-20  10000
2025-01-21  10000
2025-01-22  10000
2025-01-23  10000
2025-01-24  10000
2025-01-25  10000
2025-01-26  10000
2025-01-27  10000
2025-01-28  10000
2025-01-29  10000
2025-01-30  10000
2025-01-31  10000
2025-02-01  15000
2025-02-02  15000
2025-02-03  15000

In [33]:
df.resample('D').bfill().head(34)

            Sales
2025-01-01  10000
2025-01-02  15000
2025-01-03  15000
2025-01-04  15000
2025-01-05  15000
2025-01-06  15000
2025-01-07  15000
2025-01-08  15000
2025-01-09  15000
2025-01-10  15000
2025-01-11  15000
2025-01-12  15000
2025-01-13  15000
2025-01-14  15000
2025-01-15  15000
2025-01-16  15000
2025-01-17  15000
2025-01-18  15000
2025-01-19  15000
2025-01-20  15000
2025-01-21  15000
2025-01-22  15000
2025-01-23  15000
2025-01-24  15000
2025-01-25  15000
2025-01-26  15000
2025-01-27  15000
2025-01-28  15000
2025-01-29  15000
2025-01-30  15000
2025-01-31  15000
2025-02-01  15000
2025-02-02  12000
2025-02-03  12000

In [34]:
df.resample('D').bfill()

            Sales
2025-01-01  10000
2025-01-02  15000
2025-01-03  15000
2025-01-04  15000
2025-01-05  15000
...           ...
2025-03-28  18000
2025-03-29  18000
2025-03-30  18000
2025-03-31  18000
2025-04-01  18000

[91 rows x 1 columns]

In [35]:
df.resample('D').interpolate()

                   Sales
2025-01-01  10000.000000
2025-01-02  10161.290323
2025-01-03  10322.580645
2025-01-04  10483.870968
2025-01-05  10645.161290
...                  ...
2025-03-28  17225.806452
2025-03-29  17419.354839
2025-03-30  17612.903226
2025-03-31  17806.451613
2025-04-01  18000.000000

[91 rows x 1 columns]

In [36]:
import pandas as pd
import numpy as np

np.random.seed(42)

dates = pd.date_range(
    start='2026-01-01',
    periods=80,
    freq='D'
)

sales = np.random.randint(
    100,
    1000,
    size=80
)

df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

df.set_index('Date', inplace=True)

df

            Sales
Date
2026-01-01    202
2026-01-02    535
2026-01-03    960
2026-01-04    370
2026-01-05    206
...           ...
2026-03-17    608
2026-03-18    875
2026-03-19    134
2026-03-20    305
2026-03-21    180

[80 rows x 1 columns]

In [37]:
df.resample('M').agg(['sum','max','min','mean'])

            Sales
              sum  max  min        mean
Date
2026-01-31  14891  971  120  480.354839
2026-02-28  17081  975  120  610.035714
2026-03-31   9956  997  113  474.095238

In [ ]:
asfreq()