In [1]:
pip install tmdbsimple

Defaulting to user installation because normal site-packages is not writeable
Collecting tmdbsimple
  Downloading tmdbsimple-2.9.8-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: requests in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from tmdbsimple) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (2025.10.5)
Downloading tmdbsimple-2.9.8-py3-none-any.whl (40 kB)
Installing collected packages: tmdbsimple
Successfully installed tmdbsimple-2.9.8
Note: you may need to restart the kernel to use updated packages.

In [4]:
import tmdbsimple as tmdb
tmdb.API_KEY = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNTYxMzdjZmE5YmNhMjQzNTAzYmQ4MDQ4NzhhOGU4NiIsIm5iZiI6MTc4NzA2NDYzNS4zNDgsInN1YiI6IjZhODQ3MTNiNmUwYjI5OGZjMDU5NWQ4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.qqY8hbOuCJtONtfCXNCs1FGLXP9EWpcUk6IVrqapfmY'

In [2]:
import requests
tmdb.REQUESTS_SESSION = requests.Session()

In [5]:
tmdb.USE_BEARER_AUTH = True

In [6]:
movie = tmdb.Movies(603)
response = movie.info()

In [7]:
print(movie.title)
print(movie.release_date)
print(movie.vote_average)

The Matrix
1999-03-31
8.255

In [8]:
print(response)

{'adult': False, 'backdrop_path': '/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg', 'belongs_to_collection': {'id': 2344, 'name': 'The Matrix Collection', 'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg', 'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'}, 'budget': 63000000, 'genres': [{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}], 'homepage': 'http://www.warnerbros.com/matrix', 'id': 603, 'imdb_id': 'tt0133093', 'origin_country': ['US'], 'original_language': 'en', 'original_title': 'The Matrix', 'overview': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.', 'popularity': 45.7419, 'poster_path': '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg', 'production_companies': [{'id': 79, 'logo_path': '/at4uYdwAAgNRKhZuuFX8ShKSybw.png', 'name': 'Village Roadshow Pictures', 'origin_country': 'US'}, {'id': 372, 'logo_path': None, 'name': 'Groucho II Film Partnership', 'origin_country': ''}, {'id': 1885, 'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png', 'name': 'Silver Pictures', 'origin_country': 'US'}, {'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png', 'name': 'Warner Bros. Pictures', 'origin_country': 'US'}], 'production_countries': [{'iso_3166_1': 'US', 'name': 'United States of America'}], 'release_date': '1999-03-31', 'revenue': 463517383, 'runtime': 136, 'softcore': False, 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}], 'status': 'Released', 'tagline': 'Believe the unbelievable.', 'title': 'The Matrix', 'video': False, 'vote_average': 8.255, 'vote_count': 28505}

In [9]:
response.keys()

dict_keys(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'origin_country', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'softcore', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count'])

In [11]:
import pandas as pd

df = pd.DataFrame([response])

df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg,"{'id': 2344, 'name': 'The Matrix Collection', ...",63000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.warnerbros.com/matrix,603,tt0133093,[US],en,...,463517383,136,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Believe the unbelievable.,The Matrix,False,8.255,28505

In [14]:
df['belongs_to_collection'][0].keys()

dict_keys(['id', 'name', 'poster_path', 'backdrop_path'])

In [15]:
df.shape

(1, 27)

In [16]:
df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [17]:
df.dtypes

adult                       bool
backdrop_path             object
belongs_to_collection     object
budget                     int64
genres                    object
homepage                  object
id                         int64
imdb_id                   object
origin_country            object
original_language         object
original_title            object
overview                  object
popularity               float64
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                    int64
runtime                    int64
softcore                    bool
spoken_languages          object
status                    object
tagline                   object
title                     object
video                       bool
vote_average             float64
vote_count                 int64
dtype: object

In [18]:
df.select_dtypes(include='object').columns

Index(['backdrop_path', 'belongs_to_collection', 'genres', 'homepage',
       'imdb_id', 'origin_country', 'original_language', 'original_title',
       'overview', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'spoken_languages', 'status',
       'tagline', 'title'],
      dtype='object')

In [19]:
for col in df.columns:
    value = df[col].iloc[0]
    
    if isinstance(value, (dict, list)):
        print(col, type(value))

belongs_to_collection <class 'dict'>
genres <class 'list'>
origin_country <class 'list'>
production_companies <class 'list'>
production_countries <class 'list'>
spoken_languages <class 'list'>

In [20]:
for col in ['belongs_to_collection', 'genres', 'origin_country',
            'production_companies', 'production_countries', 'spoken_languages']:
    print(f"\n{col}:")
    print(df[col].iloc[0])

belongs_to_collection:
{'id': 2344, 'name': 'The Matrix Collection', 'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg', 'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'}

genres:
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}]

origin_country:
['US']

production_companies:
[{'id': 79, 'logo_path': '/at4uYdwAAgNRKhZuuFX8ShKSybw.png', 'name': 'Village Roadshow Pictures', 'origin_country': 'US'}, {'id': 372, 'logo_path': None, 'name': 'Groucho II Film Partnership', 'origin_country': ''}, {'id': 1885, 'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png', 'name': 'Silver Pictures', 'origin_country': 'US'}, {'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png', 'name': 'Warner Bros. Pictures', 'origin_country': 'US'}]

production_countries:
[{'iso_3166_1': 'US', 'name': 'United States of America'}]

spoken_languages:
[{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}]

In [21]:
collection = pd.json_normalize(df['belongs_to_collection'])
df = pd.concat([df.drop(columns='belongs_to_collection'), collection], axis=1)

In [22]:
df.columns

Index(['adult', 'backdrop_path', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'origin_country', 'original_language', 'original_title',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'softcore', 'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'id', 'name', 'poster_path',
       'backdrop_path'],
      dtype='object')

In [23]:
# genres
df['genres'] = df['genres'].apply(
    lambda x: ', '.join([i['name'] for i in x]) if isinstance(x, list) else None
)

# origin_country
df['origin_country'] = df['origin_country'].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else None
)

# production_companies
df['production_companies'] = df['production_companies'].apply(
    lambda x: ', '.join([i['name'] for i in x]) if isinstance(x, list) else None
)

# production_countries
df['production_countries'] = df['production_countries'].apply(
    lambda x: ', '.join([i['name'] for i in x]) if isinstance(x, list) else None
)

# spoken_languages
df['spoken_languages'] = df['spoken_languages'].apply(
    lambda x: ', '.join([i['english_name'] for i in x]) if isinstance(x, list) else None
)

In [24]:
for col in df.columns:
    value = df[col].iloc[0]
    
    if isinstance(value, (dict, list)):
        print(col, type(value))

In [25]:
df.head()

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,...,status,tagline,title,video,vote_average,vote_count,id,name,poster_path,backdrop_path
0,False,/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg,63000000,"Action, Science Fiction",http://www.warnerbros.com/matrix,603,tt0133093,US,en,The Matrix,...,Released,Believe the unbelievable.,The Matrix,False,8.255,28505,2344,The Matrix Collection,/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg,/bRm2DEgUiYciDw3myHuYFInD7la.jpg

## Want to get data of multiple movies

### Getting multiple movie IDs

In [26]:
import tmdbsimple as tmdb

tmdb.API_KEY = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNTYxMzdjZmE5YmNhMjQzNTAzYmQ4MDQ4NzhhOGU4NiIsIm5iZiI6MTc4NzA2NDYzNS4zNDgsInN1YiI6IjZhODQ3MTNiNmUwYjI5OGZjMDU5NWQ4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.qqY8hbOuCJtONtfCXNCs1FGLXP9EWpcUk6IVrqapfmY'
tmdb.USE_BEARER_AUTH = True

discover = tmdb.Discover()
response = discover.movie(page=1)

movies = response['results']

len(movies)

20

### Looking at the data

In [27]:
movies[0]

{'adult': False,
 'backdrop_path': '/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg',
 'genre_ids': [878, 28, 12],
 'id': 969681,
 'title': 'Spider-Man: Brand New Day',
 'original_language': 'en',
 'original_title': 'Spider-Man: Brand New Day',
 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
 'popularity': 1875.3748,
 'poster_path': '/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
 'release_date': '2026-07-29',
 'softcore': False,
 'video': False,
 'vote_average': 7.885,
 'vote_count': 1953}

In [28]:
movie.info()

{'adult': False,
 'backdrop_path': '/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg',
 'belongs_to_collection': {'id': 2344,
  'name': 'The Matrix Collection',
  'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg',
  'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'},
 'budget': 63000000,
 'genres': [{'id': 28, 'name': 'Action'},
  {'id': 878, 'name': 'Science Fiction'}],
 'homepage': 'http://www.warnerbros.com/matrix',
 'id': 603,
 'imdb_id': 'tt0133093',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'The Matrix',
 'overview': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
 'popularity': 45.7419,
 'poster_path': '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
 'production_companies': [{'id': 79,
   'logo_path': '/at4uYdwAAgNRKhZuuFX8ShKSybw.png',
   'name': 'Village Roadshow Pictures',
   'origin_country': 'US'},
  {'id': 372,
   'logo_path': None,
   'name': 'Groucho II Film Partnership',
   'origin_country': ''},
  {'id': 1885,
   'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png',
   'name': 'Silver Pictures',
   'origin_country': 'US'},
  {'id': 174,
   'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png',
   'name': 'Warner Bros. Pictures',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '1999-03-31',
 'revenue': 463517383,
 'runtime': 136,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Believe the unbelievable.',
 'title': 'The Matrix',
 'video': False,
 'vote_average': 8.255,
 'vote_count': 28505}

### Extracting movie IDs

In [29]:
movie_ids = [movie['id'] for movie in movies]

movie_ids

[969681,
 1368337,
 634649,
 1084244,
 1323244,
 1375646,
 1315772,
 1284041,
 1339713,
 1101383,
 1284465,
 1108427,
 1275779,
 1212763,
 1081003,
 82023,
 1307118,
 1083381,
 1003596,
 315635]

### Getting detailed information for every movie

In [30]:
all_movies = []

for movie_id in movie_ids:
    movie = tmdb.Movies(movie_id)
    data = movie.info()
    all_movies.append(data)

In [31]:
len(all_movies)

20

In [32]:
all_movies[0]

{'adult': False,
 'backdrop_path': '/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg',
 'belongs_to_collection': {'id': 531241,
  'name': 'Spider-Man (MCU) Collection',
  'poster_path': '/yeba3Y820OjApZO9aJevDsNeMEd.jpg',
  'backdrop_path': '/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg'},
 'budget': 225000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://spidermanbrandnewday.movie',
 'id': 969681,
 'imdb_id': 'tt22084616',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'Spider-Man: Brand New Day',
 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
 'popularity': 1875.3748,
 'poster_path': '/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'},
  {'id': 5,
   'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
   'name': 'Columbia Pictures',
   'origin_country': 'US'},
  {'id': 84041,
   'logo_path': '/nw4kyc29QRpNtFbdsBHkRSFavvt.png',
   'name': 'Pascal Pictures',
   'origin_country': 'US'},
  {'id': 22213,
   'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
   'name': 'TSG Entertainment',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2026-07-29',
 'revenue': 2039929225,
 'runtime': 145,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'A brand new day starts now.',
 'title': 'Spider-Man: Brand New Day',
 'video': False,
 'vote_average': 7.885,
 'vote_count': 1951}

### Creating the DataFrame

In [33]:
df = pd.DataFrame(all_movies)
df.head(2)

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg,"{'id': 531241, 'name': 'Spider-Man (MCU) Colle...",225000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://spidermanbrandnewday.movie,969681,tt22084616,[US],en,...,2039929225,145,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A brand new day starts now.,Spider-Man: Brand New Day,False,7.885,1951
1,False,/r57L2UBLPKcHdZQYg8tagv9XqK2.jpg,None,250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.universalpictures.com/movies/the-o...,1368337,tt33764258,"[GB, US]",en,...,1294477255,173,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Defy the gods.,The Odyssey,False,8.000,2969

In [36]:
df.shape  # Data of 20 movies

(20, 27)

In [37]:
df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [38]:
nested_cols = []

for col in df.columns:
    if df[col].apply(lambda x: isinstance(x, (dict, list))).any():
        nested_cols.append(col)

nested_cols

['belongs_to_collection',
 'genres',
 'origin_country',
 'production_companies',
 'production_countries',
 'spoken_languages']

In [39]:
collection = pd.json_normalize(df['belongs_to_collection'])

collection = collection.rename(columns={
    'id': 'collection_id',
    'name': 'collection_name',
    'poster_path': 'collection_poster_path',
    'backdrop_path': 'collection_backdrop_path'
})

df = pd.concat(
    [df.drop(columns='belongs_to_collection'), collection],
    axis=1
)

In [40]:
df[['id', 'title', 'collection_id', 'collection_name']].head()

,id,title,collection_id,collection_name
0,969681,Spider-Man: Brand New Day,531241.0,Spider-Man (MCU) Collection
1,1368337,The Odyssey,NaN,NaN
2,634649,Spider-Man: No Way Home,531241.0,Spider-Man (MCU) Collection
3,1084244,Toy Story 5,10194.0,Toy Story Collection
4,1323244,Rage of Stars,NaN,NaN

In [ ]:
df['genres'] = df['genres'].apply(
    lambda x: ', '.join(i['name'] for i in x) if isinstance(x, list) else None
)