In [1]:
pip install tmdbsimple

Defaulting to user installation because normal site-packages is not writeable
Collecting tmdbsimple
  Downloading tmdbsimple-2.9.8-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: requests in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from tmdbsimple) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Aditya raj\AppData\Roaming\Python\Python312\site-packages (from requests->tmdbsimple) (2025.10.5)
Downloading tmdbsimple-2.9.8-py3-none-any.whl (40 kB)
Installing collected packages: tmdbsimple
Successfully installed tmdbsimple-2.9.8
Note: you may need to restart the kernel to use updated packages.

In [17]:
import tmdbsimple as tmdb
tmdb.API_KEY = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNTYxMzdjZmE5YmNhMjQzNTAzYmQ4MDQ4NzhhOGU4NiIsIm5iZiI6MTc4NzA2NDYzNS4zNDgsInN1YiI6IjZhODQ3MTNiNmUwYjI5OGZjMDU5NWQ4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.qqY8hbOuCJtONtfCXNCs1FGLXP9EWpcUk6IVrqapfmY'

In [18]:
import requests
tmdb.REQUESTS_SESSION = requests.Session()

In [19]:
tmdb.USE_BEARER_AUTH = True

In [20]:
movie = tmdb.Movies(603)
response = movie.info()

In [21]:
print(movie.title)
print(movie.release_date)
print(movie.vote_average)

The Matrix
1999-03-31
8.256

In [22]:
print(response)

{'adult': False, 'backdrop_path': '/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg', 'belongs_to_collection': {'id': 2344, 'name': 'The Matrix Collection', 'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg', 'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'}, 'budget': 63000000, 'genres': [{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}], 'homepage': 'http://www.warnerbros.com/matrix', 'id': 603, 'imdb_id': 'tt0133093', 'origin_country': ['US'], 'original_language': 'en', 'original_title': 'The Matrix', 'overview': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.', 'popularity': 42.1455, 'poster_path': '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg', 'production_companies': [{'id': 79, 'logo_path': '/at4uYdwAAgNRKhZuuFX8ShKSybw.png', 'name': 'Village Roadshow Pictures', 'origin_country': 'US'}, {'id': 372, 'logo_path': None, 'name': 'Groucho II Film Partnership', 'origin_country': ''}, {'id': 1885, 'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png', 'name': 'Silver Pictures', 'origin_country': 'US'}, {'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png', 'name': 'Warner Bros. Pictures', 'origin_country': 'US'}], 'production_countries': [{'iso_3166_1': 'US', 'name': 'United States of America'}], 'release_date': '1999-03-31', 'revenue': 463517383, 'runtime': 136, 'softcore': False, 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}], 'status': 'Released', 'tagline': 'Believe the unbelievable.', 'title': 'The Matrix', 'video': False, 'vote_average': 8.256, 'vote_count': 28551}

In [23]:
response.keys()

dict_keys(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'origin_country', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'softcore', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count'])

In [24]:
import pandas as pd

df = pd.DataFrame([response])

df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg,"{'id': 2344, 'name': 'The Matrix Collection', ...",63000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.warnerbros.com/matrix,603,tt0133093,[US],en,...,463517383,136,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Believe the unbelievable.,The Matrix,False,8.256,28551

In [25]:
df['belongs_to_collection'][0].keys()

dict_keys(['id', 'name', 'poster_path', 'backdrop_path'])

In [15]:
df.shape

(1, 27)

In [16]:
df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [17]:
df.dtypes

adult                       bool
backdrop_path             object
belongs_to_collection     object
budget                     int64
genres                    object
homepage                  object
id                         int64
imdb_id                   object
origin_country            object
original_language         object
original_title            object
overview                  object
popularity               float64
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                    int64
runtime                    int64
softcore                    bool
spoken_languages          object
status                    object
tagline                   object
title                     object
video                       bool
vote_average             float64
vote_count                 int64
dtype: object

In [18]:
df.select_dtypes(include='object').columns

Index(['backdrop_path', 'belongs_to_collection', 'genres', 'homepage',
       'imdb_id', 'origin_country', 'original_language', 'original_title',
       'overview', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'spoken_languages', 'status',
       'tagline', 'title'],
      dtype='object')

In [19]:
for col in df.columns:
    value = df[col].iloc[0]
    
    if isinstance(value, (dict, list)):
        print(col, type(value))

belongs_to_collection <class 'dict'>
genres <class 'list'>
origin_country <class 'list'>
production_companies <class 'list'>
production_countries <class 'list'>
spoken_languages <class 'list'>

In [20]:
for col in ['belongs_to_collection', 'genres', 'origin_country',
            'production_companies', 'production_countries', 'spoken_languages']:
    print(f"\n{col}:")
    print(df[col].iloc[0])

belongs_to_collection:
{'id': 2344, 'name': 'The Matrix Collection', 'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg', 'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'}

genres:
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}]

origin_country:
['US']

production_companies:
[{'id': 79, 'logo_path': '/at4uYdwAAgNRKhZuuFX8ShKSybw.png', 'name': 'Village Roadshow Pictures', 'origin_country': 'US'}, {'id': 372, 'logo_path': None, 'name': 'Groucho II Film Partnership', 'origin_country': ''}, {'id': 1885, 'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png', 'name': 'Silver Pictures', 'origin_country': 'US'}, {'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png', 'name': 'Warner Bros. Pictures', 'origin_country': 'US'}]

production_countries:
[{'iso_3166_1': 'US', 'name': 'United States of America'}]

spoken_languages:
[{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}]

In [21]:
collection = pd.json_normalize(df['belongs_to_collection'])
df = pd.concat([df.drop(columns='belongs_to_collection'), collection], axis=1)

In [22]:
df.columns

Index(['adult', 'backdrop_path', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'origin_country', 'original_language', 'original_title',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'softcore', 'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'id', 'name', 'poster_path',
       'backdrop_path'],
      dtype='object')

In [26]:
# genres
df['genres'] = df['genres'].apply(
    lambda x: ', '.join([i['name'] for i in x]) if isinstance(x, list) else None
)

# origin_country
df['origin_country'] = df['origin_country'].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else None
)

# production_companies
df['production_companies'] = df['production_companies'].apply(
    lambda x: ', '.join([i['name'] for i in x]) if isinstance(x, list) else None
)

# production_countries
df['production_countries'] = df['production_countries'].apply(
    lambda x: ', '.join([i['name'] for i in x]) if isinstance(x, list) else None
)

# spoken_languages
df['spoken_languages'] = df['spoken_languages'].apply(
    lambda x: ', '.join([i['english_name'] for i in x]) if isinstance(x, list) else None
)

In [27]:
for col in df.columns:
    value = df[col].iloc[0]
    
    if isinstance(value, (dict, list)):
        print(col, type(value))

belongs_to_collection <class 'dict'>

In [25]:
df.head()

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,...,status,tagline,title,video,vote_average,vote_count,id,name,poster_path,backdrop_path
0,False,/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg,63000000,"Action, Science Fiction",http://www.warnerbros.com/matrix,603,tt0133093,US,en,The Matrix,...,Released,Believe the unbelievable.,The Matrix,False,8.255,28505,2344,The Matrix Collection,/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg,/bRm2DEgUiYciDw3myHuYFInD7la.jpg

## Want to get data of multiple movies

### Getting multiple movie IDs

In [28]:
import tmdbsimple as tmdb

tmdb.API_KEY = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNTYxMzdjZmE5YmNhMjQzNTAzYmQ4MDQ4NzhhOGU4NiIsIm5iZiI6MTc4NzA2NDYzNS4zNDgsInN1YiI6IjZhODQ3MTNiNmUwYjI5OGZjMDU5NWQ4NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.qqY8hbOuCJtONtfCXNCs1FGLXP9EWpcUk6IVrqapfmY'
tmdb.USE_BEARER_AUTH = True

discover = tmdb.Discover()
response = discover.movie(page=1)

movies = response['results']

len(movies)

20

### Looking at the data

In [29]:
movies[0]

{'adult': False,
 'backdrop_path': '/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg',
 'genre_ids': [878, 28, 12],
 'id': 969681,
 'title': 'Spider-Man: Brand New Day',
 'original_language': 'en',
 'original_title': 'Spider-Man: Brand New Day',
 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
 'popularity': 1380.7869,
 'poster_path': '/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg',
 'release_date': '2026-07-29',
 'softcore': False,
 'video': False,
 'vote_average': 7.897,
 'vote_count': 2136}

In [30]:
movie.info()

{'adult': False,
 'backdrop_path': '/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg',
 'belongs_to_collection': {'id': 2344,
  'name': 'The Matrix Collection',
  'poster_path': '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg',
  'backdrop_path': '/bRm2DEgUiYciDw3myHuYFInD7la.jpg'},
 'budget': 63000000,
 'genres': [{'id': 28, 'name': 'Action'},
  {'id': 878, 'name': 'Science Fiction'}],
 'homepage': 'http://www.warnerbros.com/matrix',
 'id': 603,
 'imdb_id': 'tt0133093',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'The Matrix',
 'overview': 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
 'popularity': 42.1455,
 'poster_path': '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
 'production_companies': [{'id': 79,
   'logo_path': '/at4uYdwAAgNRKhZuuFX8ShKSybw.png',
   'name': 'Village Roadshow Pictures',
   'origin_country': 'US'},
  {'id': 372,
   'logo_path': None,
   'name': 'Groucho II Film Partnership',
   'origin_country': ''},
  {'id': 1885,
   'logo_path': '/xlvoOZr4s1PygosrwZyolIFe5xs.png',
   'name': 'Silver Pictures',
   'origin_country': 'US'},
  {'id': 174,
   'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png',
   'name': 'Warner Bros. Pictures',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '1999-03-31',
 'revenue': 463517383,
 'runtime': 136,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Believe the unbelievable.',
 'title': 'The Matrix',
 'video': False,
 'vote_average': 8.256,
 'vote_count': 28551}

### Extracting movie IDs

In [31]:
movie_ids = [movie['id'] for movie in movies]

movie_ids

[969681,
 1368337,
 1288445,
 1323244,
 1084244,
 1339713,
 1621552,
 634649,
 1108427,
 1375646,
 1315772,
 82023,
 1284465,
 1284041,
 1083381,
 1275779,
 1285366,
 1101383,
 1273221,
 1212763]

### Getting detailed information for every movie

In [32]:
all_movies = []

for movie_id in movie_ids:
    movie = tmdb.Movies(movie_id)
    data = movie.info()
    all_movies.append(data)

In [31]:
len(all_movies)

20

In [32]:
all_movies[0]

{'adult': False,
 'backdrop_path': '/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg',
 'belongs_to_collection': {'id': 531241,
  'name': 'Spider-Man (MCU) Collection',
  'poster_path': '/yeba3Y820OjApZO9aJevDsNeMEd.jpg',
  'backdrop_path': '/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg'},
 'budget': 225000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://spidermanbrandnewday.movie',
 'id': 969681,
 'imdb_id': 'tt22084616',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'Spider-Man: Brand New Day',
 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
 'popularity': 1875.3748,
 'poster_path': '/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'},
  {'id': 5,
   'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
   'name': 'Columbia Pictures',
   'origin_country': 'US'},
  {'id': 84041,
   'logo_path': '/nw4kyc29QRpNtFbdsBHkRSFavvt.png',
   'name': 'Pascal Pictures',
   'origin_country': 'US'},
  {'id': 22213,
   'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
   'name': 'TSG Entertainment',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2026-07-29',
 'revenue': 2039929225,
 'runtime': 145,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'A brand new day starts now.',
 'title': 'Spider-Man: Brand New Day',
 'video': False,
 'vote_average': 7.885,
 'vote_count': 1951}

### Creating the DataFrame

In [33]:
df = pd.DataFrame(all_movies)
df.head(2)

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg,"{'id': 531241, 'name': 'Spider-Man (MCU) Colle...",225000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://spidermanbrandnewday.movie,969681,tt22084616,[US],en,...,2039929225,145,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A brand new day starts now.,Spider-Man: Brand New Day,False,7.885,1951
1,False,/r57L2UBLPKcHdZQYg8tagv9XqK2.jpg,None,250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.universalpictures.com/movies/the-o...,1368337,tt33764258,"[GB, US]",en,...,1294477255,173,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Defy the gods.,The Odyssey,False,8.000,2969

In [36]:
df.shape  # Data of 20 movies

(20, 27)

In [37]:
df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [38]:
nested_cols = []

for col in df.columns:
    if df[col].apply(lambda x: isinstance(x, (dict, list))).any():
        nested_cols.append(col)

nested_cols

['belongs_to_collection',
 'genres',
 'origin_country',
 'production_companies',
 'production_countries',
 'spoken_languages']

In [39]:
collection = pd.json_normalize(df['belongs_to_collection'])

collection = collection.rename(columns={
    'id': 'collection_id',
    'name': 'collection_name',
    'poster_path': 'collection_poster_path',
    'backdrop_path': 'collection_backdrop_path'
})

df = pd.concat(
    [df.drop(columns='belongs_to_collection'), collection],
    axis=1
)

In [40]:
df[['id', 'title', 'collection_id', 'collection_name']].head()

,id,title,collection_id,collection_name
0,969681,Spider-Man: Brand New Day,531241.0,Spider-Man (MCU) Collection
1,1368337,The Odyssey,NaN,NaN
2,634649,Spider-Man: No Way Home,531241.0,Spider-Man (MCU) Collection
3,1084244,Toy Story 5,10194.0,Toy Story Collection
4,1323244,Rage of Stars,NaN,NaN

In [41]:
df['genres'] = df['genres'].apply(
    lambda x: ', '.join(i['name'] for i in x) if isinstance(x, list) else None
)

# origin_country
df['origin_country'] = df['origin_country'].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else None
)

# production_companies
df['production_companies'] = df['production_companies'].apply(
    lambda x: ', '.join(i['name'] for i in x) if isinstance(x, list) else None
)

# production_countries
df['production_countries'] = df['production_countries'].apply(
    lambda x: ', '.join(i['name'] for i in x) if isinstance(x, list) else None
)

# spoken_languages
df['spoken_languages'] = df['spoken_languages'].apply(
    lambda x: ', '.join(i['english_name'] for i in x) if isinstance(x, list) else None
)

In [42]:
for col in df.columns:
    if df[col].apply(lambda x: isinstance(x, (dict, list))).any():
        print(col)

In [43]:
df.shape

(20, 30)

In [44]:
df.dtypes

adult                          bool
backdrop_path                object
budget                        int64
genres                       object
homepage                     object
id                            int64
imdb_id                      object
origin_country               object
original_language            object
original_title               object
overview                     object
popularity                  float64
poster_path                  object
production_companies         object
production_countries         object
release_date                 object
revenue                       int64
runtime                       int64
softcore                       bool
spoken_languages             object
status                       object
tagline                      object
title                        object
video                          bool
vote_average                float64
vote_count                    int64
collection_id               float64
collection_name              object
collection_poster_path       object
collection_backdrop_path     object
dtype: object

In [46]:
df.head(2)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,...,status,tagline,title,video,vote_average,vote_count,collection_id,collection_name,collection_poster_path,collection_backdrop_path
0,False,/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg,225000000,"Science Fiction, Action, Adventure",https://spidermanbrandnewday.movie,969681,tt22084616,US,en,Spider-Man: Brand New Day,...,Released,A brand new day starts now.,Spider-Man: Brand New Day,False,7.885,1951,531241.0,Spider-Man (MCU) Collection,/yeba3Y820OjApZO9aJevDsNeMEd.jpg,/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg
1,False,/r57L2UBLPKcHdZQYg8tagv9XqK2.jpg,250000000,"Adventure, Action, Fantasy",https://www.universalpictures.com/movies/the-o...,1368337,tt33764258,"GB, US",en,The Odyssey,...,Released,Defy the gods.,The Odyssey,False,8.000,2969,NaN,NaN,NaN,NaN

### Checking missing values

In [47]:
df.isna().sum().sort_values(ascending=False)

collection_name             13
collection_id               13
collection_backdrop_path    13
collection_poster_path      13
adult                        0
backdrop_path                0
imdb_id                      0
origin_country               0
original_language            0
original_title               0
budget                       0
genres                       0
homepage                     0
id                           0
production_companies         0
poster_path                  0
popularity                   0
overview                     0
production_countries         0
release_date                 0
revenue                      0
runtime                      0
tagline                      0
status                       0
spoken_languages             0
softcore                     0
vote_count                   0
vote_average                 0
video                        0
title                        0
dtype: int64

In [48]:
missing_pct = (df.isna().sum() / len(df) * 100).sort_values(ascending=False)

missing_pct

collection_name             65.0
collection_id               65.0
collection_backdrop_path    65.0
collection_poster_path      65.0
adult                        0.0
backdrop_path                0.0
imdb_id                      0.0
origin_country               0.0
original_language            0.0
original_title               0.0
budget                       0.0
genres                       0.0
homepage                     0.0
id                           0.0
production_companies         0.0
poster_path                  0.0
popularity                   0.0
overview                     0.0
production_countries         0.0
release_date                 0.0
revenue                      0.0
runtime                      0.0
tagline                      0.0
status                       0.0
spoken_languages             0.0
softcore                     0.0
vote_count                   0.0
vote_average                 0.0
video                        0.0
title                        0.0
dtype: float64

In [53]:
df[df.isna().any(axis=1)].head()

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,...,status,tagline,title,video,vote_average,vote_count,collection_id,collection_name,collection_poster_path,collection_backdrop_path
1,False,/r57L2UBLPKcHdZQYg8tagv9XqK2.jpg,250000000,"Adventure, Action, Fantasy",https://www.universalpictures.com/movies/the-o...,1368337,tt33764258,"GB, US",en,The Odyssey,...,Released,Defy the gods.,The Odyssey,False,8.000,2969,NaN,No Collection,NaN,NaN
4,False,/z7lZgL5tzefTfhyRtouThFhsuUS.jpg,0,"Action, Science Fiction, Thriller",,1323244,tt29512655,PL,en,Rage of Stars,...,Released,,Rage of Stars,False,4.833,6,NaN,No Collection,NaN,NaN
5,False,/84FEpVVbSKYvKXDZJDZXOKBxCEm.jpg,0,"Action, Horror, Science Fiction",https://wellgousa.com/films/colony,1375646,tt34385135,KR,ko,군체,...,Released,Survive the hive.,Colony,False,8.104,549,NaN,No Collection,NaN,NaN
7,False,/1RhfevWmWCVHtEqxWBEjPOC5KG1.jpg,0,"Horror, Science Fiction, Thriller",https://www.netflix.com/title/81914143,1284041,tt32268156,US,en,The Last House,...,Released,How long can you survive?,The Last House,False,6.908,896,NaN,No Collection,NaN,NaN
8,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,750000,"Horror, Thriller",http://www.focusfeatures.com/obsession,1339713,tt37287335,US,en,Obsession,...,Released,Be careful who you wish for…,Obsession,False,8.228,4849,NaN,No Collection,NaN,NaN

### Focusing only on that columns which have missing values

In [49]:
missing = df.isna().sum()

missing[missing > 0].sort_values(ascending=False)

collection_id               13
collection_name             13
collection_poster_path      13
collection_backdrop_path    13
dtype: int64

### Understanding why belongs_to_collection has missing values

For movies that don't belong to a collection, TMDB returns: None

It means: This movie doesn't belong to a collection.

Therefore, we should not automatically replace it with the mean, median, or mode.

In [50]:
df['collection_name'] = df['collection_name'].fillna('No Collection')
df['collection_name']

0         Spider-Man (MCU) Collection
1                       No Collection
2         Spider-Man (MCU) Collection
3                Toy Story Collection
4                       No Collection
5                       No Collection
6                  Minions Collection
7                       No Collection
8                       No Collection
9                       No Collection
10                      No Collection
11                      No Collection
12                      No Collection
13    Evil Dead Standalone Collection
14                      No Collection
15                      No Collection
16                      No Collection
17                      No Collection
18            The Avengers Collection
19        Spider-Man (MCU) Collection
Name: collection_name, dtype: object

In [54]:
df['release_date'].dtype

dtype('O')

In [55]:
df[['budget', 'revenue', 'runtime', 'popularity', 'vote_average', 'vote_count']].dtypes

budget            int64
revenue           int64
runtime           int64
popularity      float64
vote_average    float64
vote_count        int64
dtype: object

In [56]:
df['release_date'] = pd.to_datetime(df['release_date'])

In [57]:
df['release_date'].dtype

dtype('<M8[ns]')

### Check for duplicate movies

In [58]:
df['id'].duplicated().sum()

np.int64(0)

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df['id'].nunique()

20

In [61]:
len(df)

20

In [1]:
import requests
import pandas as pd

In [2]:
base_url = "https://api.themoviedb.org"

In [3]:
end_point = "/3/movie/popular"

In [4]:
final_url = base_url + end_point
final_url

'https://api.themoviedb.org/3/movie/popular'

In [5]:
access_token = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2YTdkM2IwZjUyZjAxMWFjNTUwNWRjYTUyOTVmZjIyYSIsIm5iZiI6MTc4NzA2NDYwNi45Njk5OTk4LCJzdWIiOiI2YTg0NzExZTE3M2FjN2JlNjE1OTU5YTgiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.TByo6oaVIW8ZKKELWM87Ql8p_yQquok3wHbsCm0MyCI"

In [6]:
headers = {
    "Authorization": f"Bearer {access_token}",
    "accept": "application/json"
}

In [7]:
all_movies = []

for page in range(1,31):
    response = requests.get(final_url, headers=headers, params = {"page":page})

    if response.status_code == 200:
        data = response.json()
        all_movies.extend(data["results"])
    else:
        print(f"Error on page {page}: {response.status_code}")

df = pd.DataFrame(all_movies)

In [8]:
df.shape

(600, 15)

 What characteristics are associated with successful movies, and how has the movie industry changed over time?
The analysis should help answer questions around:

Which genres perform best?
Are highly rated movies actually popular?
Does a bigger audience lead to higher ratings?
Which years produced the strongest movies?
Has movie production increased over time?
Which genres dominate the industry?
Does movie popularity depend on ratings?
Are highly voted movies more reliable than movies with very few votes?
Which movies should a streaming platform consider for acquisition or promotion?

TMDB provides endpoints for popular movies, top-rated movies, and a powerful /discover/movie endpoint with many filtering and sorting options.
Analyze TMDB movie data to identify:

Movie industry trends
High-performing genres
Relationship between ratings and popularity
Relationship between ratings and vote counts
Most successful release periods
Characteristics of highly successful movies
Movies with strong audience engagement
Potential recommendations for a streaming/movie company

In [9]:
df.head(2)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,1257.7257,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.887,2198
1,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",609.3017,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,7.988,3226

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              600 non-null    bool
 1   backdrop_path      591 non-null    object
 2   genre_ids          600 non-null    object
 3   id                 600 non-null    int64
 4   title              600 non-null    object
 5   original_language  600 non-null    object
 6   original_title     600 non-null    object
 7   overview           600 non-null    object
 8   popularity         600 non-null    float64
 9   poster_path        600 non-null    object
 10  release_date       600 non-null    object
 11  softcore           600 non-null    bool
 12  video              600 non-null    bool
 13  vote_average       600 non-null    float64
 14  vote_count         600 non-null    int64
dtypes: bool(3), float64(2), int64(2), object(8)
memory usage: 58.1+ KB

In [11]:
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'title',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'release_date', 'softcore', 'video', 'vote_average',
       'vote_count'],
      dtype='object')

In [12]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

In [19]:
df['id'].duplicated().sum()

np.int64(9)

In [20]:
df = df.drop_duplicates(subset='id')

In [21]:
df['id'].duplicated().sum()

np.int64(0)

In [13]:
df['release_year'] = df['release_date'].dt.year

df[['title', 'release_year', 'popularity', 'vote_average', 'vote_count']].head()

,title,release_year,popularity,vote_average,vote_count
0,Spider-Man: Brand New Day,2026.0,1257.7257,7.887,2198
1,The Odyssey,2026.0,609.3017,7.988,3226
2,Mutiny,2026.0,507.5238,6.500,181
3,Rage of Stars,2026.0,292.9905,5.565,46
4,Facing El Chapo,2026.0,327.4675,8.749,213

In [22]:
df.isnull().sum()

adult                0
backdrop_path        9
genre_ids            0
id                   0
title                0
original_language    0
original_title       0
overview             0
popularity           0
poster_path          0
release_date         1
softcore             0
video                0
vote_average         0
vote_count           0
release_year         1
dtype: int64

In [23]:
df[['popularity', 'vote_average', 'vote_count']].describe()

        popularity  vote_average    vote_count
count   591.000000    591.000000    591.000000
mean     40.944824      7.028264   8295.401015
std      67.558086      1.338826   8600.468470
min      16.203000      0.000000      0.000000
25%      21.387800      6.643500    634.500000
50%      26.007500      7.294000   5311.000000
75%      37.224600      7.822500  13718.000000
max    1257.725700      9.300000  40913.000000

In [25]:
df['release_year'].dtype

dtype('float64')

In [26]:
df=pd.read_csv('popular_movies.csv')

In [27]:
df.head(2)

,Unnamed: 0,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,0,False,/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,1346.7581,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.893,2163
1,1,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",620.9085,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,7.992,3198

In [28]:
df.columns

Index(['Unnamed: 0', 'adult', 'backdrop_path', 'genre_ids', 'id', 'title',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'release_date', 'softcore', 'video', 'vote_average',
       'vote_count'],
      dtype='object')

In [29]:
df.drop(columns='Unnamed: 0',inplace=True)

In [30]:
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'title',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'release_date', 'softcore', 'video', 'vote_average',
       'vote_count'],
      dtype='object')